
(TEMP-TABLE::ATTRIBUTE-RELATION
 :OBJECT-NUMBER 1421732899
 :NAME :_GUI_RA_MODULE
 :COMMENT :|ihm.project_type_module|
 :DATASET 1238591899
 :DOCUMENTATION "Fields used to defined project type linked module"
 :NCLASS IO-ORDO::PROJECT-TYPE
 :OPTIONAL T
 :RELATION-NAME "Projects types"
 :TYPE TEMP-TABLE::_GUI_PT_MODULES
)