
(TEMP-TABLE::ATTRIBUTE-RELATION
 :OBJECT-NUMBER 44063999
 :NAME :_PE_RA_EQUA_ACTCL
 :COMMENT :|PE.Equation.action_class|
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATEMP
 :OPTIONAL T
 :RELATION-NAME "Equation template(s)"
 :TYPE TEMP-TABLE::_PE_PT_EQUA_OBJECTCLASS
)