
(TEMP-TABLE::ATTRIBUTE-RELATION
 :OBJECT-NUMBER 44063499
 :NAME :_PE_RA_EQUA_RES
 :COMMENT :|resource.plural|
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATION
 :OPTIONAL T
 :RELATION-NAME "Resource"
 :TYPE KERNEL-ORDO:RESOURCE
)