
(TEMP-TABLE::ATTRIBUTE-RELATION
 :OBJECT-NUMBER 44064299
 :NAME :_PE_RA_EQUA_EQFA
 :COMMENT :|PE.Equation.equation|
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQFILATT
 :RELATION-NAME "Equation filter attribute(s)"
 :SAVE-WITH T
 :TYPE TEMP-TABLE::_PE_PT_EQUA_EQUATION
)