
(TEMP-TABLE::ATTRIBUTE-RELATION
 :OBJECT-NUMBER 44063799
 :NAME :_PE_RA_EQUA_CBS
 :COMMENT :|costAccount|
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATION
 :OPTIONAL T
 :RELATION-NAME "Equation(s)"
 :TYPE DOD:CBS-NODE
)