
(TEMP-TABLE::ATTRIBUTE-RELATION
 :OBJECT-NUMBER 44064099
 :NAME :_PE_RA_EQUA_ETAAET
 :COMMENT :|PE.Equation.equation_template|
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_ACTIONATT
 :OPTIONAL T
 :RELATION-NAME "Equation template action attribute(s)"
 :SAVE-WITH T
 :TYPE TEMP-TABLE::_PE_PT_EQUA_EQUATEMP
)