
(TEMP-TABLE::ATTRIBUTE-RELATION
 :OBJECT-NUMBER 44063699
 :NAME :_PE_RA_EQUA_COSTUNIT
 :COMMENT :|costUnit|
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATION
 :OPTIONAL T
 :RELATION-NAME "Cost unit"
 :TYPE DOD:COST-UNIT
)