
(TEMP-TABLE::ATTRIBUTE-RELATION
 :OBJECT-NUMBER 44063599
 :NAME :_PE_RA_EQUA_EQET
 :COMMENT :|PE.Equation.equation_template|
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATION
 :OPTIONAL T
 :RELATION-NAME "Equation(s)"
 :TYPE TEMP-TABLE::_PE_PT_EQUA_EQUATEMP
)