
(TEMP-TABLE::ATTRIBUTE-RELATION
 :OBJECT-NUMBER 44696699
 :NAME :_PE_RA_EQUA_OBS
 :COMMENT :|responsibility|
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATION
 :OPTIONAL T
 :RELATION-NAME "Equation(s)"
 :TYPE KERNEL-ORDO:OBS-NODE
)