
(TEMP-TABLE::ATTRIBUTE-RELATION
 :OBJECT-NUMBER 4997975799
 :NAME :_TCCONV_RA_USER
 :COMMENT "User"
 :DATASET 96270999
 :NCLASS TEMP-TABLE::_TC_PT_CONV_TIMECARD
 :OPTIONAL T
 :RELATION-NAME "User"
 :TYPE GENERIC-IO:OPX2-USER
)