
(TEMP-TABLE::ATTRIBUTE-RELATION
 :OBJECT-NUMBER 82914599
 :NAME :_PE_RA_EQUA_WBS
 :COMMENT "Activity Type"
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATION
 :OPTIONAL T
 :RELATION-NAME "Equation(s)"
 :TYPE TEMP-TABLE::WBS_TYPE
)