
(TEMP-TABLE::_SCIM_PT_FIELD_MAPPING
 :OBJECT-NUMBER 296644942441
 :DATASET 118057330253
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :SCIM_AA_S_INTERNAL_NAME "EMAIL_ADDRESS"
 :_SCIM_AA_AT_MAP_TYPE "User"
 :_SCIM_AA_N_KEYS 0.0d0
 :_SCIM_AA_S_FIELD_NAME "emails[type eq \"work\"].value"
 :_SCIM_RA_USER_SCRIPT 0
)