
(TEMP-TABLE::_SCIM_PT_FIELD_MAPPING
 :OBJECT-NUMBER 296644941841
 :DATASET 118057330253
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :SCIM_AA_S_INTERNAL_NAME "USER_ATTRIBUTE_SAN_UA_S_AD_LOCALITY"
 :_SCIM_AA_AT_MAP_TYPE "User"
 :_SCIM_AA_N_KEYS 0.0d0
 :_SCIM_AA_S_FIELD_NAME "addresses[type eq \"work\"].locality"
 :_SCIM_RA_USER_SCRIPT 0
)