
(TEMP-TABLE::_SCIM_PT_FIELD_MAPPING
 :OBJECT-NUMBER 310242048841
 :DATASET 118057330253
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :SCIM_AA_S_INTERNAL_NAME "_DMP_AA_S_PSEUDO"
 :_SCIM_AA_AT_MAP_TYPE "User"
 :_SCIM_AA_N_KEYS 0.0d0
 :_SCIM_AA_S_FIELD_NAME "urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:User:networkId"
 :_SCIM_RA_USER_SCRIPT 0
)