
(TEMP-TABLE::_SCIM_PT_FIELD_MAPPING
 :OBJECT-NUMBER 317268925441
 :DATASET 118057330253
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :SCIM_AA_S_INTERNAL_NAME "ONB"
 :_SCIM_AA_AT_CONTENTS "LIST"
 :_SCIM_AA_AT_MAP_TYPE "UserGroup"
 :_SCIM_AA_N_KEYS 1.0d0
 :_SCIM_AA_S_FIELD_NAME "id"
 :_SCIM_RA_USER_SCRIPT 0
)