
(REPORT-OBJECTS::PRESENTATION
 :OBJECT-NUMBER 142734869041
 :NAME "GISC Reporting"
 :DATASET 118081000141
 :DISPLAY-OBJECT-LABEL T
 :HEADER-PRINT-DATE T
 :HEADER-PRINT-PAGE-NUMBER T
 :HEADER-PRINT-TOTAL-PAGE-NUMBER T
 :OBJECT-LABEL "=_INF_DA_S_LEGEND_LABEL"
 :ORDER-NUMBER 0
 :ORIENTATION :LANDSCAPE
 :OWNER 5625
 :PAPER-FORMAT 0
 :POWERPOINT-TEMPLATE 0
 :_EE_AA_B_SCREEN_SET "0"
 :_PRES_AA_B_WRITE "0"
 :_PRES_RA_DATE_STYLE 0
)