
(TEMP-TABLE::_ADM_PT_DATA_CLASS
 :OBJECT-NUMBER 260000437872
 :NAME "RDPM - Test system"
 :COMMENT "Test system"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_ADM_AA_B_ADD_NEW_LINES "1"
 :_ADM_AA_B_CREA_DEFAULT "0"
 :_ADM_AA_B_DISPLAY_CFG "1"
 :_ADM_AA_B_DISP_PO_FILTER "0"
 :_ADM_AA_B_REQ_PO_FILTER "0"
 :_ADM_AA_S_CLASS "__USER_TABLE_SAN_RDPM_UT_TST_SYS"
 :_ADM_AA_S_DEF_DATA_RW "R_ITS_ADMIN,OR_FUNCT_ADM_VACCINES"
 :_ADM_AA_S_FILE_FORMULA "\"SAN_CF_RDPM_COMMON_DATA_VACCINES\""
 :_ADM_RA_DEF_TABLE_STYLE 0
 :_ELASTIC_AA_N_WEIGHT 0.0d0
 :_EL_RA_DEFAULT_MODULE 0
)