
(MESSAGE-STRING::MESSAGE
 :OBJECT-NUMBER 99921099
 :NAME "etc"
 :DATASET 96270999
 :ORIGIN :PROJECT
 :PARENT 7205399
 :VALUE #/E"ETC"F"RAF"G"Erwarteter Restaufwand"I"ETC"D"ETC"J"ETC"S"ETC"K"ETC"C"ETC"P"ETC"R"Прогноз до завершения"/
)