
(NEW-ATTRIBUTE::USER-TABLE-ELEMENT
 :OBJECT-NUMBER 310375089974
 :NAME "Requestor_Insourcing_Cancelled_To be validated_Business Partner"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :PARENT 0
 :SOURCE-DCR-SYNC-OBJECTS 0
 :USER-TABLE :SAN_RDPM_UT_SOURCING_REQUEST_NOTIFICATION
)