
(TEMP-TABLE::_GUI_PT_PANEL_TOOLS
 :OBJECT-NUMBER 119838980499
 :NAME "ABOUT"
 :COMMENT "#@ihm.aboutPlanisware"
 :DATASET 1238591899
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :_GUI_AA_B_TOOLS "1"
 :_GUI_AA_S_CORE_NAME "ABOUT_PLW"
 :_PLW_AA_S_BOOKMARKED_ICON "Ic_about_planisware_40px"
 :_PLW_AA_S_MENU_ICON "Ic_about_planisware_40px"
 :_PLW_MENU_AA_B_DISPLAY "1"
 :_PLW_MENU_AA_N_ORDER 1.0d0
 :_PLW_MENU_AA_S_CALLBACK "_GuiAboutPlanisware"
 :_PLW_MENU_AA_S_CATEGORY "EXPERT"
)