
(TEMP-TABLE::_GUI_PT_PANEL_TOOLS
 :OBJECT-NUMBER 1711472099
 :NAME "COMPUTE"
 :COMMENT "#@ihm._GUI_ATV_S_COMPUTE_FN"
 :DATASET 1238591899
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :_GUI_AA_B_TOOLS "0"
 :_GUI_AA_S_CORE_NAME "COMPUTE_FN"
 :_PLW_MENU_AA_B_DISPLAY "0"
 :_PLW_MENU_AA_N_ORDER 0.0d0
)