
(TEMP-TABLE::_GUI_PT_PANEL_TOOLS
 :OBJECT-NUMBER 118110633899
 :NAME "FTE"
 :COMMENT "#@ihm.planisware_menu.display_in_fte_menu"
 :DATASET 1238591899
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :_GUI_AA_B_TOOLS "1"
 :_GUI_AA_S_CORE_NAME "FTE"
 :_PLW_AA_S_BOOKMARKED_ICON "ic_display_fte_40px"
 :_PLW_AA_S_MENU_ICON "ic_display_fte_40px"
 :_PLW_MENU_AA_B_DISPLAY "1"
 :_PLW_MENU_AA_N_ORDER 7.0d0
 :_PLW_MENU_AA_S_CALLBACK "FteToolCallback"
 :_PLW_MENU_AA_S_CATEGORY "DISPLAY"
)