
(TEMP-TABLE::_GUI_PT_PANEL_TOOLS
 :OBJECT-NUMBER 1719445899
 :NAME "REDO"
 :COMMENT "#@ihm.redo"
 :DATASET 1238591899
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :_GUI_AA_B_TOOLS "1"
 :_GUI_AA_S_CORE_NAME "REDO"
 :_PLW_AA_S_BOOKMARKED_ICON "Ic_redo_40px"
 :_PLW_AA_S_MENU_ICON "Ic_redo_40px"
 :_PLW_MENU_AA_B_DISPLAY "1"
 :_PLW_MENU_AA_N_ORDER 2.0d0
 :_PLW_MENU_AA_S_CALLBACK "planiswaremenumod.PlaniswaremenuCallbackRedo"
 :_PLW_MENU_AA_S_CATEGORY "EDITION"
)