
(TEMP-TABLE::_GUI_PT_PANEL_TOOLS
 :OBJECT-NUMBER 1711474199
 :NAME "SIGMA"
 :COMMENT "#@ihm._GUI_ATV_S_SIGMA_FN"
 :DATASET 1238591899
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :_GUI_AA_B_TOOLS "1"
 :_GUI_AA_S_CORE_NAME "SIGMA_FN"
 :_PLW_AA_S_BOOKMARKED_ICON "Ic_open-close_40px"
 :_PLW_AA_S_MENU_ICON "Ic_open-close_40px"
 :_PLW_MENU_AA_B_DISPLAY "1"
 :_PLW_MENU_AA_N_ORDER 4.0d0
 :_PLW_MENU_AA_S_CALLBACK "planiswaremenumod.PlaniswaremenuCallBackSigma"
 :_PLW_MENU_AA_S_CATEGORY "EDITION"
)