
(TEMP-TABLE::_GUI_PT_PANEL_TOOLS
 :OBJECT-NUMBER 1711472199
 :NAME "SPELL-CHECKER"
 :COMMENT "#@ihm._GUI_ATV_S_SPELL_CHECKER_FN"
 :DATASET 1238591899
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :_GUI_AA_B_TOOLS "0"
 :_GUI_AA_S_CORE_NAME "SPELL_CHEC"
 :_PLW_MENU_AA_B_DISPLAY "0"
 :_PLW_MENU_AA_N_ORDER 0.0d0
)