
(TEMP-TABLE::_GUI_PT_PANEL_TOOLS
 :OBJECT-NUMBER 1711474999
 :NAME "UNLOCK"
 :COMMENT "#@ihm._GUI_ATV_S_UNLOCK_FN"
 :DATASET 1238591899
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :_GUI_AA_B_TOOLS "1"
 :_GUI_AA_S_CORE_NAME "UNLOCK_FN"
 :_PLW_AA_S_BOOKMARKED_ICON "ic_lock_open_40px"
 :_PLW_AA_S_MENU_ICON "ic_lock_open_40px"
 :_PLW_MENU_AA_B_DISPLAY "0"
 :_PLW_MENU_AA_N_ORDER 0.0d0
 :_PLW_MENU_AA_S_CALLBACK "planiswaremenumod.PlaniswaremenuLockunlock"
)