
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 117995573553
 :NAME :SAN_RWE_UA_S_PROD_ALT_PROD_NAME
 :COMMENT "Product Alternative Product Names"
 :DATASET 118057330253
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_PRODUCT
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)