
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 117935412621
 :NAME :SAN_UA_RWE_IS_NOT_TEMPLATE
 :COMMENT "Is not a template?"
 :DATASET 118057330253
 :FORMULA "_INF_NF_S_PRJ_STATE_INTERNAL<>\"TEMPLATE\""
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)