
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 117935433329
 :NAME :SAN_RWE_UA_S_PRODUCT
 :COMMENT "Product"
 :DATASET 118057330253
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum| :|Continuum.eSTRA|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::...__USER_TABLE_SAN_RWE_UT_PRODUCT
)