
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 117951832255
 :NAME :SAN_RWE_UA_S_INDICATION_DESC
 :COMMENT "Indication (Desc)"
 :DATASET 118057330253
 :FORMULA "SAN_RWE_UA_S_INDICATION.DESC"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)