
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 117947054655
 :NAME :SAN_UA_RWE_INDICATION
 :COMMENT "Study Indication"
 :DATASET 118057330253
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_PRIME_CODES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RWE_UT_INDICATION
)