
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 117925163450
 :NAME :SAN_RWE_UA_S_INDICATION
 :COMMENT "Indication"
 :DATASET 118057330253
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RWE_UT_INDICATION
)