
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 117951831955
 :NAME :SAN_RWE_UA_PRJ_S_THERAP_AREA_DESC
 :COMMENT "Therapeutic Area (Desc)"
 :DATASET 118057330253
 :FORMULA "SAN_RWE_UA_PRJ_S_THERAP_AREA.DESC"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.eSTRA|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)