
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 117995562653
 :NAME :SAN_UA_RWE_B_USED_BY_STUDY
 :COMMENT "Used by study"
 :DATASET 118057330253
 :FORMULA "ITER_BOOLEAN_THERE_IS_ONE(\"PROJECT\",\"SAN_UA_RWE_PROJECT_CODE_PRIME =\\\"\"+NAME+\"\\\"\") "
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_PROJECT_CODES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)