
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 118082593241
 :NAME :SAN_UA_RDPM_RES_EFSD_PTC
 :COMMENT "Effective Start Date in the Period TM"
 :DATASET 118081000141
 :FORMULA "effective_start_date <PERIOD_START($DATE_OF_THE_DAY,\"MONTH\",1) "
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)