
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 118081785941
 :NAME :SAN_UA_RDPM_B_TIMECARD_NOTIF
 :COMMENT "Timecard Email Notification Activated?"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)