
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 118000660553
 :NAME :SAN_UA_S_PRIME_STUDY_STATUS
 :COMMENT "Prime Study status"
 :DATASET 118057330253
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)