
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 118082588041
 :NAME :SAN_UA_RDPM_PROJECT_TYPE
 :COMMENT "Project's dataset class"
 :DATASET 118081000141
 :FORMULA "PROJECT.DATASET_CLASS"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)