
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 118082548541
 :NAME :SAN_UA_RDPM_S_PROJECT_TC
 :COMMENT :RDPM.SAN_RDPM_TK_PROJECT_NAME
 :DATASET 118081000141
 :FORMULA "project.SAN_RDPM_UA_PRJ_S_ROOT_PROJECT"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)