
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 118064382553
 :NAME :SAN_UA_B_CF_TO_DELIVER
 :COMMENT "Common file to deliver"
 :DATASET 118057330253
 :NCLASS GENERIC-IO:COMMON-DATASET
 :PTYPES (:|Continuum|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)