
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 118001698653
 :NAME :SAN_UA_RWE_S_STUDY_LEADERSHIP
 :COMMENT "Study Leadership (IMPACT)"
 :DATASET 118057330253
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:OBS-NODE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :STUDY_LEAD
)