
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 118038427155
 :NAME :SAN_UA_RWE_PRIME_UPDATE
 :COMMENT "Prime update"
 :DATASET 118057330253
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)