
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142738700172
 :NAME :SAN_UA_RDPM_RES_TYP_PHAR
 :COMMENT "Resource Pharma"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "from(oc.SAN_RDPM_CS_RES_PHARMA)"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)