
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142734693472
 :NAME :SAN_RDPM_UA_RES_BACKUP
 :COMMENT "Resource Backup"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE GENERIC-IO::...GROUP-OR-USER
)