
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142736346641
 :NAME :SAN_UA_RDPM_RES_AVAIL_SD
 :COMMENT "Today's Availability Start Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "ITER_DATE_MAX(\"Availabilities\",\"(SD=-1 OR SD<=$DATE_OF_THE_DAY) AND (FD=-1 OR FD>= $DATE_OF_THE_DAY)\",\"SD\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)