
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142736599941
 :NAME :SAN_RDPM_RES_TYP_REP
 :COMMENT "Type of replacement"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :TYPE_OF_REPLACEMENT
)