
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142738843073
 :NAME :SAN_RDPM_UA_LOC_COST_UNIT
 :COMMENT "Default Cost unit"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE DOD:COST-UNIT
)