
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142737283941
 :NAME :SAN_UA_RDPM_RES_CTR_TYP
 :COMMENT :RDPM.SAN_RDPM_TK_CONTRACT_TYPE
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_RES_CTR_TYP
)