
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142735468841
 :NAME :SAN_RDPM_B_RND_VACCINES_PROJECT
 :COMMENT "R&D Vaccines Project"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"PROJECT_TYPE\",\"Continuum.RDPM.Pasteur\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)