
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142732894041
 :NAME :SAN_UA_RDPM_RES_TC_MANAGER
 :COMMENT "Resource timecard manager"
 :DATASET 118081000141
 :FORMULA "\"Timecard Manager: \"+STRING_VALUE(\"User\",STRING_VALUE(\"RESOURCE\",OC._TC_AA_S_RESOURCE,\"MANAGER\"),\"DESC\")"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)