
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142732642941
 :NAME :SAN_UA_RDPM_TC_DEADLINE
 :COMMENT "Timecard validation deadline"
 :DATASET 118081000141
 :FORMULA "\"Deadline for input: \"+DATE_VALUE(\"_L1_PT_FISCAL_MONTH\",SAN_UA_RDPM_CURRENT_ACC_CAL_ID,\"_L1_NF_FM_END_DATE\") "
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)