
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142736466741
 :NAME :SAN_UA_RDPM_RES_AVAIL_PCT
 :COMMENT "Today's Availability %"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "ITER_NUMBER_SUM(\"Availabilities\",\"(SD=-1 OR SD<=$DATE_OF_THE_DAY) AND (FD=-1 OR FD>= $DATE_OF_THE_DAY) AND ( TYPE =\\\"Absence\\\" OR TYPE=\\\"Standard\\\")\",\"PCT*QTY\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)