
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142736767441
 :NAME :SAN_UA_RDPM_SKIL_S_OPERA
 :COMMENT "Operationality"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:RESOURCE-SKILL
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :OPERATIONALITY
)