
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142732859141
 :NAME :SAN_UA_RDPM_RES_AVAIL_TYP
 :COMMENT "Today's Availability Type"
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"Availabilities\",\"(SD=-1 OR SD<=$DATE_OF_THE_DAY) AND (FD=-1 OR FD>= $DATE_OF_THE_DAY)\",\"TYPE\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)