
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142736741241
 :NAME :SAN_AL_RDPM_RES_LAST_GEN
 :COMMENT "Is the last level typed generic resource?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "_INF_AA_B_GENERIC_RES AND NOT(ITER_BOOLEAN_THERE_IS_ONE(\"ELEMENTS\",\"_INF_AA_B_GENERIC_RES AND NOT SAN_RDPM_UA_B_IS_A_TEAM\"))"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)