
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142732661541
 :NAME :SAN_UA_RDPM_VALIDATION_DATE_NON_PRECISE_DATE_FORMAT
 :COMMENT "Validation date (non precise date format)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "DAY(VALIDATION_DATE )"
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)