
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142734885270
 :NAME :SAN_UA_RDPM_TC_NOTIF_DEADLINE
 :COMMENT "Timecard validation deadline (date format)"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "SAN_UA_RDPM_ACC_CAL_END_DATE"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)