
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142733075541
 :NAME :SAN_UA_RDPM_ACC_CAL_END_DATE
 :COMMENT "Actual accounting month end date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "DATE_VALUE(\"_L1_PT_FISCAL_MONTH\",SAN_UA_RDPM_CURRENT_ACC_CAL_ID,\"_L1_NF_FM_END_DATE\") "
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)