
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142732640841
 :NAME :SAN_UA_RDPM_CURRENT_ACC_CAL_ID
 :COMMENT "Current month accounting calendar ID"
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"_L1_PT_FISCAL_MONTH\",\"_L1_AA_D_FM_START_DATE <= $date_of_the_day AND _L1_NF_FM_END_DATE >= $date_of_the_day\",\"ID\")"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)