
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142734856472
 :NAME :SAN_RDPM_UA_AT_B_TECH_MIL
 :COMMENT "Technical milestone?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::WBS_TYPE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)