
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142737307441
 :NAME :SAN_RDPM_UA_RES_SHARED
 :COMMENT "Shared?"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_S_TYP_MOV_IN.SAN_RDPM_UA_TYPE_MOV_SHARED OR SAN_RDPM_UA_S_TYP_MOV_OUT.SAN_RDPM_UA_TYPE_MOV_SHARED"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)