
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142732869241
 :NAME :SAN_UA_RDPM_RES_SERV
 :COMMENT :RDPM.SAN_RDPM_TK_SERVICE
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_RES_TYP_PHAR THEN (IF SAN_RDPM_UA_RES_ENT_TYP=\"Service\" THEN name ELSE IF SAN_RDPM_UA_RES_ENT_TYP<>\"Service\" THEN ELEMENT_OF.SAN_UA_RDPM_RES_SERV FI FI) ELSE \"\" FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)