
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142738699872
 :NAME :SAN_UA_RDPM_RES_TYP_PAST
 :COMMENT "Resource Pasteur"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "from(oc.SAN_RDPM_CS_RES_VACCINE)"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)