
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142732598441
 :NAME :SAN_UA_RDPM_B_IS_A_STUDY
 :COMMENT "Is a study?"
 :DATASET 118081000141
 :FORMULA "WBS_TYPE.SAN_RDPM_UA_AT_B_STUDY"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM| :|Roadmap|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)