
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142736734041
 :NAME :SAN_RDPM_RES_B_EXCL_HEAD
 :COMMENT "Excluded from Headcount?"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)