
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 142736747241
 :NAME :SAN_UA_RDPM_RES_TYP
 :COMMENT "Legal entity"
 :DATASET 118081000141
 :FORMULA "IF ( SAN_UA_RDPM_RES_TYP_PHAR  or SAN_UA_RDPM_RES_TYP_PAST  )  AND SAN_RDPM_UA_RES_ENT_TYP=\"Legal entity\" THEN NAME ELSE IF SAN_RDPM_UA_RES_ENT_TYP<>\"Legal entity\" THEN ELEMENT_OF.SAN_UA_RDPM_RES_TYP FI FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)