
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143364520570
 :NAME :SAN_RDPM_UA_PRIM_SKILL
 :COMMENT :RDPM.SAN_RDPM_TK_PRIM_SKILL
 :DATASET 118081000141
 :FORMULA "RESOURCE.PRIMARY_SKILL "
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)