
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143364521970
 :NAME :SAN_RDPM_UA_TC_MAN_EMAIL
 :COMMENT :RDPM.SAN_RDPM_TK_TC_MAN_EMAIL
 :DATASET 118081000141
 :FORMULA "RESOURCE._JIRA_NF_S_MANAGER_EMAIL "
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)