
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143364519170
 :NAME :SAN_RDPM_UA_DEPARTMENT
 :COMMENT :RDPM.SAN_RDPM_TK_DEPARTMENT
 :DATASET 118081000141
 :FORMULA "RESOURCE.SAN_UA_RDPM_RES_DEP "
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)