
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143370317270
 :NAME :SAN_RDPM_RES_BAS_ENTITY
 :COMMENT "Base Entity"
 :DATASET 118081000141
 :FORMULA "RESOURCE.SAN_RDPM_RES_BAS_ENTITY"
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_BAS_ENT
)