
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143374953173
 :NAME :SAN_RDPM_UA_CAL_B_RESOURCE
 :COMMENT "Resource calendar?"
 :DATASET 118081000141
 :NCLASS CALENDAR:CALENDAR
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)