
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143370400470
 :NAME :SAN_RDPM_UA_PRJ_PORTFOLIO
 :COMMENT "Portfolio"
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_UA_PM_PRJ_PORT.SAN_UA_PROJ_PORTF_L2"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)