
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143364522970
 :NAME :SAN_RDPM_UA_TODAY_AVAIL_TYPE
 :COMMENT :RDPM.SAN_RDPM_TK_TODAY_AVAIL_TYPE
 :DATASET 118081000141
 :FORMULA "RESOURCE.SAN_UA_RDPM_RES_AVAIL_TYP "
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)