
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143394083373
 :NAME :SAN_RDPM_UA_LOC_S_OVT_CAL
 :COMMENT "Default Overtime calendar"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)