
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143364520270
 :NAME :SAN_RDPM_UA_PLATFORM
 :COMMENT :RDPM.SAN_RDPM_TK_PLATFORM
 :DATASET 118081000141
 :FORMULA "RESOURCE.SAN_UA_RDPM_RES_PLAT "
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)