
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143364761172
 :NAME :SAN_RDPM_UA_LK_NOTEPAD
 :COMMENT "Notepad"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:CONSTRAINT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:MULTI-LINE-STRING
)