
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143365844873
 :NAME :SAN_RDPM_UA_ACT_B_OPL
 :COMMENT "Operational level? (F)"
 :DATASET 118081000141
 :FORMULA "NOT SAN_RDPM_UA_ACT_B_PRJL"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur| :|Roadmap|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)