
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143364521670
 :NAME :SAN_RDPM_UA_SKILLS
 :COMMENT :|teamMember.step.4|
 :DATASET 118081000141
 :FORMULA "RESOURCE.SKILLS "
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)