
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143363918241
 :NAME :SAN_UA_RDPM_B_IS_RD_RES
 :COMMENT "R&D Resource"
 :DATASET 118081000141
 :FORMULA "SAN_UA_RDPM_RES_TYP_PAST OR SAN_UA_RDPM_RES_TYP_PHAR"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)