
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143364922170
 :NAME :SAN_RDPM_B_END_DATE_APPROACHING
 :COMMENT "End date approaching?"
 :DATASET 118081000141
 :FORMULA "EFFECTIVE_END_DATE > DAY($DATE_OF_THE_DAY ) AND EFFECTIVE_END_DATE <= PERIOD_START($DATE_OF_THE_DAY ,\"DAY\",31)  AND NOT _INF_AA_B_GENERIC_RES"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)