
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143364529670
 :NAME :SAN_RDPM_UA_RES_SITE
 :COMMENT :|resourceManager.Location|
 :DATASET 118081000141
 :FORMULA "RESOURCE._RM_REVIEW_RA_LOCATION "
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)