
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143364619372
 :NAME :SAN_RDPM_UA_RES_DEP_GRP
 :COMMENT "Department grouping"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_RES_TYP_PAST THEN (IF SAN_RDPM_UA_RES_ENT_TYP=\"Department grouping\" THEN name ELSE IF SAN_RDPM_UA_RES_ENT_TYP<>\"Department grouping\" THEN ELEMENT_OF.SAN_RDPM_UA_RES_DEP_GRP FI FI) ELSE \"\" FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)