
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143365013574
 :NAME :SAN_UA_S_RES_FORM_TYPE_CALC
 :COMMENT "Resource form type (calculated)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF _INF_AA_B_GENERIC_RES=TRUE THEN  \"Standard\"    ELSE IF SAN_UA_RDPM_RES_TYP_PHAR THEN   \"R&D Pharma\"    ELSE IF SAN_UA_RDPM_RES_TYP_PAST THEN   \"R&D Pasteur\"     ELSE    \"Standard\"     FI   FI   FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)