
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143364521370
 :NAME :SAN_RDPM_UA_SERVICE
 :COMMENT :RDPM.SAN_RDPM_TK_SERVICE
 :DATASET 118081000141
 :FORMULA "RESOURCE.SAN_UA_RDPM_RES_SERV"
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)