
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484010473
 :NAME :SAN_RDPM_UA_ACT_B_CONTAIN_ACTUALS
 :COMMENT "Has actuals?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "ITER_BOOLEAN_THERE_IS_ONE(\"INCURRED-EXPENDITURES\",\"TRUE\") OR ITER_BOOLEAN_THERE_IS_ONE(\"WORK-PERFORMED\",\"TRUE\") OR ?STARTED "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)