
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484002473
 :NAME :SAN_UA_ACT_STUDY_CODE
 :COMMENT "Internal Study Code"
 :DATASET 118057330253
 :IS-INDEXED T
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM| :|Continuum.eSTRA|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RWE_PRIME_CODES
)