
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485729971
 :NAME :SAN_RDPM_UA_D_EXITING_DATE_PREDEV
 :COMMENT "Exiting Date (PreDev)"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)