
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485730871
 :NAME :SAN_RDPM_UA_S_ADDITIONAL_COMMS_TERMINATION
 :COMMENT "Additional Comments on Termination / Closure"
 :DATASET 118081000141
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)