
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485559041
 :NAME :SAN_UA_RDPM_RES_DEP_DESC
 :COMMENT "Department (desc)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_RES_ENT_TYP=\"Department\" THEN         desc     ELSE         ELEMENT_OF.SAN_UA_RDPM_RES_DEP_DESC     FI "
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)