
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484006071
 :NAME :SAN_UA_RDPM_B_CRITICAL
 :COMMENT "Critical?"
 :DATASET 118081000141
 :FORMULA "IF CF<= '10d' THEN TRUE ELSE IF CF > '10d' THEN FALSE FI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)