
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485559541
 :NAME :SAN_UA_RDPM_RES_FUNCT_DESC
 :COMMENT "Function (desc)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_RES_ENT_TYP=\"Function\" THEN         desc     ELSE         ELEMENT_OF.SAN_UA_RDPM_RES_FUNCT_DESC     FI "
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)