
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143488103472
 :NAME :SAN_RDPM_UA_SR_DIFF_PREVAL
 :COMMENT "Difference From Previous Evaluation"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "SAN_RDPM_UA_SR_POTS_SR - number(list_collect(\"SuccessRates\",\"file=\\\"\"+project+\"\\\" and onb=\\\"\"+SAN_RDPM_UA_SR_LASTONB+\"\\\"\",\"SAN_RDPM_UA_SR_POTS_SR\"),\"####\")"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_SR
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)