
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484021571
 :NAME :SAN_RDPM_UA_DEVIATION_ROOT_CAUSE
 :COMMENT "Deviation root cause"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :DEVIATION_ROOT_CAUSE
)