
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485729371
 :NAME :SAN_RDPM_UA_PROJECT_SITE
 :COMMENT "Project Site"
 :DATASET 118081000141
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
)