
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143488839571
 :NAME :SAN_RDPM_UA_S_PREVIOUS_MONTHLY_BL_NAME
 :COMMENT "Name of the previous monthly Baseline"
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_UA_S_LAST_MONTHLY"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)