
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484014471
 :NAME :SAN_RDPM_UA_DPT_GRPING
 :COMMENT "Department Grouping"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_FUNCTION.CHILD_OF"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)