
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484790670
 :NAME :SAN_RDPM_UA_ORIGIN_OF_NME
 :COMMENT "Origin of NME"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur.Project|
          :|Continuum.RDPM.Pharma.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_ORIGIN_OF_NME
)