
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484174670
 :NAME :SAN_RDPM_UA_B_APAO_PROJ
 :COMMENT "APAO Project?"
 :DATASET 118081000141
 :FORMULA "boolean_value(\"project\",project.SAN_RDPM_UA_PRJ_S_ROOT_PROJECT,\"SAN_RDPM_UA_B_APAO_PROJ\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)