
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484698871
 :NAME :SAN_RDPM_UA_LK_S_SUCC_TYPE
 :COMMENT "Successor Activity type"
 :DATASET 118081000141
 :FORMULA "SA.WBS_TYPE"
 :NCLASS KERNEL-ORDO:CONSTRAINT
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)