
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484829970
 :NAME :SAN_RDPM_UA_B_PAST_ACTIVITY
 :COMMENT "R&D Vaccines Project"
 :DATASET 118081000141
 :FORMULA "Project.SAN_RDPM_B_RND_VACCINES_PROJECT"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)