
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485561041
 :NAME :SAN_UA_RDPM_RES_OP_DEP_DESC
 :COMMENT "OP Department (desc)"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_RES_OP_SERV <> \"\" THEN SAN_UA_RDPM_RES_OP_SERV.SAN_UA_RDPM_RES_DEP_DESC ELSE \"\" FI "
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)