
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143436675343
 :NAME :SAN_UA_S_ROOT_PRODUCT
 :COMMENT "Root Product"
 :DATASET 118057330253
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.eSTRA|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RWE_UT_PRODUCT
)