
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143488132971
 :NAME :SAN_RDPM_UA_YEARLY_BL_FINISH_DATE
 :COMMENT "Yearly Baseline Finish Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF SAN_RDPM_UA_B_YEARLY_EXIST =TRUE  THEN DATE_VALUE(\"Activity\",ID,\"FD_YEARLY_VACCINES\") ELSE -1 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)