
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485556241
 :NAME :SAN_UA_RDPM_RES_DEP_FIN_CODE
 :COMMENT "Department Finance Code"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_RES_TYP_PHAR THEN         IF SAN_RDPM_UA_RES_ENT_TYP=\"Department\" THEN             obs_element         ELSE             ELEMENT_OF.SAN_UA_RDPM_RES_DEP_FIN_CODE         FI     ELSE         \"\"     FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)