
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485560541
 :NAME :SAN_UA_RDPM_RES_LE_DESC
 :COMMENT "Legal Entity (desc)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_RES_ENT_TYP=\"Legal Entity\" THEN         desc     ELSE         ELEMENT_OF.SAN_UA_RDPM_RES_LE_DESC     FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)