
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143483988773
 :NAME :SAN_RDPM_UA_LK_S_TYPE
 :COMMENT "Type"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF PA.SAN_RDPM_UA_ACT_B_PRJL THEN \"PL\" ELSE IF PA.SAN_RDPM_UA_ACT_B_OPL THEN \"OL\" FI FI + \" - \" + IF SUCC_ACTIVITY.SAN_RDPM_UA_ACT_B_PRJL THEN \"PL\" ELSE IF SUCC_ACTIVITY.SAN_RDPM_UA_ACT_B_OPL THEN \"OL\" FI FI"
 :NCLASS KERNEL-ORDO:CONSTRAINT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)