
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485729671
 :NAME :SAN_RDPM_UA_D_ENTERING_DATE_PREDEV
 :COMMENT "Entering Date (PreDev)"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)