
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143491573772
 :NAME :SAN_RDPM_UA_SR_LASTONB
 :COMMENT "Last Success rate"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "ITER_NUMBER_MAX(\"SuccessRates\",\"file=\\\"\"+file+\"\\\" and onb<\\\"\"+onb+\"\\\" \",\"onb\")"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_SR
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)