
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484014174
 :NAME :SAN_RDPM_UA_OC_S_MONTHLY_BASELINE_NAME
 :COMMENT "Monthly Baseline Name"
 :DATASET 118081000141
 :FORMULA "SUBSTITUTE(\"_\",\"-\",PRINT_DATE($DATE_OF_THE_DAY,\"YYYY-MM\"))"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)