
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485770971
 :NAME :SAN_RDPM_UA_PRTF_MAIN
 :COMMENT "Portfolio main"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_PM_PRJ_PORT.SAN_UA_PROJ_PORTF_L2"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)