
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485558541
 :NAME :SAN_UA_RDPM_RES_SERV_DESC
 :COMMENT "Service (desc)"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_RES_TYP_PHAR THEN  	IF SAN_RDPM_UA_RES_ENT_TYP=\"Service\" THEN  		desc  	ELSE  		ELEMENT_OF.SAN_UA_RDPM_RES_SERV_DESC  	FI ELSE  	\"\"  FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)