
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485552541
 :NAME :SAN_UA_RDPM_RES_OP_SERV
 :COMMENT "Operational Service"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE KERNEL-ORDO:RESOURCE
)