
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484698271
 :NAME :SAN_RDPM_UA_LK_S_SUCC_NAT
 :COMMENT "Nature of successor"
 :DATASET 118081000141
 :FORMULA "SA.SAN_RDPM_UA_ACT_S_NAT_ACT"
 :NCLASS KERNEL-ORDO:CONSTRAINT
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)