
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484570941
 :NAME :SAN_RDPM_UA_RD_PROJECT
 :COMMENT "R&D Project"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_B_RND_PHARMA_PROJECT OR SAN_RDPM_B_RND_VACCINES_PROJECT"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)