
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485742571
 :NAME :SAN_RDPM_UA_GEOGRAPHICAL_TARGET
 :COMMENT "Geographical Target (Global Market)"
 :DATASET 118081000141
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::...__USER_TABLE_SAN_RDPM_UT_GEOGRAPHICAL_TARGET
)