
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143487336071
 :NAME :SAN_RDPM_UA_ED_BL1_FD
 :COMMENT "Baseline 1 End Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "DATE_VALUE(\"ACTIVITY\",ID,\"FD_\" + LIST_COLLECT(\"_PM_TT_SELECTED_COMP_TYPES\",\"TYPE_NUMBER=1\",\"NAME\"))"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)