
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485561341
 :NAME :SAN_UA_RDPM_RES_OP_SERV_FIN_CODE
 :COMMENT "OP Service Finance Code"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_RES_OP_SERV <> \"\" THEN SAN_UA_RDPM_RES_OP_SERV.SAN_UA_RDPM_RES_SERV_FIN_CODE ELSE \"\" FI "
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)