
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485660974
 :NAME :SAN_RDPM_UA_S_M_2_MONTHLY
 :COMMENT "M-2 Monthly Baseline"
 :DATASET 118081000141
 :FORMULA "SUBSTITUTE(\"_\",\"-\",PRINT_DATE(PERIOD_START($DATE_OF_THE_DAY,\"MONTH\",-2),\"YYYY-MM\"))"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)