
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143486443670
 :NAME :SAN_RDPM_UA_VACC_PROJ_CAT
 :COMMENT "Vaccine Project Category"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :VACCINES_PROJ_CAT
)