
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485579570
 :NAME :SAN_RDPM_UA_PHARMA_PROJECT_PHASE
 :COMMENT "Is Pharma Project Phase?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::WBS_TYPE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)