
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143483995573
 :NAME :SAN_RDPM_UA_OC_B_HIDE_PL_OL_LK
 :COMMENT "Hide PL - OL links"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)