
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485560041
 :NAME :SAN_UA_RDPM_RES_BU_DESC
 :COMMENT "Business Unit (desc)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_RES_ENT_TYP=\"Business Unit\" THEN         desc     ELSE         ELEMENT_OF.SAN_UA_RDPM_RES_BU_DESC     FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)