
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484726171
 :NAME :SAN_RDPM_UA_S_MOA
 :COMMENT "Mechanism of action"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur.Project|
          :|Continuum.RDPM.Pharma.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)