
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484174970
 :NAME :SAN_RDPM_UA_APAO_PROJ_LIST
 :COMMENT "APAO Project List"
 :DATASET 118081000141
 :FORMULA "string_value(\"project\",project.SAN_RDPM_UA_PRJ_S_ROOT_PROJECT,\"SAN_RDPM_UA_APAO_PROJ_LIST\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)