
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143484771770
 :NAME :SAN_RDPM_UA_PROJ_MOLECULE_TYPE
 :COMMENT "Entity Type"
 :DATASET 118081000141
 :FORMULA "LIST_REMOVE_DUPLICATES(STRING_VALUE(\"__USER_TABLE_SAN_RDPM_UT_MOLECULE_TYPE\",SAN_RDPM_DA_MOLECULE_SUB_TYPE,\"SAN_RDPM_UT_MOLECULE_TYPE\")) "
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)