
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143483995273
 :NAME :SAN_RDPM_UA_OC_B_HIDE_PL_PL_LK
 :COMMENT "Hide PL - PL links"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)