
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143487335771
 :NAME :SAN_RDPM_UA_D_BL1_SD
 :COMMENT "Baseline 1 Start Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "DATE_VALUE(\"ACTIVITY\",ID,\"SD_\" + LIST_COLLECT(\"_PM_TT_SELECTED_COMP_TYPES\",\"TYPE_NUMBER=1\",\"NAME\"))"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)