
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143485579870
 :NAME :SAN_RDPM_UA_VACCINES_PROJECT_PHASE
 :COMMENT "Is Vaccines Project Phase?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::WBS_TYPE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)