
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 143695151843
 :NAME :SAN_RWE_UA_S_RWI_DESC
 :COMMENT "Scientific Expert"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"USER\",SAN_RWE_UA_S_RWI,\"DESC\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.eSTRA|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)