
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 258982480673
 :NAME :SAN_RDPM_UA_PRJ_S_ROOT_PROJECT
 :COMMENT "Root project"
 :DATASET 118081000141
 :FORMULA "IF PARENT_PROJECT=\"\" THEN ID ELSE PARENT_PROJECT.SAN_RDPM_UA_PRJ_S_ROOT_PROJECT FI"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)