
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 258996274175
 :NAME :SAN_RDPM_UA_USER_EMAIL
 :COMMENT "Email"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"USER\",SAN_RDPM_UA_USER,\"EMAIL_ADDRESS\")"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)