
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 258997106875
 :NAME :SAN_RDPM_UA_SCOPE
 :COMMENT "Scope"
 :DATASET 118081000141
 :FORMULA "FILE.DESC"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)