
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 258981902971
 :NAME :SAN_RDPM_S_CONDITION
 :COMMENT "Condition"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_TARGET_POP
 :POSSIBLE-VALUES "Traveler population,At risk population,All population,To,<,>,<=,>=,=,<>"
 :PTYPES (:|Continuum.RDPM.Pasteur.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)