
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 258983110682
 :NAME :SAN_UA_B_IS_ACT_CMC
 :COMMENT "? is there a CMC activity"
 :DATASET 118081000141
 :FORMULA "ITER_BOOLEAN_THERE_IS_ONE(\"CHILDREN\",\"SAN_RDPM_UF_OBS_CMC\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)