
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 259002430175
 :NAME :SAN_RDPM_UA_PROJECT_ROLE_DESC
 :COMMENT "Role Description"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_PROJECT_ROLE.DESC"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)