
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260024919771
 :NAME :SAN_RDPM_UA_CLIN_INDICATION
 :COMMENT "Clinical Indication"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::...__USER_TABLE_SAN_RWE_UT_INDICATION
)