
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008233370
 :NAME :SAN_RDPM_UA_MAIN_TYPE_OF_MOVE_IN
 :COMMENT "Main type of move IN"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_S_TYP_MOV_IN.SAN_RDPM_UT_RES_TYPE_MOV"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)