
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260033384070
 :NAME :SAN_RDPM_UF_ACT_BPS_INDICATION_STATUS
 :COMMENT "Indication Status (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_ACT_BPS_INDICATION_STATUS <> \"\" then SAN_RDPM_UA_ACT_BPS_INDICATION_STATUS ELSE WBS_ELEMENT.SAN_RDPM_UF_ACT_BPS_INDICATION_STATUS FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)