
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260041630171
 :NAME :SAN_RDPM_UA_PREVIOUS_MONTH_ACC_CAL_START_DATE
 :COMMENT "Previous month accounting calendar start date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "DATE_VALUE(\"_L1_PT_FISCAL_MONTH\",SAN_RDPM_UA_OC_PREVIOUS_MONTH_ACC_CAL_ID,\"_L1_AA_D_FM_START_DATE\") "
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)