
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260006678074
 :NAME :SAN_UA_N_COMPLEXITY_FACTOR
 :COMMENT "Complexity factor (stored value)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 1.0d0
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_WBS_FORM_DATA
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)