
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260081321071
 :NAME :SAN_RDPM_UA_B_IS_GNG_PO
 :COMMENT "Is Go / No Go?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::WBS_TYPE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)