
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260000025273
 :NAME :SAN_RDPM_UA_ACT_S_REPORT_MILE_TYPE
 :COMMENT "Reporting Milestone Type"
 :DATASET 118081000141
 :FORMULA "if  WBS_TYPE.SAN_RDPM_UA_AT_REPORT_MILE_TYPE=\"Project Objective\" then \"01- Portfolio movements based on changes of phases\" else  WBS_TYPE.SAN_RDPM_UA_AT_REPORT_MILE_TYPE fi"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)