
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 26000122872
 :NAME :SAN_RDPM_UA_ACT_STAD_STAT
 :COMMENT "Study status"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN IF SAN_RDPM_UA_ACT_STAD_STAT_INP=\"Active\" THEN SAN_RDPM_UF_ACT_S_SCHEDULING_STUDY_STATUS ELSE SAN_RDPM_UA_ACT_STAD_STAT_INP FI ELSE WBS_ELEMENT.SAN_RDPM_UA_ACT_STAD_STAT FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)