
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260071270573
 :NAME :SAN_RDPM_UA_PH_S_WBS_TYPE
 :COMMENT "Activity Type"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.WBS_TYPE"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)