
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008129773
 :NAME :SAN_UA_SC_S_STUDY_TYPE_TITLE
 :COMMENT "Study Title"
 :DATASET 118057330253
 :FORMULA "STRING_VALUE(\"wbs_type\",SAN_UA_SC_STUDY_TYPE,\"SAN_RDPM_UA_AT_S_STUDY_TYPE_TITLE\") "
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_PRIME_CODES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)