
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260019736371
 :NAME :SAN_RDPM_UA_SPECIFICITY_AND_TOOLS
 :COMMENT "Specificity & Tools"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_SPECIFICITY_AND_TOOLS
)