
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260048083670
 :NAME :SAN_RDPM_UF_S_BAS_ENTITY_MANAGEMENT_CENTER_DESC
 :COMMENT "Management Center description"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_RES_BAS_ENTITY.SAN_RDPM_UT_BAS_ENT.DESC"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)