
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008233070
 :NAME :SAN_RDPM_UA_DEFAULT_PERC_DIRECT
 :COMMENT "Default % Direct"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "PRIMARY_SKILL.SAN_UA_RDPM_SKIL_PERCT_DIRECT"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)