
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260000024773
 :NAME :SAN_RDPM_UA_AT_REPORT_MILE_TYPE
 :COMMENT "Reporting Milestone Type"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::WBS_TYPE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_REPORT_MILE_TYPE
)