
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260019777571
 :NAME :SAN_RDPM_UA_COUNTRY_MAPPING
 :COMMENT "Country Mapping"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::...__USER_TABLE_SAN_RWE_UT_COUNTRY
)