
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260019660571
 :NAME :SAN_RDPM_UA_PROJECT_PRIO
 :COMMENT "Project Priority (F)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"PROJECT\",PROJECT.SAN_RDPM_UA_PRJ_S_ROOT_PROJECT,\"SAN_RDPM_UA_PRJ_S_PRIORITY\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)