
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260067359576
 :NAME :SAN_RDPM_UA_ACT_CALCULATED_MOLECULE_SUB_TYPE
 :COMMENT "Entity Sub-Type (F)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"PROJECT\",PROJECT.SAN_RDPM_UA_PRJ_S_ROOT_PROJECT,\"SAN_RDPM_DA_MOLECULE_SUB_TYPE\") "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)