
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008233670
 :NAME :SAN_RDPM_UA_MAIN_TYPE_OF_MOVE_OUT
 :COMMENT "Main type of move OUT"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_S_TYP_MOV_OUT.SAN_RDPM_UT_RES_TYPE_MOV"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)