
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260025551271
 :NAME :SAN_RDPM_UA_DATA_CAPTURE_F
 :COMMENT "Data Capture (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_DATA_CAPTURE_DASTORE <> \"\" THEN SAN_RDPM_UA_DATA_CAPTURE_DASTORE ELSE WBS_ELEMENT.SAN_RDPM_UA_DATA_CAPTURE_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)