
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260067790871
 :NAME :SAN_RDPM_UA_S_ROOT_PROJECT_MOA
 :COMMENT "Mechanism of Action (MoA) (F)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"PROJECT\",PROJECT.SAN_RDPM_UA_PRJ_S_ROOT_PROJECT,\"SAN_RDPM_DA_S_MOA\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)