
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260000337672
 :NAME :SAN_RDPM_UA_ACT_PROD_ACT
 :COMMENT "Product (act) "
 :DATASET 118081000141
 :FORMULA "if SAN_RDPM_UA_ACT_VAC_PROD<>\"\" then SAN_RDPM_UA_ACT_VAC_PROD else wbs_element.SAN_RDPM_UA_ACT_PROD_ACT fi "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)