
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260020018871
 :NAME :SAN_RDPM_UA_CLUSTER_CODE
 :COMMENT "Cluster Code"
 :DATASET 118081000141
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE KERNEL-ORDO:OBS-NODE
)