
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260010123170
 :NAME :SAN_RDPM_UA_RES_DEP_FIN_CODE
 :COMMENT "Department Finance code"
 :DATASET 118081000141
 :FORMULA "RESOURCE.SAN_UA_RDPM_RES_DEP_FIN_CODE"
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)