
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260081322471
 :NAME :SAN_RDPM_UA_B_INDICATION_NOT_STOPPED
 :COMMENT "Indication is different than \"Stopped\"?"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_ACT_BPS_INDICATION_STATUS.DESC <> \"Stopped\""
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)