
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260071164674
 :NAME :SAN_UA_ACT_B_PATIENT_STUDY_F
 :COMMENT "Is a Patient study? (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN SAN_UA_ACT_B_PATIENT_STUDY ELSE WBS_ELEMENT.SAN_UA_ACT_B_PATIENT_STUDY_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)