
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260067011572
 :NAME :SAN_RDPM_UA_B_SITE_CSU_COUNT
 :COMMENT "Is a CSU Country?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)