
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260010466474
 :NAME :SAN_UA_RDPM_B_AUTOPROGRESS
 :COMMENT "Autoprogress?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "?TASK AND AS<>\"\" AND AF=\"\" "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)