
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260006962582
 :NAME :SAN_RDPM_UA_ABSENCE
 :COMMENT "Has an absence?"
 :DATASET 118081000141
 :FORMULA "ITER_BOOLEAN_THERE_IS_ONE(\"Availabilities\",\"TYPE=\\\"Absence\\\"\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)