
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260019698071
 :NAME :SAN_RDPM_UA_IRT
 :COMMENT "IRT"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :IRT
)