
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260006675474
 :NAME :SAN_UA_WBS_FORM_DATA_ACTIVITY
 :COMMENT "WBS Form Activity"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_WBS_FORM_DATA
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE KERNEL-ORDO:WORK-STRUCTURE
)