
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260048083370
 :NAME :SAN_RDPM_UF_S_BAS_ENTITY_MANAGEMENT_CENTER_NAME
 :COMMENT "Management Center name"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_RES_BAS_ENTITY.SAN_RDPM_UT_BAS_ENT.NAME"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)