
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260067790571
 :NAME :SAN_RDPM_UA_S_ROOT_PROJECT_DESC
 :COMMENT "Project Description (F)"
 :DATASET 118081000141
 :FORMULA "Project.SAN_RDPM_UF_S_PROJECT_DESCRIPTION"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)