
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260067793871
 :NAME :SAN_RDPM_UA_B_IS_RBM_STUDY_F
 :COMMENT "Is a RBM study? (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN SAN_RDPM_UA_B_IS_RBM_STUDY ELSE WBS_ELEMENT.SAN_RDPM_UA_B_IS_RBM_STUDY_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)