
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260000016770
 :NAME :SAN_RDPM_UA_COUNTRY
 :COMMENT "Country"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RWE_UT_COUNTRY
)