
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260020019471
 :NAME :SAN_RDPM_UA_CLUSTER_DESC
 :COMMENT "Cluster Description"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_CLUSTER_CODE.DESC"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)