
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260000305172
 :NAME :SAN_RDPM_UA_ACT_PROD_COMM
 :COMMENT "Product Comments"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)