
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008233970
 :NAME :SAN_RDPM_UA_ABSENCE_ONGOING
 :COMMENT "Absence ongoing"
 :DATASET 118081000141
 :FORMULA "LIST_LENGTH(LIST_COLLECT(\"Availabilities\",\"TYPE=\\\"Absence\\\" and SD < $date_of_the_day and FD > $date_of_the_day\",\"id\")) > 0"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)