
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260048961670
 :NAME :SAN_RDPM_UF_PRIMARY_SKILL_OPERATIONALITY
 :COMMENT "Default Operationality"
 :DATASET 118081000141
 :FORMULA "PRIMARY_SKILL.SAN_UA_RDPM_SKIL_S_OPERA"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)