
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260041629371
 :NAME :SAN_RDPM_UA_OC_PREVIOUS_MONTH_ACC_CAL_ID
 :COMMENT "Previous month accounting calendar ID"
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"_L1_PT_FISCAL_MONTH\",\"_L1_AA_D_FM_START_DATE <= DATE_ADDMONTH($DATE_OF_THE_DAY,-1) AND _L1_NF_FM_END_DATE >= DATE_ADDMONTH($DATE_OF_THE_DAY,-1)\",\"ID\")"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)