
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008021373
 :NAME :SAN_UA_RDPM_ACT_S_STUDY_ID
 :COMMENT "Study Identifier"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN ID ELSE WBS_ELEMENT.SAN_UA_RDPM_ACT_S_STUDY_ID FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)