
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260001211672
 :NAME :SAN_RDPM_UA_ACT_S_STEP_NAME
 :COMMENT "Step Name"
 :DATASET 118081000141
 :FORMULA "if wbs_type.SAN_RDPM_UA_AT_B_IS_STEP then name else wbs_element.SAN_RDPM_UA_ACT_S_STEP_NAME   fi "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)