
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260048946270
 :NAME :SAN_RDPM_SKILL_S_ROL_TYP
 :COMMENT "Skill Type"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:RESOURCE-SKILL
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_ROLE_TYPE
)