
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008130673
 :NAME :SAN_UA_SC_S_STUDY_INDICATION_SUFFIX
 :COMMENT "Study Indication Suffix"
 :DATASET 118057330253
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_PRIME_CODES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)