
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260001893773
 :NAME :SAN_RDPM_UA_PRJ_S_DISCO_DEV_CODE
 :COMMENT "Disco/ Dev linked codes"
 :DATASET 118081000141
 :FORMULA "SAN_UA_RWE_PROJECT_CODE_PRIME.SAN_RDPM_UA_PC_S_DISCO_DEV_CODE"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)