
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260026744770
 :NAME :SAN_RDPM_UA_PLANNED_NUM_SAMPLE
 :COMMENT "Planned # Samples"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)