
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260029470172
 :NAME :SAN_RDPM_UA_SITE_CSU_CTR_CONSO
 :COMMENT "CSU Country Consolidation"
 :DATASET 118081000141
 :FORMULA "string_value(\"_RM_REVIEW_PT_LOCATIONS\",SAN_RDPM_UA_SITE_CSU_CONSO,\"SAN_RDPM_UA_COUNTRY\")"
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)