
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260010123470
 :NAME :SAN_RDPM_UA_RES_SERV_FIN_CODE
 :COMMENT "Service Finance code"
 :DATASET 118081000141
 :FORMULA "RESOURCE.SAN_UA_RDPM_RES_SERV_FIN_CODE"
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)