
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260009358174
 :NAME :SAN_UA_RDPM_S_ROLE
 :COMMENT "Role"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UR_WBS_FORM_MAP_LEADER
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::_RM_REVIEW_PT_ROLE
)