
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008083773
 :NAME :SAN_UA_PC_B_OCCUPIED
 :COMMENT "Occupied?"
 :DATASET 118057330253
 :FORMULA "ITER_BOOLEAN_THERE_IS_ONE(\"USER_ATTRIBUTE_INVERSE_SAN_UA_RWE_PROJECT_CODE_PRIME.ORDO-PROJECT\",\"_INF_NF_S_PRJ_STATE_INTERNAL=\\\"ACTIVE\\\"  AND  _PM_NF_B_IS_A_VERSION=FALSE\") "
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_PROJECT_CODES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)