
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260048954570
 :NAME :SAN_RDPM_UF_PRIMARY_SKILL_MAIN_SKILL
 :COMMENT "Main skill name"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_B_IS_MAIN_SKILL THEN NAME ELSE PARENT_SKILL.SAN_RDPM_UF_PRIMARY_SKILL_MAIN_SKILL FI"
 :NCLASS KERNEL-ORDO:RESOURCE-SKILL
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)