
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260067210772
 :NAME :SAN_RDPM_UA_PHAR_ADMIN_ROUTE
 :COMMENT "Administration route"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::...__USER_TABLE_SAN_RDPM_UT_ADMINISTRATION_ROUTE
)