
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260009678274
 :NAME :SAN_UA_RDPM_WBS_FORM_SERV_DESC
 :COMMENT "Service Desc"
 :DATASET 118081000141
 :FORMULA "_RM_REVIEW_RA_RES.SAN_UA_RDPM_RES_SERV_DESC"
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_ROLE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)