
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008090673
 :NAME :SAN_UA_PC_PROJECT_OWNER
 :COMMENT "Project Owner"
 :DATASET 118057330253
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_PROJECT_CODES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE KERNEL-ORDO:OBS-NODE
)