
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008090073
 :NAME :SAN_UA_PC_PROJECT_STATUS
 :COMMENT "Project Status"
 :DATASET 118057330253
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_PROJECT_CODES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::_STA_PT_PRJ_STATUS
)