
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008193373
 :NAME :SAN_RDPM_UA_ACT_OBS_CALCULATED_BUDGET_OWNER
 :COMMENT "Budget Owner (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_ACT_OBS_BUDGET_OWNER<>\"\" THEN SAN_RDPM_UA_ACT_OBS_BUDGET_OWNER ELSE WBS_ELEMENT.SAN_RDPM_UA_ACT_OBS_CALCULATED_BUDGET_OWNER FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)