
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260025574071
 :NAME :SAN_RDPM_UA_STUDY_SCOPE_F
 :COMMENT "Study Scope (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_STUDY_SCOPE_DASTORE <> \"\" THEN SAN_RDPM_UA_STUDY_SCOPE_DASTORE ELSE WBS_ELEMENT.SAN_RDPM_UA_STUDY_SCOPE_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)