
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260002049471
 :NAME :SAN_RDPM_UA_CMC_PORTFOLIO
 :COMMENT "CMC Portfolio"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Project|
          :|Continuum.RDPM.Pasteur.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :CMC_PORTFOLIO
)