
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260000183970
 :NAME :SAN_RDPM_UA_S_STUDY_CODE
 :COMMENT "Internal Study Code"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_ACT_S_CALCULATED_STUDY_CODE"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)