
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260024887571
 :NAME :SAN_RDPM_UA_ACT_THERAPEUTIC_AREA_F
 :COMMENT "ATC Code (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_ACT_THERAPEUTIC_AREA <> \"\" THEN SAN_RDPM_UA_ACT_THERAPEUTIC_AREA ELSE LIST_COLLECT(\"ALL_PARENTS\",\"SAN_RDPM_UA_ACT_THERAPEUTIC_AREA <> \\\"\\\"\",\"SAN_RDPM_UA_ACT_THERAPEUTIC_AREA\") FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)