
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260081320271
 :NAME :SAN_RDPM_UA_B_PO_GNG_IS_NO_GO
 :COMMENT "Is No Go?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "WBS_TYPE.SAN_RDPM_UA_B_IS_GNG_PO AND MATCH_STRING(\"No Go\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)