
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260029467772
 :NAME :SAN_RDPM_UA_SITE_CSU_CONSO
 :COMMENT "CSU Site Consolidation"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
)