
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008034973
 :NAME :SAN_RDPM_UA_ACT_S_CALCULATED_STUDY_CODE
 :COMMENT "Internal Study Code (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN SAN_UA_ACT_STUDY_CODE ELSE WBS_ELEMENT.SAN_RDPM_UA_ACT_S_CALCULATED_STUDY_CODE FI"
 :IS-INDEXED T
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM| :|Continuum.eSTRA| :|Roadmap|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)