
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260024861571
 :NAME :SAN_RDPM_UA_INDICATION_STATUS_DETAILED
 :COMMENT "Indication Status Detailed"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_B_IS_AN_INDICATION THEN IF SAN_RDPM_UA_B_INDICATION_STATUS_STOPPED_OR_COMPLETED AND ?FINISHED THEN SAN_RDPM_UA_ACT_BPS_INDICATION_STATUS.DESC + \" inactive\" ELSE IF SAN_RDPM_UA_B_INDICATION_STATUS_STOPPED_OR_COMPLETED AND NOT ?FINISHED THEN SAN_RDPM_UA_ACT_BPS_INDICATION_STATUS.DESC + \" active\" ELSE SAN_RDPM_UA_ACT_BPS_INDICATION_STATUS.DESC FI FI ELSE STRING_VALUE(\"ACTIVITY\",SAN_RDPM_UA_ACT_S_INDICATION_ID,\"SAN_RDPM_UA_INDICATION_STATUS_DETAILED\") FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur| :|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)