
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260000025573
 :NAME :SAN_RDPM_UA_ACT_N_REPORT_MILE_ORDER
 :COMMENT "Reporting Milstone Order"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "WBS_TYPE.SAN_RDPM_UA_AT_REPORT_MILE_TYPE.SAN_RDPM_UA_RMT_N_ORDER"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)