
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260055878676
 :NAME :SAN_RDPM_TC_VALIDATION_DEADLINE_DATE
 :COMMENT "Validation Deadline Date for Timecard"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "PERIOD_START(OC.SAN_UA_RDPM_ACC_CAL_END_DATE,\"day\",-2)"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)