
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260000182470
 :NAME :SAN_RDPM_UA_RES_DEPARTMENT
 :COMMENT "Department"
 :DATASET 118081000141
 :FORMULA "RES.SAN_UA_RDPM_RES_DEP "
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)