
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260000019570
 :NAME :SAN_RDPM_UA_S_SITE_DESCRIPTION
 :COMMENT "Site description"
 :DATASET 118081000141
 :FORMULA "_RM_REVIEW_RA_LOCATION.SAN_RDPM_UA_S_SITE_DESCRIPTION"
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_ROLE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)