
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260047740871
 :NAME :SAN_RDPM_UA_MONITORING_SITE
 :COMMENT "Monitoring Site"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
)