
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260024990371
 :NAME :SAN_RDPM_UA_INDICATION_CODE_F
 :COMMENT "Indication Code (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_INDICATION_CODE <> \"\" THEN SAN_RDPM_UA_INDICATION_CODE ELSE WBS_ELEMENT.SAN_RDPM_UA_INDICATION_CODE_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)