
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260020001071
 :NAME :SAN_RDPM_UA_APPROACH_PHASE_PRIO_DATE
 :COMMENT "Approach Phase at Prio Date"
 :DATASET 118081000141
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_APPROACH_PHASE_PRIO_DATE
)