
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008045573
 :NAME :SAN_RDPM_UA_SP_S_SHORT_DESC
 :COMMENT "Short Description"
 :DATASET 118081000141
 :DOCUMENTATION "PRIME: Master Data \"Study purpose\" information."
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_STUDY_PURPOSE
 :PTYPES (:|Continuum|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)