
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260033384570
 :NAME :SAN_RDPM_UF_DEVELOPMENT_OBJECTIVE
 :COMMENT "Development objective (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_DEVELOPMENT_OBJECTIVE <> \"\" then SAN_RDPM_UA_DEVELOPMENT_OBJECTIVE ELSE WBS_ELEMENT.SAN_RDPM_UF_DEVELOPMENT_OBJECTIVE FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)