
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260000182770
 :NAME :SAN_RDPM_UA_S_PLATFORM
 :COMMENT "Platform"
 :DATASET 118081000141
 :FORMULA "RES.SAN_UA_RDPM_RES_PLAT"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)