
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260007844341
 :NAME :SAN_UA_RDPM_B_DISPLAYED_WBS_FORM_PHARMA
 :COMMENT "Displayed in WBS Form?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_ROLE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)