
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260008090973
 :NAME :SAN_UA_PC_PROJECT_CATEGORY
 :COMMENT "Project Category"
 :DATASET 118057330253
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_PROJECT_CODES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_CATEGORY
)