
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260000181270
 :NAME :SAN_RDPM_UA_S_PORTFOLIO
 :COMMENT "Portfolio"
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_UA_PM_PRJ_PORT"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)