
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260009678574
 :NAME :SAN_UA_RDPM_WBS_FORM_SKILL
 :COMMENT "Skill"
 :DATASET 118081000141
 :FORMULA "_RM_DA_S_DYN_SKILLS "
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_ROLE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)