
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260106827874
 :NAME :SAN_UA_RDPM_S_WBS_FORM_LEADER_ROLE
 :COMMENT "WBS Form - Role for leader update"
 :DATASET 118081000141
 :FORMULA "LIST_REMOVE_DUPLICATES(LIST_INTERSECT(OBS_ELEMENT.SAN_UA_RDPM_S_OBS_TYPE_ROLES,WBS_TYPE.SAN_UA_RDPM_S_ACT_TYPE_ROLES))"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)