
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260103758941
 :NAME :SAN_RDPM_UA_B_IS_MAIN_SKILL
 :COMMENT "Main skill?"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:RESOURCE-SKILL
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)