
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260108665674
 :NAME :SAN_RDPM_UA_OC_D_PRC_ED
 :COMMENT "PRC End Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF DATE_VALUE(\"PROJECT\",$CURRENT_PAGE_OBJECT_ID,\"ED\")<>-1 THEN DATE_VALUE(\"PROJECT\",$CURRENT_PAGE_OBJECT_ID,\"ED\") ELSE $TIME_WINDOW_END FI"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)