
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260106749775
 :NAME :SAN_RDPM_UA_UG_PL_ACCESS
 :COMMENT "Current user has Project Level access rights?"
 :DATASET 118081000141
 :FORMULA "USER_IN_GROUP($CURRENT_USER,OC.SAN_RDPM_CS_UG_PL_ACCESS)"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)