
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260103793241
 :NAME :SAN_UA_B_CF_PROD_DATA
 :COMMENT "Common file to export to have current production data"
 :DATASET 118081000141
 :FORMULA "NAME IN (\"SAN_CF_CONTINUUM_COMMON_DATA\")"
 :NCLASS GENERIC-IO:COMMON-DATASET
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)