
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260107216174
 :NAME :SAN_RDPM_UA_B_OBS_CMC
 :COMMENT "Pharma - CMC"
 :DATASET 118081000141
 :FORMULA "FROM(OC.SAN_RDPM_CS_OBS_CMC)"
 :NCLASS KERNEL-ORDO:OBS-NODE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)