
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260108665374
 :NAME :SAN_RDPM_UA_OC_D_PRC_SD
 :COMMENT "PRC Start Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF DATE_VALUE(\"PROJECT\",$CURRENT_PAGE_OBJECT_ID,\"OD\")<>-1 THEN DATE_VALUE(\"PROJECT\",$CURRENT_PAGE_OBJECT_ID,\"OD\") ELSE $TIME_WINDOW_START FI"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)