
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260103542182
 :NAME :SAN_UA_S_ANIMAL_SPECY
 :COMMENT "Animal (F)"
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"ALLOCATIONS\",\"RES.SAN_RDPM_UA_B_RES_SPECIES\",\"RES\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)