
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260105771182
 :NAME :SAN_UA_S_ACT_CALCULATED_SOURCING_STUDY
 :COMMENT "Sourcing Study (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN SAN_UA_S_ACT_SOURCING_STUDY ELSE WBS_ELEMENT.SAN_UA_S_ACT_CALCULATED_SOURCING_STUDY FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)