
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260103519282
 :NAME :SAN_UA_N_ANIMALS_NUMB
 :COMMENT "Number of Animals (F)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "ITER_NUMBER_SUM(\"ALLOCATIONS\",\"RES.SAN_RDPM_UA_B_RES_SPECIES\",\"QTY\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)