
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260107216674
 :NAME :SAN_RDPM_UA_B_OBS_PRECLIN_SAFETY
 :COMMENT "Pharma - Pre-Clinical Safety"
 :DATASET 118081000141
 :FORMULA "FROM(OC.SAN_RDPM_CS_OBS_PRECLIN_SAFETY)"
 :NCLASS KERNEL-ORDO:OBS-NODE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)