
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260106826174
 :NAME :SAN_UA_RDPM_S_OBS_TYPE_ROLES
 :COMMENT "WBS Form - Roles linked to OBS"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"USER_ATTRIBUTE_INVERSE_SAN_UA_RDPM_S_OBS.__USER_TABLE_SAN_RDPM_UR_WBS_FORM_MAP_LEADER\",\"TRUE\",\"SAN_UA_RDPM_S_ROLE\") "
 :NCLASS KERNEL-ORDO:OBS-NODE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)