
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260103476241
 :NAME :SAN_UA_B_CF_DPM_RDD_CONFIGURATION
 :COMMENT "Common file to export into Data Migration Config. DPM "
 :DATASET 118081000141
 :FORMULA "NAME IN (\"SAN_CF_RDPM_MIG_CONFIG_L2\", \"SAN_CF_RDPM_MIG_CONFIG_L1\")"
 :NCLASS GENERIC-IO:COMMON-DATASET
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)