
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260106826474
 :NAME :SAN_UA_RDPM_S_ACT_TYPE_ROLES
 :COMMENT "WBS Form - Roles linked to Activity Type"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"USER_ATTRIBUTE_INVERSE_SAN_UA_RDPM_S_ACT_TYPE.__USER_TABLE_SAN_RDPM_UR_WBS_FORM_MAP_LEADER\",\"TRUE\",\"SAN_UA_RDPM_S_ROLE\") "
 :NCLASS TEMP-TABLE::WBS_TYPE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)