
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260103476841
 :NAME :SAN_UA_B_CF_RDD_DATA
 :COMMENT "Common file to export into Data Migration Data DPM"
 :DATASET 118081000141
 :FORMULA "NAME IN (\"SAN_CF_RDPM_MIG_DATA\")"
 :NCLASS GENERIC-IO:COMMON-DATASET
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)