
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260105936882
 :NAME :SAN_UA_S_ACT_STUDY_DESC
 :COMMENT "Study Description (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN DESC ELSE WBS_ELEMENT.SAN_UA_S_ACT_STUDY_DESC FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)