
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260148691776
 :NAME :SAN_RDPM_UA_ACT_COMPLEXITY_FACTOR
 :COMMENT "Complexity Factor"
 :DATASET 118081000141
 :DEFAULT-VALUE 1.0d0
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)