
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260108629674
 :NAME :SAN_RDPM_UA_B_FLEX_REPORT_BOT_LABEL
 :COMMENT "Flexible Report - Bottom Label"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_B_FLEX_REPORT_START_DATE_AT_BOTTOM THEN 	PS  	ELSE 	IF SAN_RDPM_UA_B_FLEX_REPORT_END_DATE_AT_BOTTOM 	 THEN  		PRINT_END_DATE(PF,OC.DATE_FORMAT1) 	ELSE 		\"\" 	FI  FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)