
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 260107091974
 :NAME :SAN_UA_RDPM_S_WBS_FORM_LEADER_SITE
 :COMMENT "WBS Form - Leader Site"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "san_pjs_get_wbs_form_string_value_on_object(ID,SAN_UA_RDPM_S_WBS_FORM_LEADER_ROLE,\"USER_ATTRIBUTE_SAN_UA_S_LEADER_SITE\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)