
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262033941141
 :NAME :SAN_RDPM_US_COUNTRY_WEIGHT_CSU_REGION
 :COMMENT "Weight of CSU Region"
 :DATASET 118081000141
 :DEFAULT-VALUE 1.0d0
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_COUNTRY
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)