
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262005538676
 :NAME :SAN_RDPM_UA_ACT_DEFAULT_RTM_ALLOCATION
 :COMMENT "Default RTM allocation?"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY then (SAN_RDPM_UA_SOURCING_MODEL_DASTORE <> \"*Full Package*\" AND SAN_RDPM_UA_ACT_OBS_CALCULATED_BUDGET_OWNER = \"R&D\" AND NOT (LIST_LENGTH(SAN_RDPM_UA_S_LIST_REGIONS)=1 AND LIST_FIND(\"AP\",SAN_RDPM_UA_S_LIST_REGIONS)) AND (SAN_UA_S_ACT_CALCULATED_STUDY_PHASE IN (\"IIb\",\"III\") OR (SAN_UA_S_ACT_CALCULATED_STUDY_PHASE = \"IIa\" AND SAN_RDPM_UA_ACT_N_COUNT_AP+SAN_RDPM_UA_ACT_N_COUNT_EUR+SAN_RDPM_UA_ACT_N_COUNT_NAM+SAN_RDPM_UA_ACT_N_COUNT_LAM > 8))) OR SAN_RDPM_UA_ACT_MANUAL_RTM_ACTIV FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)