
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262034357282
 :NAME :SAN_UA_RDPM_S_RESOURCE_COUNTRY
 :COMMENT "Country"
 :DATASET 118081000141
 :FORMULA "_RM_REVIEW_RA_LOCATION.SAN_RDPM_UA_COUNTRY"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)