
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262044406970
 :NAME :SAN_UA_B_ACT_IS_LEAD_INDICATION
 :COMMENT "Next indication? "
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_INDICATION_NUMBER.SAN_RDPM_UA_B_INDIC_NUMB_LEAD"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)