
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262039678782
 :NAME :SAN_RDPM_UA_S_SITES_PH
 :COMMENT "Site(s) of Res. allocations"
 :DATASET 118081000141
 :FORMULA "LIST_REMOVE(\"\",LIST_REMOVE_DUPLICATES(LIST_COLLECT(\"ALLOCATIONS\",\"\",\"_RM_REVIEW_RA_LOCATION + \\\",\\\"\")))"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)