
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262021189074
 :NAME :SAN_RDPM_UA_B_COHORT_ACT
 :COMMENT "Cohort activity"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"WBS_TYPE\",OC.SAN_RDPM_CS_COHORT_AT) OR WBS_ELEMENT.SAN_RDPM_UA_B_COHORT_ACT"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)