
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262018874076
 :NAME :SAN_RDPM_UA_B_PROJECT_TEAM_USER_IS_ACTIVE
 :COMMENT "User inactive?"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_USER.INACTIVE"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)