
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262039763082
 :NAME :SAN_RDPM_UA_S_PROJECT_CODE_TIMECARD
 :COMMENT "Project code for Timecard"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_S_PROJECT_CODE_TIMECARD"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)