
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262033956472
 :NAME :SAN_RDPM_UA_CPT_OBS
 :COMMENT "Responsibility - OBS"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_DEF_COST_PAT
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE KERNEL-ORDO:OBS-NODE
)