
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262069675870
 :NAME :SAN_RDPM_UF_B_IS_RND_ACTIVITY_F
 :COMMENT "Is R&D Activity (F)"
 :DATASET 118081000141
 :FORMULA "boolean_value(\"RESPONSIBILITY\",SAN_RDPM_UA_ACT_OBS_CALCULATED_BUDGET_OWNER,\"SAN_RDPM_UF_B_IS_RND_ACTIVITY_OBS\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)