
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262034120072
 :NAME :SAN_RDPM_UA_PRJ_RND_IND
 :COMMENT "R&D Project Pharma Indication"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"PROJECT_TYPE\",oc.SAN_RDPM_CS_PRJ_INDICATION)"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)