
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262039558782
 :NAME :SAN_RDPM_UA_S_LIST_CLINICAL_INDICATION
 :COMMENT "List Clinical indication(s)"
 :DATASET 118081000141
 :FORMULA "LIST_REMOVE(\"\",LIST_REMOVE_DUPLICATES(LIST_COLLECT(\"ACTIVITIES\",\"SAN_RDPM_UA_B_IS_AN_INDICATION\",\"SAN_RDPM_UA_CLIN_INDICATION_F\")))"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)