
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262077759373
 :NAME :SAN_RDPM_UA_ACT_S_INDICATION_ID
 :COMMENT "Indication Identifier"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_B_IS_AN_INDICATION THEN ID ELSE WBS_ELEMENT.SAN_RDPM_UA_ACT_S_INDICATION_ID FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)