
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262039654782
 :NAME :SAN_UA_B_IS_THERE_ACT_CSO_CALCULATED
 :COMMENT "? is CSO activity calculated"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_B_IS_THERE_ACT_CSO then SAN_UA_B_IS_THERE_ACT_CSO else WBS_ELEMENT.SAN_UA_B_IS_THERE_ACT_CSO_CALCULATED FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)