
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262037148974
 :NAME :SAN_RDPM_UA_ACT_SOURCING
 :COMMENT "Sourcing"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::_INF_PT_CBS2
)