
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262070047274
 :NAME :SAN_RDPM_UA_S_RES_TEAM
 :COMMENT "Team"
 :DATASET 118081000141
 :FORMULA "IF _INF_AA_B_GENERIC_RES=FALSE THEN 	IF CHILD_OF.SAN_RDPM_UA_B_IS_A_TEAM THEN CHILD_OF ELSE CHILD_OF.SAN_RDPM_UA_S_RES_TEAM FI ELSE 	\"\" FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)