
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 262044407470
 :NAME :SAN_UA_B_PRJ_IS_LEAD_INDICATION
 :COMMENT "Lead indication (project)? "
 :DATASET 118081000141
 :FORMULA "BOOLEAN_VALUE(\"WBS_ELEMENT\",PROJECT_ROOT_ACTIVITY(ID),\"SAN_UA_B_ACT_IS_LEAD_INDICATION\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)