
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282700366871
 :NAME :SAN_RDPM_UA_INDICATION_ONB
 :COMMENT "ONB of the indication if below one"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "NUMBER_VALUE(\"ACTIVITY\",SAN_RDPM_UA_ACT_S_INDICATION_ID,\"ONB\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)