
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282703583370
 :NAME :SAN_RDPM_UF_S_PROJECT_CODE
 :COMMENT "Project code"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"PROJECT\",PROJECT.SAN_RDPM_UA_PRJ_S_ROOT_PROJECT,\"SAN_UA_RWE_PROJECT_CODE_PRIME\")"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)