
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282702088282
 :NAME :SAN_RDPM_UA_S_PLANNED_SPE_LAUNCH
 :COMMENT "Planned SPE Launch date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "ITER_DATE_MAX(\"ALL_CHILDREN\",\"BELONGS(\\\"WBS_TYPE\\\",\\\"Global AED Launch,SPE Launch\\\")\",\"PS\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)