
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282732463573
 :NAME :SAN_RDPM_UA_ACT_N_RES_VAR_TRESHOLD
 :COMMENT "Resource Variance Threshold (FTE)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)