
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282717328674
 :NAME :SAN_RDPM_UA_B_VACCINES_LOADED_BASELINE
 :COMMENT "Vaccines loaded baseline?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_L1_PT_REF_ADMIN
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)