
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282705352672
 :NAME :SAN_RDPM_UA_DELAY_ACTORS
 :COMMENT "Delay actor"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :DELAY_ACTOR
)