
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282701871382
 :NAME :SAN_RDPM_UA_S_PROJECT_STATUS_DETAILED
 :COMMENT "Project Status detailed"
 :DATASET 118081000141
 :FORMULA "IF LEVEL=1 THEN PROJECT.SAN_RDPM_UA_PRJ_PRJ_STATUS ELSE WBS_ELEMENT.SAN_RDPM_UA_S_PROJECT_STATUS_DETAILED FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)