
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282701845582
 :NAME :SAN_RDPM_UA_ACT_B_NCA_ANALYSIS
 :COMMENT "NCA analysis? test"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN SAN_RDPM_UA_B_NCA_ANALYSIS ELSE WBS_ELEMENT.SAN_RDPM_UA_ACT_B_NCA_ANALYSIS FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)