
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282718691976
 :NAME :SAN_RDPM_UA_PROVIDER_CATEGORY
 :COMMENT "Category"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_INF_PT_CBS3
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)