
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282705637872
 :NAME :SAN_RDPM_UA_ACT_PARENT_ONB
 :COMMENT "Parent ONB"
 :DATASET 118081000141
 :FORMULA "wbs_element.onb"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)