
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282702032382
 :NAME :SAN_RDPM_UA_NEXT_ABSENCE_START_DATE
 :COMMENT "Next absence start date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "ITER_DATE_MAX(\"Availabilities\",\"TYPE=\\\"ABSENCE\\\" and FD>$Date_of_the_day and SD>$Date_of_the_day\",\"SD\") "
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)