
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282706385541
 :NAME :SAN_RDPM_UF_OBS_CMC
 :COMMENT "CMC?"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"RESPONSIBILITY\",OC.SAN_RDPM_CS_OBS_CMC)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)