
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282711586076
 :NAME :SAN_RDPM_B_RES_MANAGED_IN_TC
 :COMMENT "Managed resource in Timecard?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF NOT OC._INF_NF_B_SUPERUSER_MODE THEN  USER_IN_GROUP($CURRENT_USER,LIST_MERGE(MANAGERS,OC.SAN_RDPM_CS_TC_SEE_ALL_RES_GROUPS)) ELSE TRUE FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)