
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282701842882
 :NAME :SAN_RDPM_UA_N_DURATION_MTHS
 :COMMENT "Duration Mths"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "DU/'22d'"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)