
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282701968582
 :NAME :SAN_RDPM_UA_WBS_TYPE_SUBMISSION
 :COMMENT "Submission activity type"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN LIST_REMOVE(\"\",LIST_REMOVE_DUPLICATES(LIST_COLLECT(\"ALL_CHILDREN\",\"\",\"SAN_RDPM_UA_TYPE_SUBMISSION\"))) ELSE WBS_ELEMENT.SAN_RDPM_UA_WBS_TYPE_SUBMISSION FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)