
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282705345172
 :NAME :SAN_RDPM_S_UNIT
 :COMMENT "Unit"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_TARGET_POP
 :PTYPES (:|Continuum.RDPM.Pasteur.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :UNIT
)