
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282706436141
 :NAME :SAN_RDPM_UF_ACT_PHARMA_GANTT_COLOR
 :COMMENT "RDPM Gantt Color (Text)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF ?FINISHED THEN \"OBJ33\" ELSE IF (?TASK and CF<=0) THEN \"OBJ1\" ELSE IF SAN_RDPM_UA_ACT_SOURCING=\"CO-DEV\" THEN \"BBLO\" ELSE OBS_ELEMENT._INF_DA_FINAL_COLOR FI FI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)