
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282700418571
 :NAME :SAN_RDPM_UA_LVL1_ACTIVITY_ONB
 :COMMENT "ONB of the lvl1 activity"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "number_value(\"ACTIVITY\",project_root_activity(SAN_RDPM_UA_S_ACT_PROJECT_ID_F),\"ONB\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)