
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282706389641
 :NAME :SAN_RDPM_UA_B_OBS_RTMED
 :COMMENT "Pharma - RTMED"
 :DATASET 118081000141
 :FORMULA "FROM(OC.SAN_RDPM_CS_OBS_RTMED)"
 :NCLASS KERNEL-ORDO:OBS-NODE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)