
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282703582370
 :NAME :SAN_RDPM_UF_S_INDICATION_CODE
 :COMMENT "Indication"
 :DATASET 118081000141
 :FORMULA "IF BOOLEAN_VALUE(\"ACTIVITY\",project_root_activity(PROJECT),\"SAN_RDPM_UA_B_IS_AN_INDICATION\") THEN string_value(\"ACTIVITY\",project_root_activity(PROJECT),\"SAN_RDPM_UA_S_UNIQUE_IND_CODE_F\") FI"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)