
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282701966882
 :NAME :SAN_RDPM_UA_TYPE_SUBMISSION
 :COMMENT "Submission type"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF (BELONGS(\"WBS_TYPE\", \"US submission\") or BELONGS(\"WBS_TYPE\", \"EU submission\")) AND PS=SAN_RDPM_D_PS_LAST_SUBMISSION THEN WBS_TYPE FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)