
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282718697676
 :NAME :SAN_RDPM_UA_B_ACT_EXCLUDE_TT
 :COMMENT "Activity type to exclude to TT"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "belongs(\"WBS_TYPE\",OC.SAN_RDPM_CS_AT_EXCLUDE_TT) "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)