
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282702032082
 :NAME :SAN_RDPM_UA_ONGOING_ABSENCE_END_DATE
 :COMMENT "Ongoing absence end date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "ITER_DATE_MAX(\"Availabilities\",\"TYPE=\\\"ABSENCE\\\" and FD>=$Date_of_the_day and SD<=$Date_of_the_day\",\"FD-'1d'\") "
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)