
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282702107482
 :NAME :SAN_RDPM_UA_B_IS_CSO_STUDY
 :COMMENT "is a CSO/EGDS study?"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY and SAN_UA_B_IS_THERE_ACT_CSO_CALCULATED THEN YES ELSE FALSE FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)