
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282706386441
 :NAME :SAN_RDPM_UF_OBS_CSO
 :COMMENT "CSO/EGDS?"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"RESPONSIBILITY\",OC.SAN_RDPM_CS_OBS_CSO)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)