
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282717328974
 :NAME :SAN_RDPM_UA_B_PHARMA_LOADED_BASELINE
 :COMMENT "Pharma Loaded Baseline?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_L1_PT_REF_ADMIN
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)