
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282705480872
 :NAME :SAN_RDPM_UA_ACT_FOLOWUP
 :COMMENT "CS Follow-up?"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"WBS_TYPE\",OC.SAN_RDPM_CS_AT_FOLLUP)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)