
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282705342072
 :NAME :SAN_RDPM_UA_S_FUNDING_ZONE
 :COMMENT "Funding Zone"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :FIND_ZONE
)