
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282702002382
 :NAME :SAN_RDPM_HAS_A_FUTURE_ABSENCE
 :COMMENT "Has an absence (in progress / planned) ?"
 :DATASET 118081000141
 :FORMULA "ITER_BOOLEAN_THERE_IS_ONE(\"Availabilities\",\"TYPE=\\\"Absence\\\" AND FD>=$DATE_OF_THE_DAY\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)