
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282702105582
 :NAME :SAN_RDPM_UA_S_RES_PE
 :COMMENT "List of R&D Structures"
 :DATASET 118081000141
 :FORMULA "LIST_REMOVE_DUPLICATES(LIST_COLLECT(\"EXPENDITURES\",\"COST_ACCOUNT IN(\\\"Clinical Costs\\\",\\\"CLI_VAR\\\")\",\"RES\"))"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)