
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282701870682
 :NAME :SAN_RDPM_UA_S_THERAPEUTIC_AREA_DESC
 :COMMENT "ATC Code desc (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_ACT_THERAPEUTIC_AREA<>\"\" THEN SAN_RDPM_UA_ACT_THERAPEUTIC_AREA.DESC ELSE WBS_ELEMENT.SAN_RDPM_UA_S_THERAPEUTIC_AREA_DESC FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)