
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282705933171
 :NAME :SAN_RDPM_UA_POST_APPROVAL_COMMITMENT
 :COMMENT "Post Approval Commitment"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::...__USER_TABLE_SAN_RWE_UT_REGULATORY_IMPACT
)