
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282732758173
 :NAME :SAN_RDPM_UA_N_SR_F
 :COMMENT "Success Rate (F)"
 :DATASET 118081000141
 :FORMULA "IF WBS_TYPE._WT_AA_B_CONSO_SF_FM THEN SAN_RDPM_UA_N_SR ELSE WBS_ELEMENT.SAN_RDPM_UA_N_SR_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)