
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282702123782
 :NAME :SAN_RDPM_UA_B_IS_THERE_CSO_COST_STUDY
 :COMMENT "Is there a CSO/EGDS Cost? (F)"
 :DATASET 118081000141
 :FORMULA "ITER_BOOLEAN_THERE_IS_ONE(\"CHILDREN\",\"SAN_RDPM_UA_B_IS_THERE_CSO_COST\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)