
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282700366271
 :NAME :SAN_RDPM_UA_STUDY_ONB
 :COMMENT "ONB of the study if below one"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "number_value(\"ACTIVITY\",SAN_UA_RDPM_ACT_S_STUDY_ID,\"ONB\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)