
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282811879641
 :NAME :SAN_RDPM_UA_ACT_PROJECT_PHASE
 :COMMENT "Project Phase"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"PROJECT\",PROJECT.SAN_RDPM_UA_PRJ_S_ROOT_PROJECT,\"SAN_RDPM_UA_PROJECT_PHASE\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)