
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282811882141
 :NAME :SAN_RDPM_UA_DU_DELTA_YEARLY_CURRENT
 :COMMENT "Delta Yearly - Current month (Duration)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0
 :FORMULA "IF SAN_RDPM_UA_D_PHARMA_YEARLY_DATE<>-1 THEN DIFF_DATE(SAN_RDPM_UA_D_PHARMA_YEARLY_DATE,PS,CAL) FI "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME:DURATION
)