
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282806047872
 :NAME :SAN_RDPM_UA_SITE_CSU_REG_F
 :COMMENT "CSU Region (F)"
 :DATASET 118081000141
 :FORMULA "if SAN_RDPM_UA_COUNTRY.SAN_RDPM_UA_CTRY_CSU_REGION <>\"\" then  SAN_RDPM_UA_COUNTRY.SAN_RDPM_UA_CTRY_CSU_REGION else SAN_RDPM_UA_SITE_CSU_REG fi"
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)