
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282811883141
 :NAME :SAN_RDPM_UA_S_DELTA_YEARLY_CURRENT_MONTH
 :COMMENT "Delta Yearly - Current month"
 :DATASET 118081000141
 :FORMULA "PRINT_DURATION(SAN_RDPM_UA_DU_DELTA_YEARLY_CURRENT,\"MD\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)