
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282810674182
 :NAME :SAN_RDPM_UA_B_IS_THERE_CMC_ACT_IN_BB
 :COMMENT "is there a CMC activity in the BB?"
 :DATASET 118081000141
 :FORMULA "ITER_BOOLEAN_THERE_IS_ONE(\"CHILDREN\",\"ITER_BOOLEAN_THERE_IS_ONE(\\\"CHILDREN\\\",\\\"SAN_UA_B_IS_ACT_CMC\\\")\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)