
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282806048972
 :NAME :SAN_RDPM_UA_ACT_CTR_IDENTIF
 :COMMENT "RTM Countries Identification"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::..._RM_REVIEW_PT_LOCATIONS
)