
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808366082
 :NAME :SAN_RDPM_UA_S_STUDY_GROUP_F
 :COMMENT "Study Group F"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "SAN_DA_ACT_STUDY_GROUP"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)