
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282806046072
 :NAME :SAN_RDPM_UA_SITE_CSU_REG
 :COMMENT "CSU Region"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CSU_REGION
)