
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808365582
 :NAME :SAN_RDPM_UA_S_OBS_INDICATION_F
 :COMMENT "OBS of Indication (F)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_B_IS_AN_INDICATION THEN OBS_ELEMENT ELSE WBS_ELEMENT.SAN_RDPM_UA_S_OBS_INDICATION_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)