
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808727870
 :NAME :SAN_RDPM_UF_S_INDICATION_ADMINISTRATION_ROUTE
 :COMMENT "Administration Route (Indication)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"ACTIVITY\",SAN_RDPM_UF_S_INDICATION_ACTIVITY_ID,\"SAN_RDPM_UA_ACT_ADM_ROUTE_F\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)