
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808730570
 :NAME :SAN_RDPM_UF_S_INDICATION_STATUS_DETAILED
 :COMMENT "Indication Status detailed (Indication)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"ACTIVITY\",SAN_RDPM_UF_S_INDICATION_ACTIVITY_ID,\"SAN_RDPM_UA_INDICATION_STATUS_DETAILED\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|
          :|Continuum.RDPM.Pasteur.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)