
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808728570
 :NAME :SAN_RDPM_UF_S_CLINICAL_INDICATION
 :COMMENT "Clinical Indication (Indication)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"ACTIVITY\",SAN_RDPM_UF_S_INDICATION_ACTIVITY_ID,\"SAN_RDPM_UA_CLIN_INDICATION_F\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)