
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282806658971
 :NAME :SAN_RDPM_UA_END_OF_PHASE_ONE
 :COMMENT "End of Phase 1"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF LIST_LENGTH(DURATIONS) > 1 THEN ADD_DURATION(PS,DURATION(NTH(DURATIONS,0,\",\")),CAL) ELSE PF FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)