
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808211382
 :NAME :SAN_RDPM_UA_S_PRG_ROLE
 :COMMENT "PRG Role"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_ACT_B_PATIENT_STUDY_F THEN \"PRG\" ELSE \"PRG-ECB\" FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)