
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282807846782
 :NAME :SAN_RDPM_UA_ID_RES_LINK_RESP
 :COMMENT "ID of RES linked to RESP"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "RESPONSIBILITY.SAN_RDPM_UA_S_ID_RES_LINK_OBS"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)