
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282811728973
 :NAME :SAN_RDPM_UA_CYCLE_F
 :COMMENT "Cycle (F)"
 :DATASET 118081000141
 :FORMULA "if SAN_UA_RDPM_ACT_S_STUDY_ID<>\"\" then STRING_VALUE(\"Activity\",SAN_UA_RDPM_ACT_S_STUDY_ID,\"SAN_RDPM_UA_CYCLE\") else (if SAN_RDPM_UA_CYCLE<>\"\" then SAN_RDPM_UA_CYCLE fi)   fi"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)