
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808729670
 :NAME :SAN_RDPM_UF_S_INDICATION_FORMULATION
 :COMMENT "Formulation (Indication)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"ACTIVITY\",SAN_RDPM_UF_S_INDICATION_ACTIVITY_ID,\"SAN_RDPM_UR_ACT_FORMULATION_CALC\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)