
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808727370
 :NAME :SAN_RDPM_UF_S_INDICATION_ACTIVITY_ID
 :COMMENT "Indication activity identifier"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "if SAN_RDPM_UA_PRJ_RND_IND OR SAN_RDPM_UA_PRJ_RND_IND_VAC then PROJECT_ROOT_ACTIVITY(ID) FI"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|
          :|Continuum.RDPM.Pasteur.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)