
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282807843982
 :NAME :SAN_RDPM_UA_S_ID_RES_LINK_OBS
 :COMMENT "ID of Resource linked to OBS"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "LIST_REMOVE_DUPLICATES(LIST_COLLECT(\"OBS-CHILDREN\",\"CLASS=\\\"RESOURCE\\\"\",\"SAN_UA_RDPM_RES_FUNCTION\"))"
 :NCLASS KERNEL-ORDO:OBS-NODE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)