
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808046582
 :NAME :SAN_RDPM_UA_D_LPI_LSI_END_TASK
 :COMMENT "Duration From LPI/LSI to end of task"
 :DATASET 118081000141
 :DEFAULT-VALUE 0
 :FORMULA "DIFF_DATE(SPJ.SAN_RDPM_UA_PLANNED_LPI_LSI,PF,CAL)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME:DURATION
)