
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282806250772
 :NAME :SAN_RDPM_UA_ACT_PLANN_SITE
 :COMMENT "Planned sites"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "NUMBER_VALUE(\"ACTIVITY\",SAN_UA_RDPM_ACT_S_STUDY_ID,\"SAN_RDPM_CF_SITES\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)