
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808730270
 :NAME :SAN_RDPM_UF_S_INDICATION_PRIORITY_VALUE
 :COMMENT "Project Priority (F)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"PROJECT\",SAN_RDPM_UA_PRJ_S_ROOT_PROJECT,\"SAN_RDPM_UA_PRJ_S_PRIORITY\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|
          :|Continuum.RDPM.Pasteur.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)