
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282806647682
 :NAME :SAN_RDPM_UA_N_MONTH_DU_FPI_TO_LPLV
 :COMMENT "Duration FPI to LPLV (month)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN DIFF_DATE(SAN_RDPM_UA_PLANNED_FPI_FSI,SAN_RDPM_UA_PLANNED_LPLV_LSLV,CAL)/'22d' ELSE WBS_ELEMENT.SAN_RDPM_UA_N_MONTH_DU_FPI_TO_LPLV FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)