
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808723870
 :NAME :SAN_RDPM_UF_B_IS_RND_ACTIVITY_OBS
 :COMMENT "Is R&D OBS? (F)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "FROM (OC.SAN_RDPM_CS_OBS_RND_ACTIVITY)"
 :NCLASS KERNEL-ORDO:OBS-NODE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)