
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282810741282
 :NAME :SAN_RDPM_UA_N_SUBJECT_FROM_STUDY
 :COMMENT "Planned Subject (F)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN SAN_RDPM_CF_SUBJECTS ELSE WBS_ELEMENT.SAN_RDPM_UA_N_SUBJECT_FROM_STUDY FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)