
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282810027282
 :NAME :SAN_RDPM_UA_S_SETUP_DU_MONTH
 :COMMENT "SET-UP Duration in month"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN LIST_COLLECT(\"ALL_CHILDREN\",\"?TASK and BELONGS(\\\"WBS_TYPE\\\",OC.SAN_RDPM_CS_AT_SETUP)\",\"DU/'22d'\") ELSE WBS_ELEMENT.SAN_RDPM_UA_S_SETUP_DU_MONTH FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)