
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808742970
 :NAME :SAN_RDPM_UA_B_LINK_EXPORTED_TO_SHINE
 :COMMENT "LINK exported to SHINE"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "PA.SAN_RDPM_UA_B_ACT_EXPORTED_TO_SHINE AND SUCC_ACTIVITY.SAN_RDPM_UA_B_ACT_EXPORTED_TO_SHINE"
 :NCLASS KERNEL-ORDO:CONSTRAINT
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)