
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282808149182
 :NAME :SAN_RDPM_UA_D_SD_ID_CARD
 :COMMENT "PS of Study ID Card approved"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN ITER_DATE_MAX(\"ALL_CHILDREN\",\"?TASK and BELONGS(\\\"WBS_TYPE\\\",\\\"Study ID card approved\\\")\",\"PS\") ELSE '-1' FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)