
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282811881641
 :NAME :SAN_RDPM_UA_DU_DELTA_BASELINE_1_2
 :COMMENT "Delta Baseline 1 vs Baseline 2 (Duration)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0
 :FORMULA "IF OC.DATE2<>\"\" AND SAN_RDPM_UA_D_BL1_FD<>'-1' AND SAN_RDPM_UA_D_BL2_FD<>'-1' THEN  	 DIFF_DATE(SAN_RDPM_UA_D_BL1_FD,SAN_RDPM_UA_D_BL2_FD,CAL) ELSE '0d'  FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME:DURATION
)