
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 282807947482
 :NAME :SAN_RDPM_UA_S_ID_SETUP
 :COMMENT "SET-UP ID (F)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN LIST_COLLECT(\"ALL_CHILDREN\",\"?TASK and BELONGS(\\\"WBS_TYPE\\\",OC.SAN_RDPM_CS_AT_SETUP)\",\"ID\") ELSE WBS_ELEMENT.SAN_RDPM_UA_S_ID_SETUP FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)