
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283026995674
 :NAME :SAN_UA_RDPM_B_AUTO_SYNC_LINK_BB
 :COMMENT "Create external synchro links within Building Block?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::WBS_TYPE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)