
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283042470769
 :NAME :SAN_RDPM_UF_D_LAST_REF_FD
 :COMMENT "Last monthly baseline finish date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "DATE_VALUE(\"ACTIVITY\",ID,\"FD_\"+OC.SAN_RDPM_CS_LAST_MONTHLY_PHARMA) "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)