
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283039635570
 :NAME :SAN_RDPM_UF_INDICATION_NUMBER
 :COMMENT "Indication number (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_B_IS_AN_INDICATION THEN SAN_RDPM_UA_INDICATION_NUMBER ELSE WBS_ELEMENT.SAN_RDPM_UF_INDICATION_NUMBER FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)