
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283039620574
 :NAME :SAN_RDPM_UA_B_WPM_ACT_MODULE_FILTER
 :COMMENT "DataOwner Worpackage Filter"
 :DATASET 118081000141
 :FORMULA "IF PROJECT.SAN_RD_IS_RND_PROJECT THEN SAN_UA_RDPM_B_IS_A_STUDY ELSE ID=PROJECT FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)