
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283042489869
 :NAME :SAN_RDPM_UF_B_WB_NEWLY_CRITIC_PATH
 :COMMENT "Filter for workbox Newly on critical path"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_B_RND_PHARMA_PROJECT AND SAN_RDPM_UA_ACT_B_OPL  AND SAN_RDPM_UF_B_CRITIC_PATH_REF"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)