
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283141190982
 :NAME :SAN_RDPM_UA_D_CSR_APPROVED_PS
 :COMMENT "CSR Approved PS"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "DATE(\"SAN_RDPM_UA_D_PS_CSR_APPROVED\",\"DD-MMM-YY\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)