
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283108992982
 :NAME :SAN_RDPM_UA_S_DBL_SPEC_AND_TOOL
 :COMMENT "DBL Specificity and tool"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN LIST_COLLECT(\"ALL_CHILDREN\",\"?TASK and BELONGS(\\\"WBS_TYPE\\\",\\\"DBL\\\")\",\"SAN_RDPM_UA_SPECIFICITY_AND_TOOLS\") ELSE WBS_ELEMENT.SAN_RDPM_UA_S_DBL_SPEC_AND_TOOL FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)