
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283128082771
 :NAME :SAN_RDPM_UA_D_AUTOPROGRESS_DATE
 :COMMENT "Autoprogress date"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "MIN_DATE(PROJECT.TIME_NOW,ADD_DURATION(PF,'-1d',CAL))"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)