
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283110261974
 :NAME :SAN_RDPM_UA_B_IS_SOURCING_CONTROLLER
 :COMMENT "Is Finance Controller?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "USER_IN_GROUP($CURRENT_USER,SAN_RDPM_RO_SOURCING_CONTROLLER)"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)