
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283108993482
 :NAME :SAN_RDPM_UA_S_ECRF_DBL_SPEC_AND_TOOL
 :COMMENT "eCRF/DBL Specificity and Tool"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_S_ECRF_SPEC_AND_TOOL<>\"\" THEN SAN_RDPM_UA_S_ECRF_SPEC_AND_TOOL ELSE SAN_RDPM_UA_S_DBL_SPEC_AND_TOOL FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)