
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283144362082
 :NAME :SAN_RDPM_UA_N_AT_COUNT
 :COMMENT "Number of AT coded in active Projects"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "LIST_LENGTH(LIST_COLLECT(\"r.WBS_TYPE.WORK-STRUCTURE\",\"PROJECT.STATE=\\\"Active\\\"\",\"ONB\"))"
 :NCLASS TEMP-TABLE::WBS_TYPE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)