
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283130861941
 :NAME :SAN_UA_S_SUBJECT_NON_PROD
 :COMMENT "Email Subject for Non Prod"
 :DATASET 118057330253
 :FORMULA "if Not SAN_UA_B_CHC_PROD_DB then \"[\"+$Database_name+\"]\" fi"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.CHC.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)