
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283109220982
 :NAME :SAN_RDPM_UA_NB_RESUPPLY
 :COMMENT "Nb of Re-supply tasks"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN ITER_NUMBER_SUM(\"ALL_CHILDREN\",\"?TASK and BELONGS(\\\"WBS_TYPE\\\",OC.SAN_RDPM_CS_AT_RESUPPLY)\",\"1\") else WBS_ELEMENT.SAN_RDPM_UA_NB_RESUPPLY FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)