
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283126419982
 :NAME :SAN_RDPM_UA_S_IPRECONCILIATION
 :COMMENT "IP Reconciliation Duration in month"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN LIST_COLLECT(\"ALL_CHILDREN\",\"BELONGS(\\\"WBS_TYPE\\\",OC.SAN_RDPM_CS_AT_IP_RECONCILIATION)\",\"DU/'22d'\") ELSE WBS_ELEMENT.SAN_RDPM_UA_S_IPRECONCILIATION FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)