
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283135374974
 :NAME :SAN_UA_ACT_STUDY_PURPOSE
 :COMMENT "Study Purpose"
 :DATASET 118057330253
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM| :|Continuum.eSTRA|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RWE_UT_MEDICAL_IMPACT
)