
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283111192371
 :NAME :SAN_RDPM_UA_B_FROM_ACTIVE_PROJECT
 :COMMENT "Activity's project is active?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "PROJECT._INF_NF_S_PROJECT_STATE = \"ACTIVE\""
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)