
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283127265282
 :NAME :SAN_RDPM_UA_D_PS_SCREENING
 :COMMENT "PS Screening"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN ITER_DATE_MAX(\"ALL_CHILDREN\",\"?TASK and BELONGS(\\\"WBS_TYPE\\\",OC.SAN_RDPM_CS_AT_CLINICAL_MILESTONE_3200)\",\"PS\") ELSE WBS_ELEMENT.SAN_RDPM_UA_D_PS_SCREENING FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)