
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283120429370
 :NAME :SAN_RDPM_S_ACTIVITY_AF_SHINE
 :COMMENT "ACTIVITY ACTUAL FINISH EXPORT TO SHINE"
 :DATASET 118081000141
 :FORMULA "PRINT_DATE(AF,\"YY/MM/DD\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)