
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283135792282
 :NAME :SAN_RDPM_UA_ACT_NB_COUNTRIES
 :COMMENT "Number of Countries"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY then LIST_LENGTH(SAN_RDPM_UA_S_LIST_COUNTRIES) else 0 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)