
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283126351382
 :NAME :SAN_RDPM_UA_S_ID_CS_FEASIBILITY
 :COMMENT "CS feasibility ID"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN LIST_COLLECT(\"ALL_CHILDREN\",\"?TASK and BELONGS(\\\"WBS_TYPE\\\",OC.SAN_RDPM_CS_AT_CS_FEASIBILITY)\",\"ID\") ELSE WBS_ELEMENT.SAN_RDPM_UA_S_ID_CS_FEASIBILITY FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)