
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283122550969
 :NAME :SAN_UF_S_MAIN_PATH
 :COMMENT "Main path for Import Export depending on env"
 :DATASET 118057330253
 :FORMULA "IF ($DATABASE_NAME=\"DATABASE_PROD\") THEN OC.SAN_CS_MAIN_PATH_PROD ELSE IF ($DATABASE_NAME=\"DATABASE_PREPROD\") THEN OC.SAN_CS_MAIN_PATH_PREPROD ELSE OC.SAN_CS_MAIN_PATH_INT FI FI"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)