
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283115401774
 :NAME :SAN_UA_RDPM_ACT_S_BUILD_BLOCK_NAME
 :COMMENT "Building Block Name"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"ACTIVITY\",SAN_UA_RDPM_ACT_S_BUILD_BLOCK_ID,\"NAME\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)