
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 283110264274
 :NAME :SAN_RDPM_UA_S_MESSAGE_REQUESTOR
 :COMMENT "Message for requestor"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"__USER_TABLE_SAN_RDPM_UT_SOURCING_REQUEST_NOTIFICATION\",\"Requestor_\"+SAN_RDPM_UA_S_SOURCING_MESSAGE_ID,\"SAN_RDPM_UA_S_NOTIFICATION\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)