
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 292398608470
 :NAME :SAN_RDPM_UA_ACT_COUNT_ACTM_DESC
 :COMMENT "Country description (RA)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"__USER_TABLE_SAN_RWE_UT_COUNTRY\",SAN_RDPM_UA_ACT_COUNT_ACTM,\"DESC\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)