
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 292398623570
 :NAME :SAN_RDPM_PH_CSU_CTR_CONS_DESC
 :COMMENT "CSU Country Consolidation description"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"__USER_TABLE_SAN_RWE_UT_COUNTRY\",SAN_RDPM_PH_CSU_CTR_CONS,\"DESC\")"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)