
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 292398611770
 :NAME :SAN_UA_RDPM_S_RESOURCE_COUNTRY_DESC
 :COMMENT "Country description"
 :DATASET 118081000141
 :FORMULA "_RM_REVIEW_RA_LOCATION.SAN_RDPM_UA_COUNTRY.DESC"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)