
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296659195082
 :NAME :SAN_RDPM_UA_S_OBS_L4
 :COMMENT "OBS Level 4"
 :DATASET 118081000141
 :FORMULA "IF LEVEL=4 THEN DESC ELSE IF LEVEL>4 THEN OBS_ELEMENT.SAN_RDPM_UA_S_OBS_L4 FI FI"
 :NCLASS KERNEL-ORDO:OBS-NODE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)