
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296659194582
 :NAME :SAN_RDPM_UA_S_OBS_L2
 :COMMENT "OBS Level 2"
 :DATASET 118081000141
 :FORMULA "IF LEVEL=2 THEN DESC  ELSE  IF LEVEL>2 THEN OBS_ELEMENT.SAN_RDPM_UA_S_OBS_L2  FI FI"
 :NCLASS KERNEL-ORDO:OBS-NODE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)