
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296658335882
 :NAME :SAN_RDPM_UA_B_IS_PO
 :COMMENT "Is a Project objective?"
 :DATASET 118081000141
 :FORMULA "WBS_TYPE.SAN_RDPM_UA_B_IS_PROJECT_OBJECTIVES"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)