
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296637841471
 :NAME :SAN_RDPM_UA_B_INDICATION_EXPORT_FILTER
 :COMMENT "Is an exported indication?"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_B_EXPORTED_PROJECT_FILTER AND NOT SAN_RDPM_UA_B_OLD_BRANCH_FILTER_F AND SAN_RDPM_UA_B_IS_AN_INDICATION"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)