
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296637889571
 :NAME :SAN_RDPM_UA_B_PORTFOLIO_FILTER_CONTEXT
 :COMMENT "Context filter is from portfolio"
 :DATASET 118081000141
 :FORMULA "LEVEL=1 AND _CRT_NF_B_PTF_FILTER"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)