
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296658648782
 :NAME :SAN_RDPM_UA_S_PH_CSU_CLUSTER
 :COMMENT "CSU Cluster"
 :DATASET 118081000141
 :FORMULA "_RM_REVIEW_RA_LOCATION.SAN_RDPM_UA_COUNTRY.SAN_RDPM_UA_CTRY_CSU_CLUSTER"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)