
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296659204182
 :NAME :SAN_RDPM_UA_S_WBSF_WRI_NARRATIVES_SOURCING
 :COMMENT "WRI Role - Narratives Production - Sourcing"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN san_pjs_get_wbs_form_string_value_on_object(SAN_RDPM_UA_S_ID_NARRATIVES_PRODUCTION,\"CDOC-WRI\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)