
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296654201874
 :NAME :SAN_RDPM_UA_S_IMPACT_CODE
 :COMMENT "Impact Code"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_ACT_S_CALCULATED_STUDY_CODE+\"_\"+STRING_VALUE(\"__USER_TABLE_SAN_RWE_UT_COUNTRY\",SAN_RDPM_UA_ACT_COUNT_ACT_F,\"SAN_RWE_UA_S_ISO_A3\")+\"_\"+PRINT_NUMBER(SAN_RDPM_UA_ACT_MILESTONE_PERIOD_F,\"####\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)