
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296659188682
 :NAME :SAN_RDPM_UA_N_PRP_POURCENTAGE
 :COMMENT "PRP %"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF WEIGHT <>\"\" THEN WEIGHT ELSE 0 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)