
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296660793282
 :NAME :SAN_RDPM_UA_S_ROLE_LEADER_SITE
 :COMMENT "Role Leader Site"
 :DATASET 118081000141
 :FORMULA "san_pjs_get_wbs_form_string_value_on_object(ACTIVITY,_RM_REVIEW_RA_ROLE,\"USER_ATTRIBUTE_SAN_UA_S_LEADER_SITE\")"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)