
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296660794482
 :NAME :SAN_RDPM_UA_S_ROLE_EXCLUDE_RESOURCES
 :COMMENT "Role Excluding resources"
 :DATASET 118081000141
 :FORMULA "san_pjs_get_wbs_form_boolean_value_on_object(ACTIVITY,_RM_REVIEW_RA_ROLE,\"USER_ATTRIBUTE_SAN_UA_B_EXCLUDED_RES\")"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)