
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296659819982
 :NAME :SAN_RDPM_UA_NB_COHORT_PER_COUNTRY
 :COMMENT "Cohort country number"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF SAN_RDPM_UA_NB_COUNTRY=1 then LIST_LENGTH(SAN_RDPM_UA_S_COHORT_COUNTRY_LIST) else if (LIST_LENGTH(SAN_RDPM_UA_S_COHORT_COUNTRY_LIST)-LIST_LENGTH(LIST_REMOVE(SPJ.SAN_RDPM_UA_ACT_COUNT,SAN_RDPM_UA_S_COHORT_COUNTRY_LIST)))=0.00 THEN 1 else IF (LIST_LENGTH(SAN_RDPM_UA_S_COHORT_COUNTRY_LIST)-LIST_LENGTH(LIST_REMOVE(SPJ.SAN_RDPM_UA_ACT_COUNT,SAN_RDPM_UA_S_COHORT_COUNTRY_LIST)))=\"\" then 1 else (LIST_LENGTH(SAN_RDPM_UA_S_COHORT_COUNTRY_LIST)-LIST_LENGTH(LIST_REMOVE(SPJ.SAN_RDPM_UA_ACT_COUNT,SAN_RDPM_UA_S_COHORT_COUNTRY_LIST))) fi fi fi"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)