
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296660131282
 :NAME :SAN_RDPM_UA_S_ACT_DMM
 :COMMENT "? DMM activity"
 :DATASET 118081000141
 :FORMULA "SPJ.WBS_TYPE=\"DMM\" and ?TASK"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)