
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296665427476
 :NAME :SAN_RDPM_UA_RES_COST_CENTER
 :COMMENT "Cost Center"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_COST_CENTER
)