
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296660125482
 :NAME :SAN_RDPM_UA_D_PROPOSED_PF
 :COMMENT "Proposed Planned Finish"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)