
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296658647682
 :NAME :SAN_RDPM_UA_S_PH_RES_SERV_DESC
 :COMMENT "Resource Service Description"
 :DATASET 118081000141
 :FORMULA "RES.SAN_UA_RDPM_RES_SERV_DESC"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)