
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296652555982
 :NAME :SAN_RDPM_D_STUDY_CONDUCT_START_DATE
 :COMMENT "Start date of Study conduct"
 :DATASET 118081000141
 :FORMULA "ITER_DATE_MIN(\"CHILDREN\",\"BELONGS(\\\"WBS_TYPE\\\",\\\"Study conduct\\\")\",PS)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)