
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296637842471
 :NAME :SAN_RDPM_UA_B_EXPORTED_PROJECT_FILTER
 :COMMENT "Is in exported project?"
 :DATASET 118081000141
 :FORMULA "PROJECT._CRT_NF_B_PTF_FILTER"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)