
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296646861470
 :NAME :SAN_RDPM_UA_S_PROJECT_STATUS
 :COMMENT "Project Status"
 :DATASET 118081000141
 :FORMULA "PROJECT._STA_RA_PRJ_STATUS"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)