
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296657163669
 :NAME :SAN_RDPM_UF_N_WEIGHT_SETUP
 :COMMENT "Specific weight for setup (Cohort)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF BELONGS(\"WBS_TYPE\",\"ESC/STAGE\") THEN (WBS_ELEMENT.SAN_RDPM_UF_N_WEIGHT_SITES+WBS_ELEMENT.SAN_RDPM_UF_N_WEIGHT_SUBJECTS)/2 ELSE 0 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)