
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296659190482
 :NAME :SAN_RDPM_UA_S_SKILL_DESC
 :COMMENT "Skill Description"
 :DATASET 118081000141
 :FORMULA "DESC"
 :NCLASS KERNEL-ORDO:RESOURCE-SKILL
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)