
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296658645382
 :NAME :SAN_RDPM_UA_N_CTAM_RATIO
 :COMMENT "CTAM Ratio for Algorithms"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)