
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296657313382
 :NAME :SAN_RDPM_UA_N_MONTH_DU_FIRST_IP_TO_LPI
 :COMMENT "Duration from First IP to LPI/LSI (Month)"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN DIFF_DATE(SAN_RDPM_UA_D_PS_FIRST_IP,SAN_RDPM_UA_PLANNED_LPI_LSI,CAL)/'22d' ELSE WBS_ELEMENT.SAN_RDPM_UA_N_MONTH_DU_FIRST_IP_TO_LPI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)