
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296647810382
 :NAME :SAN_RDPM_UA_D_PS_MIN_RESUPPLY
 :COMMENT "Re-supply min PS "
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN ITER_DATE_MIN(\"ALL_CHILDREN\",\"?TASK and BELONGS(\\\"WBS_TYPE\\\",\\\"Re-supply\\\")\",\"PS\") ELSE '-1' FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)