
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296657126969
 :NAME :SAN_RDPM_UF_N_WEIGHT_AVERAGE
 :COMMENT "Average weight (Cohort)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF BELONGS(\"WBS_TYPE\",\"ESC/STAGE,EXP/STAGE,COHORT\") THEN (SAN_RDPM_UF_N_WEIGHT_DU+SAN_RDPM_UF_N_WEIGHT_SITES+SAN_RDPM_UF_N_WEIGHT_SUBJECTS)/3 ELSE 0 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)