
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296660325982
 :NAME :SAN_RDPM_UA_S_GLOBAL_QC_TYPE_MOVEMENT
 :COMMENT "Global QC on Type of movement"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_S_QC_TYPE_MOVEMENT<>\"\" THEN SAN_RDPM_UA_S_QC_TYPE_MOVEMENT ELSE \"x - Type of movement well defined\" FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)