
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296637930371
 :NAME :SAN_RDPM_UA_S_PHASE_LIST
 :COMMENT "Existing phase"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"_PAC_DR_PROJECT_PHASES\",\"TRUE\",\"ONB\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)