
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296659234482
 :NAME :SAN_RDPM_UA_ACT_FLAG_IMPACT_FIRST_IP
 :COMMENT "Pack impact on First IP on site?"
 :DATASET 118081000141
 :FORMULA "IF BELONGS(\"WBS_TYPE\", \"Packaging,Packaging review & release\") THEN ITER_BOOLEAN_THERE_IS_ONE(\"SUCCESSOR_TASKS\",\"BELONGS(\\\"WBS_TYPE\\\", \\\"Distribution\\\" )\") FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)