
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296643679374
 :NAME :SAN_RDPM_UA_B_HEADCOUNT_REPORT_FILTER
 :COMMENT "Headcount report resource filter"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "_INF_AA_B_GENERIC_RES AND NOT(SAN_UA_RWE_B_EXTERNAL) AND NOT(ITER_BOOLEAN_THERE_IS_ONE(\"ELEMENTS\",\"_INF_AA_B_GENERIC_RES\"))"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)