
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296660587482
 :NAME :SAN_RDPM_UA_S_PROJECT_DESCRIPTION
 :COMMENT "R&D Project Description"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"PROJECT\",SAN_RDPM_UA_PRJ_S_ROOT_PROJECT, \"DESC\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)