
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296637781369
 :NAME :SAN_RDPM_UF_D_STUD_COMP
 :COMMENT "Date of Study completion task"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF SAN_RDPM_UF_B_COHORT_REPORT_FILTER THEN ITER_DATE_MIN(\"CHILDREN\",\"BELONGS(\\\"WBS_TYPE\\\",\\\"Study completion\\\")\",\"PS\") ELSE -1 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)