
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296660613782
 :NAME :SAN_RDPM_UA_S_TRANSVERSAL_R&D
 :COMMENT "R&D - Non R&D - Transversal"
 :DATASET 118081000141
 :FORMULA "IF PROJECT.SAN_UA_RWE_PROJECT_CODE_PRIME IN (\"SUPPORT\",\"DC*\",\"OC*\",\"RP*\") THEN \"Transversal\" ELSE IF SAN_RDPM_UA_ACT_OBS_CALCULATED_BUDGET_OWNER=\"R&D\" THEN  		\"R&D\" ELSE \"Non R&D\" FI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)