
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296658650082
 :NAME :SAN_RDPM_UA_S_PH_ACT_DESC
 :COMMENT "Activity Description (F)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.DESC"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)