
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296659196482
 :NAME :SAN_RDPM_UA_S_WBSF_SDM_SOURCING
 :COMMENT "SDM Role - Sourcing"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_S_OBS_CALCULATED_DBL=\"DB1502\" THEN if san_pjs_get_wbs_form_string_value_on_object(ID,\"CDMS-SDM\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") <> \"\" then san_pjs_get_wbs_form_string_value_on_object(ID,\"CDMS-SDM\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") else san_pjs_get_wbs_form_string_value_on_object(ID,\"TODMS-SDM\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") fi ELSE IF SAN_RDPM_UA_S_OBS_CALCULATED_DBL=\"DB1501\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"EDOO-SDM\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") ELSE IF SAN_RDPM_UA_S_OBS_CALCULATED_DBL=\"DB1400\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"EDO-CTDM\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") ELSE IF SAN_RDPM_UA_S_OBS_CALCULATED_DBL=\"DB1401\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"EDCO-SDM\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") FI FI FI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)