
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296646904874
 :NAME :SAN_UA_RDPM_S_RES_CSU_CLUSTER
 :COMMENT "CSU Cluster"
 :DATASET 118081000141
 :FORMULA "_RM_REVIEW_RA_LOCATION.SAN_RDPM_UA_COUNTRY.SAN_RDPM_UA_CTRY_CSU_CLUSTER"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)