
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296659195582
 :NAME :SAN_RDPM_UA_S_BUDGET_OWNER_ORGANIZATION
 :COMMENT "Budget Owner Organization"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_ACT_OBS_CALCULATED_BUDGET_OWNER=\"R&D\" AND SAN_RDPM_UA_S_WBS_TYPE_INDICATION_OTHER in (\"INDICATION\") THEN SAN_RDPM_UA_S_INDICATION_OWNER_DESC_F ELSE  IF SAN_RDPM_UA_ACT_OBS_CALCULATED_BUDGET_OWNER=\"R&D\" AND SAN_RDPM_UA_S_WBS_TYPE_INDICATION_OTHER in (\"OTHER\") THEN PROJECT.SAN_RDPM_UA_S_PROJECT_RESP_DESC ELSE  STRING_VALUE(\"RESPONSIBILITY\",SAN_RDPM_UA_ACT_OBS_CALCULATED_BUDGET_OWNER,\"SAN_RDPM_UA_S_OBS_L2\") FI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)