
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296646861170
 :NAME :SAN_RDPM_UA_S_PROJECT_PHASE
 :COMMENT "Project Phase"
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_UA_PROJECT_PHASE"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)