
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296646131670
 :NAME :SAN_RDPM_UA_D_PHARMA_YEARLY_DATE
 :COMMENT "Yearly baseline date (Pharma)"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF GETINTERNALSTRINGVALUE(\"ACTIVITY\",ID,\"TASK_TYPE\") = \"START-MILESTONE\" THEN SAN_RDPM_UA_D_PHARMA_YEARLY_SD ELSE SAN_RDPM_UA_D_PHARMA_YEARLY_FD FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)