
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296637844871
 :NAME :SAN_RDPM_UA_B_PHASE_EXPORT_FILTER
 :COMMENT "Is an exported phase?"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_B_EXPORTED_PROJECT_FILTER AND NOT SAN_RDPM_UA_B_OLD_BRANCH_FILTER_F AND _PAC_NF_B_PHASE"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)