
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296658647982
 :NAME :SAN_RDPM_UA_S_PH_RES_TEAM
 :COMMENT "Resource Team"
 :DATASET 118081000141
 :FORMULA "RES.SAN_RDPM_UA_S_RES_TEAM"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)