
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296636057970
 :NAME :SAN_RDPM_UA_OC_S_EXPORT_SHINE_PATH
 :COMMENT "Shine export path"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "OC.SAN_UF_S_MAIN_PATH+OC.SAN_CS_SHINE_EXPORT_PATH"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)