
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296657318082
 :NAME :SAN_RDPM_UA_S_MONTH_DU_LPI_TO_LPLV
 :COMMENT "Duration from LPI/LSI to LPLV/LSLV (Month)"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN DIFF_DATE(SAN_RDPM_UA_PLANNED_LPI_LSI,SAN_RDPM_UA_PLANNED_LPLV_LSLV,CAL)/'22d' ELSE WBS_ELEMENT.SAN_RDPM_UA_S_MONTH_DU_LPI_TO_LPLV FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)