
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296654949974
 :NAME :SAN_UA_B_ACTUAL_FROM_IMPACT
 :COMMENT "Actual date imported from Impact?"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CLINICAL_MILESTONES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)