
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296647811082
 :NAME :SAN_RDPM_UA_D_PF_MAX_RESUPPLY
 :COMMENT "Re-supply max PF "
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN ITER_DATE_MAX(\"ALL_CHILDREN\",\"?TASK and BELONGS(\\\"WBS_TYPE\\\",\\\"Re-supply\\\")\",\"PF\") ELSE '-1' FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)