
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296637845471
 :NAME :SAN_RDPM_UA_B_STUDY_EXPORT_FILTER
 :COMMENT "Is an exported study?"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_B_EXPORTED_PROJECT_FILTER AND NOT SAN_RDPM_UA_B_OLD_BRANCH_FILTER_F AND SAN_UA_RDPM_B_IS_A_STUDY"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)