
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296637845771
 :NAME :SAN_RDPM_UA_B_TASK_EXPORT_FILTER
 :COMMENT "Is an exported task?"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_B_EXPORTED_PROJECT_FILTER AND NOT SAN_RDPM_UA_B_OLD_BRANCH_FILTER_F AND NOT (WBS_ELEMENT = \"\" OR SAN_RDPM_UA_B_INDICATION_EXPORT_FILTER OR SAN_RDPM_UA_B_PHASE_EXPORT_FILTER OR SAN_RDPM_UA_B_STUDY_EXPORT_FILTER)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)