
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296652556682
 :NAME :SAN_RDPM_UA_D_START_TASK_LPI_LSI
 :COMMENT "Duration From start of Task to LPI/LSI"
 :DATASET 118081000141
 :DEFAULT-VALUE 0
 :FORMULA "DIFF_DATE(PS,SPJ.SAN_RDPM_UA_PLANNED_LPI_LSI,CAL)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME:DURATION
)