
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296675614176
 :NAME :SAN_RDPM_UA_ACT_NB_CRF_PAGE_SUBJECT_F
 :COMMENT "Nb CRF Pages per Subject (F)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF SAN_RDPM_UA_ACT_NB_CRF_PAGE_SUBJECT <>\"\" THEN SAN_RDPM_UA_ACT_NB_CRF_PAGE_SUBJECT ELSE WBS_ELEMENT.SAN_RDPM_UA_ACT_NB_CRF_PAGE_SUBJECT_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)