
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296660838282
 :NAME :SAN_UA_B_IS_ACT_BCB
 :COMMENT "? is there a BCB activity"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN ITER_BOOLEAN_THERE_IS_ONE(\"ALL CHILDREN\",\"SAN_RDPM_UF_OBS_BCB\") else WBS_ELEMENT.SAN_UA_B_IS_ACT_BCB FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)