
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296637925871
 :NAME :SAN_RDPM_UA_S_UNIQUE_IND_CODE
 :COMMENT "Unique Ind Code"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_B_IS_AN_INDICATION THEN FILE FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)