
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296647430382
 :NAME :SAN_RDPM_UA_ACT_B_LINK_SPJ_BK
 :COMMENT "Link to activity embedded on BK study?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "?TASK and ITER_BOOLEAN_THERE_IS_ONE(\"SLINKS\",\"SUCC_ACTIVITY.spj.OBS_ELEMENT=\\\"BK\\\"\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)