
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296658646782
 :NAME :SAN_RDPM_UA_S_PH_RES_DPT
 :COMMENT "Resource Department"
 :DATASET 118081000141
 :FORMULA "RES.SAN_UA_RDPM_RES_DEP"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)