
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296659199582
 :NAME :SAN_RDPM_UA_S_ID_LPI_LSI
 :COMMENT "LPI/LSI ID"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN LIST_COLLECT(\"ALL_CHILDREN\",\"?TASK and BELONGS(\\\"WBS_TYPE\\\",oc.SAN_RDPM_CS_AT_LPI_LSI)\",\"ID\") ELSE WBS_ELEMENT.SAN_RDPM_UA_S_ID_LPI_LSI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)