
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296660823482
 :NAME :SAN_RDPM_UF_OBS_DMPK
 :COMMENT "DMPK?"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"RESPONSIBILITY\",OC.SAN_RDPM_CS_OBS_DMPK)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)