
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296659193982
 :NAME :SAN_RDPM_UA_S_WBSF_WRI_PROCOL_SOURCING
 :COMMENT "WRI Role - Protocol - Sourcing"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN san_pjs_get_wbs_form_string_value_on_object(SAN_RDPM_UA_S_ID_PROTOCOL,\"CDOC-WRI\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)