
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296660612782
 :NAME :SAN_UA_D_DBL_MAX_PF
 :COMMENT "DBL Max Planned Finish"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "ITER_DATE_MAX(\"ALL_CHILDREN\",\"BELONGS(\\\"WBS_TYPE\\\",OC.SAN_RDPM_CS_AT_DBL)\",\"PF\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)