
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296646132570
 :NAME :SAN_RDPM_UA_D_BL2_FD
 :COMMENT "Baseline 2 Finish Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF TASK_TYPE = \"Start milestone\" then DATE_VALUE(\"ACTIVITY\",ID,\"SD_\" + OC.DATE2) else DATE_VALUE(\"ACTIVITY\",ID,\"FD_\" + OC.DATE2)-'1d' FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)