
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296637842971
 :NAME :SAN_RDPM_UA_B_INDICATION_EXPORT_FILTER_F
 :COMMENT "Is an exported indication? (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_B_INDICATION_EXPORT_FILTER THEN TRUE ELSE WBS_ELEMENT.SAN_RDPM_UA_B_INDICATION_EXPORT_FILTER_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)