
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296658644282
 :NAME :SAN_RDPM_UA_S_PH_PRJ_CODE
 :COMMENT "Project Code"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_ROOT_PROJECT_CODE_F"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)