
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296646861770
 :NAME :SAN_RDPM_UA_S_PROJECT_PRIORITY_VALUE
 :COMMENT "Priority Value"
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_UA_PRJ_S_PRIORITY "
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)