
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296646131970
 :NAME :SAN_RDPM_UA_B_PHARMA_PLANNING_VARIANCE_TABLE_STYLE_FILTER
 :COMMENT "Pharma planning variance table style filter"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"WBS_TYPE\",OC.SAN_RDPM_CS_CLINICAL_ACTIVITIES) AND SAN_RDPM_UA_ACT_B_PRJL"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)