
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296637847271
 :NAME :SAN_RDPM_UA_B_OLD_BRANCH_FILTER
 :COMMENT "Is excluded from Datahub export?"
 :DATASET 118081000141
 :FORMULA "IF OC.SAN_RDPM_CS_OLD_BRANCH_EXCLUSION <> \"\" THEN  EVALUATE_FILTER(OC.SAN_RDPM_CS_OLD_BRANCH_EXCLUSION) FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)