
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296660609782
 :NAME :SAN_RDPM_UA_D_PF_ABBREVIATED_PROTOCOL
 :COMMENT "Abbreviated Protocol PF"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN ITER_DATE_MIN(\"ALL_CHILDREN\",\" BELONGS(\\\"WBS_TYPE\\\",OC.SAN_RDPM_CS_AT_ABBREVIATED_PROTOCOL)\",\"PF\") ELSE '-1' FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)