
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296660339682
 :NAME :SAN_UA_B_IS_THERE_ACT_REG_CALCULATED
 :COMMENT "? is REG activity calculated"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY AND SAN_UA_B_IS_ACT_REG AND SAN_RDPM_UF_OBS_REGULATORY then SAN_UA_B_IS_ACT_REG else WBS_ELEMENT.SAN_UA_B_IS_THERE_ACT_REG_CALCULATED FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)