
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 296635553373
 :NAME :SAN_RDPM_UA_OC_B_EQUATIONS_RUNNING
 :COMMENT "Are Equations Running?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)