
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310189067874
 :NAME :SAN_RDPM_UA_B_PHASE_LCM
 :COMMENT "Has a LCM Phase?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_PS_SUBMISSION_LEAD_INDICATION<>-1 AND SAN_RDPM_UA_PS_APPROVAL_LEAD_INDICATION<>-1 AND SAN_RDPM_UA_PS_APPROVAL_LEAD_INDICATION>SAN_RDPM_UA_PS_SUBMISSION_LEAD_INDICATION"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)