
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310198566276
 :NAME :SAN_RDPM_UA_ACT_S_PREVIOUS_GNG_PHASE
 :COMMENT "GNG of Phase"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_RND_PHASE_F<>\"\" AND WBS_TYPE._WT_AA_B_CONSO_SF_FM THEN _pac_get_previous_gate_or_stage(WBS_TYPE,\"SAN_RDPM_UA_B_IS_GNG_PO\") FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)