
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310192485276
 :NAME :SAN_UA_STUDY_PHASE_NB_UNIQUE_CRF_PAGE_SUBJECT
 :COMMENT "Nb Unique CRF pages per Subject"
 :DATASET 118081000141
 :DEFAULT-VALUE 60.0d0
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_STUDY_PHASE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)