
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310189066374
 :NAME :SAN_RDPM_UA_B_PHASE_M2_PH1
 :COMMENT "Has a M2-PH1 Phase?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_PS_M2_LEAD_INDICATION<>-1 AND SAN_RDPM_UA_PS_PH1_LEAD_INDICATION<>-1 AND SAN_RDPM_UA_PS_PH1_LEAD_INDICATION>SAN_RDPM_UA_PS_M2_LEAD_INDICATION"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)