
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310189065774
 :NAME :SAN_RDPM_UA_B_PHASE_M0_M1
 :COMMENT "Has a M0-M1 Phase?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_PS_M0_LEAD_INDICATION<>-1 AND SAN_RDPM_UA_PS_M1_LEAD_INDICATION<>-1 AND SAN_RDPM_UA_PS_M1_LEAD_INDICATION>SAN_RDPM_UA_PS_M0_LEAD_INDICATION"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)