
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310199807174
 :NAME :SAN_RDPM_UA_S_LINK_TYPE
 :COMMENT "Link Type"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_AUTO_LINKS
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :LINK_TYPE
)