
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310191457474
 :NAME :SAN_RDPM_UA_S_RES_OBS_DESC
 :COMMENT "OBS Description"
 :DATASET 118081000141
 :FORMULA "OBS_ELEMENT.DESC"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)