
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310195346176
 :NAME :SAN_RDPM_UA_ACT_GNG_DATE_PLANNED
 :COMMENT "GNG Planned date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "DATE_VALUE(\"TASK\",SAN_RDPM_UA_ACT_S_PREVIOUS_GNG_PHASE,\"PF\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)