
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310189065474
 :NAME :SAN_RDPM_UA_B_PHASE_PRE_M0
 :COMMENT "Has a Pre-M0 Phase?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "PS<>-1 AND SAN_RDPM_UA_PS_M0_LEAD_INDICATION<>-1 AND SAN_RDPM_UA_PS_M0_LEAD_INDICATION>PS"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)