
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310189063976
 :NAME :SAN_UA_STUDY_PHASE_NB_CRF_PAGE_SUBJECT
 :COMMENT "Nb CRF Pages per Subject"
 :DATASET 118081000141
 :DEFAULT-VALUE 90.0d0
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_STUDY_PHASE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)