
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310191387474
 :NAME :SAN_RDPM_UA_B_PHASE_PH2A
 :COMMENT "Has a phase 2a?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_PS_PH2A_LEAD_INDICATION<>-1 AND SAN_RDPM_UA_PS_PH2B_LEAD_INDICATION<>-1 AND SAN_RDPM_UA_PS_PH2B_LEAD_INDICATION>SAN_RDPM_UA_PS_PH2A_LEAD_INDICATION"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)