
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310222580676
 :NAME :SAN_RDPM_UA_ACT_MANAGING_UNIT_F
 :COMMENT "Managing Unit (F)"
 :DATASET 118081000141
 :FORMULA "IF  SAN_RDPM_UA_ACT_MANAG_UNIT <>\"\" THEN  SAN_RDPM_UA_ACT_MANAG_UNIT ELSE  WBS_ELEMENT.SAN_RDPM_UA_ACT_MANAGING_UNIT_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)