
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310234750576
 :NAME :SAN_RDPM_UA_USER_DOMAINE
 :COMMENT "Domain"
 :DATASET 118081000141
 :FORMULA "IF USER_IN_GROUP(ID,OC.SAN_RDPM_CS_AT_VACCINE_USER_GROUP) THEN \"Vaccine\" ELSE IF USER_IN_GROUP(ID,OC.SAN_RDPM_CS_AT_PHARMA_USER_GROUP) THEN \"Pharma\" FI  FI"
 :NCLASS GENERIC-IO:OPX2-USER
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)