
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310212888770
 :NAME :SAN_RDPM_UA_S_LIST_PREDECESSORS
 :COMMENT "List of predecessors"
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"PLINKS\",\"TRUE\",\"PA.ONB\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)