
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310232115170
 :NAME :SAN_UF_RDPM_STUDY_CODE_CONSOLIDATION_F
 :COMMENT "Study code consolidation (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_R_STUDY_CODE_CONSOLIDATION<>\"\" THEN SAN_UA_RDPM_R_STUDY_CODE_CONSOLIDATION ELSE SAN_RDPM_UA_ACT_S_CALCULATED_STUDY_CODE FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)