
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310233213270
 :NAME :SAN_UA_B_NON_PROD_EMAIL
 :COMMENT "Email Sending prohibited?"
 :DATASET 118081000141
 :FORMULA "EMAIL_ADDRESS<>\"\" AND NOT OC.SAN_UA_B_PROD_DATABASE AND NOT LIST_FIND(EMAIL_ADDRESS,OC.EMAIL_NOTIFICATION_RECEPIENT)"
 :NCLASS GENERIC-IO:OPX2-USER
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)