
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310212727670
 :NAME :SAN_RDPM_UF_ACT_D_RELEASE_DATE
 :COMMENT "Release Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "ITER_DATE_MIN(\"SLINKS\",\"EVALUATE_BOOLEAN_ON_OBJECT(\\\"ACTIVITY\\\", SUCC, \\\"BELONGS(\\\\\\\"WBS_TYPE\\\\\\\",OC.SAN_RDPM_CS_AT_PACKAGING_REVIEW_RELEASE)\\\")\",\"SUCC.PF\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)