
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310233085873
 :NAME :SAN_RDPM_UF_ACT_B_SR_FILTER_DU
 :COMMENT "Synchro Rule Filter DU"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "BELONGS(\"WBS_TYPE\",\"Recruitment,Treatment\") AND NOT SAN_RDPM_UA_ACT_B_OPL_DRIVING"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)