
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310239819672
 :NAME :SAN_RDPM_UA_ACT_CLIN_PRJ_SIZE
 :COMMENT "Clinical Project Size"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :CLINICAL_PROJECT_SIZE
)