
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310262139810
 :NAME :SAN_RDPM_UA_S_SUB_TYPE_CONTRACT
 :COMMENT "Sub-type of contract"
 :DATASET 118081000141
 :FORMULA "SAN_UA_RDPM_RES_CTR_TYP.SAN_RDPM_UT_RES_CTR_TYP"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)