
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310222875841
 :NAME :SAN_RDPM_UF_N_EQUA_BATCH_NB
 :COMMENT "Nb of batchs to launch for equations"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF $DATABASE_NAME in (\"DATABASE_PROD\",\"DATABASE_PREPROD\") THEN 10 ELSE 4 FI"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)