
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310243580072
 :NAME :SAN_UA_RDPM_N_PERC_VACC_REGION
 :COMMENT "Percentage Vaccines Region"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "SAN_UA_RDPM_PV_REG_VACC.SAN_UA_RDPM_N_PERC_DISTRIB_VACC"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)