
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310223546576
 :NAME :SAN_RDPM_UA_SC_STUDY_SPONSOR_NAME
 :COMMENT "Study Sponsor Name"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_PRIME_CODES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::...__USER_TABLE_SAN_UT_SPONSOR
)