
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310222581176
 :NAME :SAN_RDPM_UA_ACT_STUDY_MANAGER_NAME_F
 :COMMENT "Study Manager Name (F)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"USER\",SAN_RDPM_RO_STUDY_MANAGER,\"DESC\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)