
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310200899976
 :NAME :SAN_RDPM_UA_ACT_ROOT_PRODUCT_CODE
 :COMMENT "Root Product Code "
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RWE_UT_PRODUCT
)