
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310234752676
 :NAME :SAN_RDPM_UA_PROJECT_TEAM_FIRST_NAME
 :COMMENT "First name"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_USER.SAN_UA_S_AD_GIVEN_NAME"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)