
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310210057976
 :NAME :SAN_RDPM_UA_GCI_ASSAY_SAMPLE_NUM
 :COMMENT "Sample number"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY_ACTIVITY
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)