
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310234126869
 :NAME :SAN_RDPM_UF_N_SITES_COHORT_PEX
 :COMMENT "Planned sites for cohort report"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN 0 ELSE SAN_RDPM_CF_COHORT_SITES FI "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)