
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310206076276
 :NAME :SAN_RDPM_UA_ACT_COUNTRY_REG_F
 :COMMENT "Country (Reg) (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_ACT_COUNTRY_REG <> \"\" THEN SAN_RDPM_UA_ACT_COUNTRY_REG ELSE WBS_ELEMENT.SAN_RDPM_UA_ACT_COUNTRY_REG_F FI "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur| :|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)