
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310223531871
 :NAME :SAN_RDPM_UA_B_AS_METRIC_ACTIVE
 :COMMENT "Activate for FR AS metrics?"
 :DATASET 118081000141
 :FORMULA "WBS_TYPE.SAN_RDPM_UA_B_AS_METRIC_ACTIVE"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)