
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310235735582
 :NAME :SAN_RDPM_UA_S_WBSF_TSOM_LEADER
 :COMMENT "CSSM Role - Leader"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"CSC-CSSM\",\"USER_ATTRIBUTE_SAN_UA_S_LEADER\") FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)