
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310203359276
 :NAME :SAN_RDPM_UA_ACT_INDICATION_DATE
 :COMMENT "Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)