
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310219129176
 :NAME :SAN_RDPM_UA_PROJECT_TEAM_MEMBER_RESP_DESC
 :COMMENT "Responsibility Description"
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_UA_S_PROJECT_RESP_DESC"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)