
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310235741782
 :NAME :SAN_RDPM_UA_B_IS_CSO_RESOURCE
 :COMMENT "is CSO/EGDS Resource?"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"OBS_ELEMENT\",OC.SAN_RDPM_CS_OBS_CSO)"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)