
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310212328371
 :NAME :SAN_RDPM_B_RND_ACTIVITY
 :COMMENT "R&D Project"
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_UA_RD_PROJECT"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)