
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310235895382
 :NAME :SAN_RDPM_UA_PF_LAST_MONTHLY_BL
 :COMMENT "PF date at last Monthly baseline"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "DATE_VALUE(\"ACTIVITY\",ID,\"FD_\"+OC.SAN_RDPM_CS_LAST_MONTHLY_PHARMA)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)