
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310232391072
 :NAME :SAN_RDPM_UA_PRJ_LEAD_IND_DESC
 :COMMENT "Description of the Lead indication"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_PRJ_RND_PRJ THEN list_collect(\"ATTACHED_PROJECTS\",\"SAN_UA_B_PRJ_IS_LEAD_INDICATION\",\"DESC\")  FI "
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)