
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310231739772
 :NAME :SAN_RDPM_UF_ACT_S_FLX_ORDR
 :COMMENT "Flexible Report Grouping  Order"
 :DATASET 118081000141
 :FORMULA "number_value(\"ACTIVITY\",SAN_RDPM_UA_ACT_S_INDICATION_ID ,\"SAN_RDPM_UA_FREE_FIELD_PROJECT_PPR\") +SAN_RDPM_UA_ACT_S_INDICATION "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)