
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310200072576
 :NAME :SAN_RDPM_UA_ACT_SEGMENT_F
 :COMMENT "Velocity (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_ACT_SEGMENT <> \"\" THEN SAN_RDPM_UA_ACT_SEGMENT ELSE WBS_ELEMENT.SAN_RDPM_UA_ACT_SEGMENT_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)