
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310235469582
 :NAME :SAN_RDPM_UA_S_DEPT_CODE_CSU_REGION
 :COMMENT "Financial Dpt code - CSU Region"
 :DATASET 118081000141
 :FORMULA "IF RES.NAME<>\"CSU\" THEN  RES.SAN_UA_RDPM_RES_DEP_DESC ELSE \"DB17 - \" + _RM_REVIEW_RA_LOCATION.SAN_RDPM_UA_SITE_CSU_REG  FI"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)