
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310212300772
 :NAME :SAN_RDPM_UA_ACT_S_INDPH_APDAT
 :COMMENT "Indication phase at approval date"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :INDICATION_PHASE_AT_PRIO_DATE
)