
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310233086573
 :NAME :SAN_RDPM_UF_ACT_B_SR_FILTER_FNL_PF
 :COMMENT "Synchro Rule Filter FNL PF"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "WBS_TYPE.SAN_RDPM_UA_AT_B_TECH_MIL AND SAN_RDPM_UA_ACT_B_OPL_DRIVING"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)