
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310263676371
 :NAME :SAN_UA_N_NUM_LOT
 :COMMENT "# Lot(s) (stored value)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_WBS_FORM_DATA
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)