
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310236608870
 :NAME :SAN_UF_RDPM_PE_STUDY_MANAGER_NAME_F
 :COMMENT "Study manager name (F)"
 :DATASET 118081000141
 :FORMULA "Activity.SAN_RDPM_UA_ACT_STUDY_MANAGER_NAME_F"
 :NCLASS DOD:EXPENDITURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)