
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310212296572
 :NAME :SAN_RDPM_UA_ACT_D_SR_APPR_DATE
 :COMMENT "Success Rate approval date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)