
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310212295172
 :NAME :SAN_RDPM_UA_ACT_SR
 :COMMENT "Reference Success Rate"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "WBS_TYPE.SAN_RDPM_UA_AT_N_SR"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)