
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310233065373
 :NAME :SAN_RDPM_UA_B_CLIN_STUDY_NOT_MIGRATED_F
 :COMMENT "Clinical study not migrated? (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN SAN_RDPM_UA_B_CLIN_STUDY_NOT_MIGRATED ELSE BOOLEAN_VALUE(\"ACTIVITY\",SAN_UA_RDPM_ACT_S_STUDY_ID,\"SAN_RDPM_UA_B_CLIN_STUDY_NOT_MIGRATED\") FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)