
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310200896876
 :NAME :SAN_RDPM_UA_ACT_RAISON_INDICATION_TERM_F
 :COMMENT "Reason for indication termination (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_ACT_RAISON_INDICATION_TERM <> \"\" THEN SAN_RDPM_UA_ACT_RAISON_INDICATION_TERM ELSE WBS_ELEMENT.SAN_RDPM_UA_ACT_RAISON_INDICATION_TERM_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)