
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310233086973
 :NAME :SAN_RDPM_UF_ACT_B_SR_FILTER_NO_SYNC
 :COMMENT "Synchro Rule Filter NO SYNC"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "BELONGS(\"WBS_TYPE\", \"Recruitment,Treatment,Cohort FPI to LPI,Cohort LPI to LPLV,Cohort LPLT to LPLV\") OR WBS_TYPE.SAN_RDPM_UA_AT_B_TECH_MIL"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)