
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310235734482
 :NAME :SAN_RDPM_UA_S_CSD_SMM_LEADER
 :COMMENT "CSD/SMM Leader"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN LIST_COLLECT(\"ALL_CHILDREN\",\"?TASK and BELONGS(\\\"WBS_TYPE\\\", \\\"PROTOCOL APPROVED\\\" )\",\"SAN_RDPM_UA_S_PHARMA_LEADER\") ELSE WBS_ELEMENT.SAN_RDPM_UA_S_CSD_SMM_LEADER FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)