
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310201577472
 :NAME :SAN_RDPM_UA_ACT_CSU_CLSTR_DESC
 :COMMENT "CSU Cluster Description"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_ACT_COUNT.SAN_RDPM_UA_CTRY_CSU_CLUSTER.DESC"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)