
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310233086273
 :NAME :SAN_RDPM_UF_ACT_B_SR_FILTER_DU_OL
 :COMMENT "Synchro Rule Filter DU OL"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_ACT_B_OPL AND BELONGS(\"WBS_TYPE\",\"Cohort FPI to LPI,Cohort LPI to LPLV,Cohort LPLT to LPLV\") AND NOT SAN_RDPM_UA_ACT_B_OPL_DRIVING"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)