
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310233213570
 :NAME :SAN_UA_B_PROD_DATABASE
 :COMMENT "Production database"
 :DATASET 118081000141
 :FORMULA "$DATABASE_NAME=\"DATABASE_PROD\""
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)