
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310235738582
 :NAME :SAN_RDPM_UA_S_TRANSVERSAL_CATEGORY
 :COMMENT "Transversal Category"
 :DATASET 118081000141
 :FORMULA "LIST_INTERSECT(SAN_RDPM_UA_SPECIFICITY_AND_TOOLS,\"IT Tool Dev.,Non Algo Population,Ope. SUPPORT,Innovation\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)