
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310235733582
 :NAME :SAN_RDPM_UA_S_OBS_DESC
 :COMMENT "OBS element Description"
 :DATASET 118081000141
 :FORMULA "OBS_ELEMENT.DESC"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)