
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310235895982
 :NAME :SAN_RDPM_UA_STUDY_UPDATE_1M_F
 :COMMENT "Study update > +/- 1M (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_STUDY_UPDATE_1M THEN SAN_RDPM_UA_STUDY_UPDATE_1M ELSE WBS_ELEMENT.SAN_RDPM_UA_STUDY_UPDATE_1M FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)