
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310263668976
 :NAME :SAN_RDPM_UA_PEXP_COST_ACCOUNT_MAIN
 :COMMENT "Cost account Main"
 :DATASET 118081000141
 :FORMULA "COST_ACCOUNT.SAN_RDPM_UA_S_COST_ACCOUNT_MAIN"
 :NCLASS DOD:EXPENDITURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)