
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310209923276
 :NAME :SAN_RDPM_UA_ACT_NO_GCI_TESTING_TRIAL_STEP
 :COMMENT "No GCI testing (Trial/Step)"
 :DATASET 118081000141
 :FORMULA "IF ?WBS_ELEMENT THEN ITER_BOOLEAN_THERE_IS_ONE(\"ALL_CHILDREN\",\"SAN_RDPM_UA_ACT_B_GCI_NOTST\")     ELSE FALSE FI "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)