
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310235468282
 :NAME :SAN_RDPM_UA_S_ID_OPER_FEASIBILITY
 :COMMENT "Feasibility Model"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"ACTIVITY\",SAN_RDPM_UA_S_ID_OP_FEASABILITY,\"SAN_RDPM_UA_S_OBS_DESC\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)