
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310235799682
 :NAME :SAN_UA_B_IS_THERE_ACT_PKDM
 :COMMENT "? is PKDM activity calculated"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN ITER_BOOLEAN_THERE_IS_ONE(\"CHILDREN\",\"?TASK AND OBS_ELEMENT.SAN_RDPM_UA_B_OBS_PKDM\") else WBS_ELEMENT.SAN_UA_B_IS_THERE_ACT_PKDM FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)