
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310235735882
 :NAME :SAN_RDPM_UA_BUDGET_DECISION_LAST_QUATERLY
 :COMMENT "Governance decision at last Quaterly baseline"
 :DATASET 118081000141
 :FORMULA "REFERENCE_STRING_VALUE(\"ACTIVITY\",ID,\"SAN_RDPM_UA_BUDGET_DECISION\",OC.SAN_RDPM_CS_LAST_QUATERLY_PHARMA)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)