
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310200069376
 :NAME :SAN_RDPM_UA_ACT_S_ECO_VALUE_F
 :COMMENT "Commercial Opportunity (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_ACT_S_ECO_VALUE <> \"\" THEN SAN_RDPM_UA_ACT_S_ECO_VALUE ELSE WBS_ELEMENT.SAN_RDPM_UA_ACT_S_ECO_VALUE_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)