
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310372228374
 :NAME :SAN_RDPM_UA_S_ROLE
 :COMMENT "Recipient"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_SOURCING_REQUEST_NOTIFICATION
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :SOURCING_ROLE
)