
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310382233374
 :NAME :SAN_RDPM_UA_N_RATE_CARD_MANAGEMENT_FEE
 :COMMENT "Monthly Management Fees"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_SOURCING_RATE_CARD
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)