
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310375074574
 :NAME :SAN_RDPM_UA_S_CANCELLATION_STATUS
 :COMMENT "Cancelled at"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_SOURCING_REQUEST_NOTIFICATION
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_SOURCING_REQUEST_STATUS
)