
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310375075074
 :NAME :SAN_UA_RDPM_S_CANCELLED_BY
 :COMMENT "Cancelled by"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_SOURCING_REQUEST_NOTIFICATION
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :SOURCING_ROLE
)