
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310375336610
 :NAME :SAN_RDPM_UA_B_PRJ_PO_NOTIF
 :COMMENT "Send Project Objectives notification?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "USER_IN_GROUP($CURRENT_USER,LIST_COLLECT(\"__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER\",\"SAN_RDPM_UA_PROJECT_ROLE.SAN_RDPM_UA_B_ROLE_PO_NOTIF\",\"SAN_RDPM_UA_USER\"))"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)