
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310372197174
 :NAME :SAN_RDPM_UA_S_SOURCING_TOOL_CUR_STATUS
 :COMMENT "Current Status"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_SOURCING_REQUEST_NEXT_STATUS
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_SOURCING_REQUEST_STATUS
)