
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310371926210
 :NAME :SAN_UA_RDPM_S_PEX_SIMULATED_RESOURCES2
 :COMMENT "CSU Cluster/Skill"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF LIST_FIND(SAN_UA_RDPM_RES_DEP, \"DB17-CSU\") THEN SAN_UA_RDPM_S_RES_CSU_CLUSTER  ELSE PRIMARY_SKILL FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)