
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310371972210
 :NAME :SAN_RDPM_UA_RES_S_AVAILIBILITY_TYPE
 :COMMENT "Availability Type"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_B_RES_SIMU THEN       		\"SIMU\"     ELSE 	IF SAN_RDPM_UA_B_SOURCING_REQUEST AND SAN_RDPM_UA_S_SOURCING_STATUS<>\"Validated\" THEN      		\"Sourcing\"  	ELSE 		\"Standard\"     	FI FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)