
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310379431470
 :NAME :SAN_RDPM_UA_D_VAC_BASELINE_DATE
 :COMMENT "Baseline date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_VACCINES_BASELINE_SCHEDULE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)