
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310382184174
 :NAME :SAN_RDPM_UA_S_SOURCING_MESSAGE_ID
 :COMMENT "Sourcing Tool - Message ID"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_S_SOURCING_TYPE+\"_\"+SAN_RDPM_UA_S_SOURCING_STATUS+IF SAN_RDPM_UA_S_SOURCING_STATUS=\"Cancelled\" THEN \"_\"+SAN_RDPM_UA_S_CANCELATION_STEP+\"_\"+SAN_RDPM_UA_S_CANCELLED_BY FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)