
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310371925710
 :NAME :SAN_UA_RDPM_S_PEX_SIMULATED_RESOURCES1
 :COMMENT "CSU Rgion/Team"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF LIST_FIND(SAN_UA_RDPM_RES_DEP,\"DB17-CSU\") THEN SAN_UA_RDPM_S_RES_CSU_REGION  ELSE SAN_RDPM_UA_S_RES_TEAM FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)