
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310382187274
 :NAME :SAN_RDPM_UA_S_NOTIFICATION_TYPE
 :COMMENT "Notification Type"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_SOURCING_REQUEST_NOTIFICATION
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :NOTIFICATION_TYPE
)