
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310382230874
 :NAME :SAN_RDPM_UA_S_RATE_CARD_JOB_TITLE
 :COMMENT "Job Title"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_SOURCING_RATE_CARD
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_JOB_TITLES
)