
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310382203174
 :NAME :SAN_RDPM_UA_S_NOTIF_TYPE_BP
 :COMMENT "Notification Type - Business Partner"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"__USER_TABLE_SAN_RDPM_UT_SOURCING_REQUEST_NOTIFICATION\",\"Business Partner_\"+SAN_RDPM_UA_S_SOURCING_MESSAGE_ID,\"SAN_RDPM_UA_S_NOTIFICATION_TYPE\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)