
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310370705170
 :NAME :SAN_RDPM_UA_PRJ_UA_NAME_EXT_SOURCE
 :COMMENT "Name of External Source"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur.Project|
          :|Continuum.RDPM.Pharma.Project|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::_INF_PT_CBS3
)