
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310301766576
 :NAME :SAN_RDPM_UA_PEXP_LAST_MODIF_AUTHOR
 :COMMENT "Last Modification Date & Author"
 :DATASET 118081000141
 :FORMULA "LAST_MODIFICATION_DATE +\" By \"+ STRING_VALUE(\"USER\",LAST_MODIFICATION_USER, \"DESC\")"
 :NCLASS DOD:EXPENDITURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)