
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310301761776
 :NAME :SAN_RDPM_UA_USER_B_NOTIF_SEND
 :COMMENT "Has Timecard User been notified?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS GENERIC-IO:OPX2-USER
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)