
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310382086774
 :NAME :SAN_RDPM_UA_S_SOURCING_SKILL_ASSIGNEMENT
 :COMMENT "Skill assignment"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_JOB_TITLES
)