
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310382089174
 :NAME :SAN_RDPM_UA_D_SOURCING_START_BILL_MANAGEMENT
 :COMMENT "Start date of billing Management"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)