
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310372207141
 :NAME :SAN_UA_RDPM_S_PARENTS_ONB
 :COMMENT "Parents ONB"
 :DATASET 118081000141
 :FORMULA "IF LEVEL>1 THEN 	LIST_MERGE(PRINT_NUMBER(ONB,\"####\"),WBS_ELEMENT.SAN_UA_RDPM_S_PARENTS_ONB) ELSE 	PRINT_NUMBER(ONB,\"####\") FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)