
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310372210074
 :NAME :SAN_RDPM_UA_S_NEXT_STATUS_REQUESTOR
 :COMMENT "Sourcing Tool - Next status requestor"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"__USER_TABLE_SAN_RDPM_UT_SOURCING_REQUEST_NEXT_STATUS\",\"SAN_RDPM_UA_S_STATUS_SOURCING_TYPE=\\\"\"+SAN_RDPM_UA_S_SOURCING_TYPE+\"\\\" AND SAN_RDPM_UA_S_SOURCING_TOOL_CUR_STATUS=\\\"\"+SAN_RDPM_UA_S_SOURCING_STATUS+ \"\\\" AND SAN_RDPM_UA_S_SOURCING_TOOL_ROLE=\\\"Requestor\\\"\",\"SAN_RDPM_UA_S_SOURCING_TOOL_NEXT_STATUS\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)