
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310372084910
 :NAME :SAN_RDPM_UA_S_COUNTRY_OF_SITE
 :COMMENT "Country of site"
 :DATASET 118081000141
 :FORMULA "_RM_REVIEW_RA_LOCATION.SAN_RDPM_UA_COUNTRY.DESC"
 :NCLASS DOD:EXPENDITURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)