
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310382169074
 :NAME :SAN_RDPM_UA_B_PARENT_SOURCING_REQ
 :COMMENT "Parent sourcing request"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_RES_ENT_TYP IN (\"Service\",\"Team\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)