
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310375711941
 :NAME :SAN_RDPM_UA_S_SOURCING_REQUEST_PREFIX
 :COMMENT "Sourcing Request Prefix"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "\"EC-\"+SAN_UA_RDPM_RES_SERV_FIN_CODE+\"A-\"+SUBSTRING(PRINT_NUMBER(YEAR_NUMBER($DATE_OF_THE_DAY),\"####\"),2,4)"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)