
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310370704870
 :NAME :SAN_UA_PC_NAME_EXT_SOURCE
 :COMMENT "Name of External Source"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_PROJECT_CODES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::_INF_PT_CBS3
)