
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310382088674
 :NAME :SAN_RDPM_UA_N_SOURCING_MANAGEMENT_FEES
 :COMMENT "Monthly Management fees (KLC)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)