
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310382084874
 :NAME :SAN_RDPM_UA_S_SOURCING_MANAGEMENT_CENTER
 :COMMENT "Management Center (FIRST)"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_MANAGEMENT_CENTER
)