
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310375286510
 :NAME :SAN_RDPM_UA_B_ROLE_PO_NOTIF
 :COMMENT "Send Project Objectives notification?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_ROLE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)