
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310301748076
 :NAME :SAN_RDPM_UA_PH_LAST_MODIF_AUTHOR
 :COMMENT "Last Modification Date & Author"
 :DATASET 118081000141
 :FORMULA "LAST_MODIFICATION_DATE +\" By \"+ STRING_VALUE(\"USER\",LAST_MODIFICATION_USER, \"DESC\")"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)