
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310382205774
 :NAME :SAN_RDPM_UA_B_SOURCING_CONTRACT_TYPE
 :COMMENT "Sourcing contract type?"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_RES_CTR_TYP
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)