
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310376206173
 :NAME :SAN_RDPM_UA_TM_COUNTRY
 :COMMENT "Country"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_TRANSLATOR_METRICS
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RWE_UT_COUNTRY
)