
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310382090474
 :NAME :SAN_RDPM_UA_S_SOURCING_FIN_TERRITORY_CODE
 :COMMENT "Financial Territory Code"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_S_SOURCING_MANAGEMENT_CENTER.SAN_RDPM_UA_S_FIN_TERRITORY_CODE"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)