
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310376206473
 :NAME :SAN_RDPM_UA_TM_WBS_TYPE
 :COMMENT "Activity Type"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_TRANSLATOR_METRICS
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::WBS_TYPE
)