
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 310372224974
 :NAME :SAN_RDPM_UA_B_SOURCING_REQUEST
 :COMMENT "Sourcing Request"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_B_INSOURCING_REQUEST"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)