
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316632371776
 :NAME :SAN_RDPM_UA_ACT_MAIN_CHG_ASSUMP_VS_LST_APPR_REF
 :COMMENT "Main changes on assumptions vs latest approved reference"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:MULTI-LINE-STRING
)