
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316665525974
 :NAME :SAN_RDPM_UA_S_ACT_TYPES
 :COMMENT "Activity Types"
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"USER_ATTRIBUTE_INVERSE_SAN_RDPM_UA_S_CLIN_MS_RULE.__USER_TABLE_SAN_RDPM_UT_MAP_CLIN_MS_ACT_TYPE\",\"\",\"SAN_RDPM_UA_S_ACT_TYPE_DATE\")"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CLIN_MS_RULES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)