
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316634359482
 :NAME :SAN_RDPM_UA_S_TYPE_PRODUCT_DESC
 :COMMENT "Type of product description"
 :DATASET 118081000141
 :FORMULA "LIST_REMOVE_DUPLICATES(DESC+\" / \"+SAN_RDPM_UA_S_LIST_DEMAND_UNIT+\" / \"+SAN_RDPM_UA_MANUF_PROCESS+\" / \"+SAN_RDPM_UA_ACT_STOCKAGE_CONDITIONS)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)