
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316646750682
 :NAME :SAN_RDPM_UA_NP_PHARMA_VAR_ANAL_F
 :COMMENT "Variance analysis (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_NP_PHARMA_VAR_ANAL<>\"\" THEN SAN_RDPM_UA_NP_PHARMA_VAR_ANAL ELSE WBS_ELEMENT.SAN_RDPM_UA_NP_PHARMA_VAR_ANAL FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)