
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316643417082
 :NAME :SAN_RDPM_UA_S_DELTA_YEARLY_BASELINE_2
 :COMMENT "Delta Yearly - baseline 2"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_D_PHARMA_YEARLY_DATE<>'-1' AND SAN_RDPM_UA_D_BL2_FD<>'-1' THEN PRINT_DURATION(SAN_RDPM_UA_DU_DELTA_YEARLY_BASELINE_2,\"MD\") ELSE \"\" FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)