
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316651340710
 :NAME :SAN_UA_RDPM_RES_GE_TYP
 :COMMENT "Global entity"
 :DATASET 118081000141
 :FORMULA "IF ( SAN_UA_RDPM_RES_TYP_PHAR  or SAN_UA_RDPM_RES_TYP_PAST  )  AND SAN_RDPM_UA_RES_ENT_TYP=\"Global entity\" THEN NAME ELSE IF SAN_RDPM_UA_RES_ENT_TYP<>\"Global entity\" THEN ELEMENT_OF.SAN_UA_RDPM_RES_GE_TYP FI FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)