
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316642422241
 :NAME :SAN_RDPM_UA_N_VACC_MAN_MONTH
 :COMMENT "Total Load (Man Month)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "TOTAL_LOAD * 12 / IF _RM_REVIEW_RA_LOCATION.SAN_RDPM_UA_NB_DAYS_FOR_VACC_FTE <> 0 THEN _RM_REVIEW_RA_LOCATION.SAN_RDPM_UA_NB_DAYS_FOR_VACC_FTE ELSE OC.SAN_RDPM_CS_DEFAULT_FTE_DAYS_NUMBER FI"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)