
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316662545410
 :NAME :SAN_RDPM_UA_S_PORTFOLIO_ID
 :COMMENT "Portfolio ID"
 :DATASET 118081000141
 :FORMULA "IF LEVEL>2 THEN SAN_RDPM_UT_PM_PRJ_PORT.SAN_RDPM_UA_S_PORTFOLIO_ID+\".\"+NAME ELSE NAME  FI"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PM_PRJ_PORT
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)