
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316645374682
 :NAME :SAN_RDPM_UA_S_PROJECT_STATUS_DETAILED
 :COMMENT "Project Status Detailed"
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_UA_PRJ_PRJ_STATUS"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)