
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316665568374
 :NAME :SAN_RDPM_UA_S_DATE_SLOT
 :COMMENT "Date Slot"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CLIN_MS_RULES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :DATE_SLOT
)