
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316645526610
 :NAME :SAN_RDPM_UA_N_A_SET_UP_COSTS
 :COMMENT "A-Set up costs"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN (OC.SAN_RDPM_CS_VACC_CRF_PAGE_RATE * SAN_RDPM_UA_ACT_NB_UNIQUE_CRF_PAGE_SUBJECT_F ) ELSE WBS_ELEMENT.SAN_RDPM_UA_N_A_SET_UP_COSTS FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)