
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316645494482
 :NAME :SAN_RDPM_UA_S_INDIC_SHORTNAME_F
 :COMMENT "Indication Shortname (F)"
 :DATASET 118081000141
 :FORMULA "IF (SAN_RDPM_UA_B_IS_AN_INDICATION OR WBS_TYPE=\"OTHER\") THEN SAN_RDPM_UA_S_INDIC_SHORTNAME ELSE WBS_ELEMENT.SAN_RDPM_UA_S_INDIC_SHORTNAME_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)