
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316643322382
 :NAME :SAN_RDPM_UF_OBS_DG12
 :COMMENT "DG12?"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"RESPONSIBILITY\",OC.SAN_RDPM_CS_OBS_DG12)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)