
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316645566882
 :NAME :SAN_RDPM_UA_S_CSU_PROVIDER
 :COMMENT "CSU Provider"
 :DATASET 118081000141
 :FORMULA "IF SPJ.DESC=\"Geographic area\" then SAN_RDPM_UA_ACT_PROVIDER  ELSE \"\" FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)