
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316650503210
 :NAME :SAN_RDPM_UA_D_PF_CONCEPT_PROTOCOL_W_AND_A
 :COMMENT "Concept Protocol Writing & Approval"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN ITER_DATE_MIN(\"ALL_CHILDREN\",\"  BELONGS(\\\"WBS_TYPE\\\",OC.SAN_RDPM_CS_S_AT_V_S_CPROT)\" ,\"PF\") ELSE '-1' FI   "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)