
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316645292182
 :NAME :SAN_RDPM_UA_B_IS_BIO_RESOURCE
 :COMMENT "is BIO Resource?"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"OBS_ELEMENT\",OC.SAN_RDPM_CS_OBS_BIO)"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)