
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316646087770
 :NAME :SAN_RDPM_UA_RATE_OVERHEAD
 :COMMENT "Rate Overhead"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_COUNTRY
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)