
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316645372882
 :NAME :SAN_RDPM_UA_S_INDICATION_OWNER_F
 :COMMENT "Indication Owner (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_B_IS_AN_INDICATION THEN OBS_ELEMENT ELSE WBS_ELEMENT.SAN_RDPM_UA_S_INDICATION_OWNER_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)