
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316632373576
 :NAME :SAN_RDPM_UA_ACT_MARKET_POSITION_RATIONAL
 :COMMENT "Market positioning rational"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:MULTI-LINE-STRING
)