
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316669529176
 :NAME :SAN_RDPM_UA_PRJ_MR_QUALI_INFO_INIT
 :COMMENT "MR Qualitative info initiated"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)