
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316632370876
 :NAME :SAN_RDPM_UA_ACT_ASSUMP_SCENARIO_DESC
 :COMMENT "Assumptions - Scenario description"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:MULTI-LINE-STRING
)