
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316669525876
 :NAME :SAN_UA_MR_KEY_DECISION_DATE
 :COMMENT "Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_MR_KEY_DECISIONS_TAKEN
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)