
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316643338282
 :NAME :SAN_RDPM_UA_D_POCC
 :COMMENT "Proof of commercial concept"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF LEVEL=2 THEN ITER_DATE_MIN(\"ALL_CHILDREN\",\"(BELONGS(\\\"WBS_TYPE\\\", \\\"Proof of Commercial Concept\\\" )) AND PF<>-1\",\"PF\") ELSE '' FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)