
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316649533274
 :NAME :SAN_RDPM_UA_S_TIMELINE_ACT_COLOR
 :COMMENT "Vaccine Timeline Activity Color"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF FILE._ROA_NF_B_ROADMAP_PROJECT THEN  	\"GREY\" ELSE 	IF SAN_RDPM_UA_B_YEARLY_EXIST=TRUE AND SAN_RDPM_UA_D_VACCINE_YEARLY_BASELINE_DATE<>-1 THEN  			 		IF (YEAR_NUMBER(SAN_RDPM_UA_D_VACCINE_YEARLY_BASELINE_DATE)=YEAR_NUMBER($DATE_OF_THE_DAY) AND (DIFF_DATE(SAN_RDPM_UA_D_VACCINE_YEARLY_BASELINE_DATE,SAN_RDPM_UA_D_VACCINE_MILESTONE_DATE,\"\")<'-28d')) THEN 			\"GREEN\"  	 			 		ELSE  				 			IF (YEAR_NUMBER(SAN_RDPM_UA_D_VACCINE_YEARLY_BASELINE_DATE)=YEAR_NUMBER($DATE_OF_THE_DAY) AND (DIFF_DATE(SAN_RDPM_UA_D_VACCINE_YEARLY_BASELINE_DATE,SAN_RDPM_UA_D_VACCINE_MILESTONE_DATE,\"\")>'28d')) THEN 	 					 				\"RED\"  	 				 			ELSE  					 				IF (YEAR_NUMBER(SAN_RDPM_UA_D_VACCINE_YEARLY_BASELINE_DATE)<>YEAR_NUMBER($DATE_OF_THE_DAY) AND (DIFF_DATE(SAN_RDPM_UA_D_VACCINE_YEARLY_BASELINE_DATE,SAN_RDPM_UA_D_VACCINE_MILESTONE_DATE,\"\")<'-90d')) THEN 	 						 					\"GREEN\" 	 					 				ELSE  						 					IF (YEAR_NUMBER(SAN_RDPM_UA_D_VACCINE_YEARLY_BASELINE_DATE)<>YEAR_NUMBER($DATE_OF_THE_DAY)AND (DIFF_DATE(SAN_RDPM_UA_D_VACCINE_YEARLY_BASELINE_DATE,SAN_RDPM_UA_D_VACCINE_MILESTONE_DATE,\"\")>'90d')) THEN  							 						\"RED\" 						 					ELSE 							 						\"BLUE\" 						 					FI  					 				FI  				 			FI  			 		FI  	ELSE 		\"10061705\" 	FI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)