
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316632387476
 :NAME :SAN_RDPM_UA_ACT_EXPRESSION_SYSTEM_F
 :COMMENT "Expression system (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_ACT_EXPRESSION_SYSTEM <> \"\" THEN SAN_RDPM_UA_ACT_EXPRESSION_SYSTEM ELSE WBS_ELEMENT.SAN_RDPM_UA_ACT_EXPRESSION_SYSTEM_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)