
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316634249174
 :NAME :SAN_RDPM_UA_S_REQUESTOR_NAME
 :COMMENT "Requestor Name"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"USER\",SAN_RDPM_RO_SOURCING_REQUESTOR,\"DESC\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)