
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316657237469
 :NAME :SAN_RDPM_UA_B_EQUATION_FILTER_PHARMA
 :COMMENT "Equation project filter for Pharma"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "LIST_FIND(\"PHARMA\",OC.SAN_RDPM_CS_EQUA_BATCH_SCOPE) AND NOT (PF<$DATE_OF_THE_DAY OR SAN_RDPM_UA_PRJ_PRJ_STATUS IN (\"Completed inactive\",\"Stopped inactive\"))"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)