
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316645508010
 :NAME :SAN_RDPM_UA_B_IS_LAST
 :COMMENT "Is Last? "
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_DA_B_IS_LAST"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)