
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316657236769
 :NAME :SAN_RDPM_UA_B_EQUATION_FILTER_PASTEUR
 :COMMENT "Equation project filter for Vaccines"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "LIST_FIND(\"PASTEUR\",OC.SAN_RDPM_CS_EQUA_BATCH_SCOPE) AND  NOT (SAN_RDPM_UA_PRJ_PRJ_STATUS IN (\"Completed inactive\",\"Stopped inactive\"))"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)