
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316643080682
 :NAME :SAN_RDPM_UA_S_LIST_DEMAND_UNIT
 :COMMENT "List of Demand unit"
 :DATASET 118081000141
 :FORMULA "LIST_REMOVE_DUPLICATES((LIST_COLLECT(\"EXPENDITURES\",\"ACTIVITY.SAN_RDPM_UA_S_ACT_DMM\",\"TYPE\")))"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)