
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316662547141
 :NAME :SAN_UA_RDPM_RES_PLATFORM
 :COMMENT "Platform"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_RES_ENT_TYP=\"Platform\" THEN      name  ELSE IF SAN_RDPM_UA_RES_ENT_TYP<>\"Platform\" THEN      ELEMENT_OF.SAN_UA_RDPM_RES_PLATFORM FI FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)