
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316643054382
 :NAME :SAN_RDPM_UA_B_PHASE_WBS
 :COMMENT "Located in Phase"
 :DATASET 118081000141
 :FORMULA "IF _PAC_NF_B_PHASE THEN WBS_TYPE ELSE WBS_ELEMENT.SAN_RDPM_UA_B_PHASE_WBS FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)