
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 316643322682
 :NAME :SAN_UA_B_IS_ACT_DG12
 :COMMENT "? is there a DG12 activity"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN ITER_BOOLEAN_THERE_IS_ONE(\"ALL CHILDREN\",\"SAN_RDPM_UF_OBS_DG12\") else WBS_ELEMENT.SAN_UA_B_IS_ACT_DG12 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)