
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317256032674
 :NAME :SAN_RDPM_UA_B_PHARMA_RULE
 :COMMENT "Pharma Rule"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_S_APPLY_TO IN (\"COMMON\",\"PHARMA\")"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CLIN_MS_RULES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)