
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317297287410
 :NAME :SAN_RDPM_UA_S_LIST_REGIONS_VACC_DESC_HOURS
 :COMMENT "List of Vaccines Regions (desc)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_S_LIST_REGIONS_VACC_DESC"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)