
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317295639669
 :NAME :SAN_RDPM_UA_AH_WORKING_MD
 :COMMENT "Working MD"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "SAN_RDPM_CF_AH_PERIOD - SAN_RDPM_CF_AH_NON_WK_PERIOD "
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)