
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317296298376
 :NAME :SAN_RDPM_UA_S_DISPATCH_WBS_TYPE
 :COMMENT "Dispatch activity types"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::WBS_TYPE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::...WBS_TYPE
)