
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317274579641
 :NAME :SAN_RDPM_UA_B_RES_FILT_ENTRIES_EXISTS
 :COMMENT "Filter for report Resource Entries/Exits"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "FROM(OC.GEN_HEADER_FILT_RES) AND _RM_NF_B_RES_IS_MANAGED"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)