
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317268860341
 :NAME :SAN_RDPM_UA_PRJ_RND_PRJ_VAC
 :COMMENT "R&D Project Vaccines Project"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"PROJECT_TYPE\",\"Continuum.RDPM.Pasteur.Project\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)