
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317296235441
 :NAME :SAN_UA_RDPM_S_COST_METRIC_UNIT
 :COMMENT "Cost Metric Unit"
 :DATASET 118057330253
 :NCLASS DOD:EXPENDITURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)