
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317241679210
 :NAME :SAN_RDPM_UA_OC_S_STATE
 :COMMENT "State"
 :DATASET 118081000141
 :DEFAULT-VALUE "Active"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :POSSIBLE-VALUES "Consolidated portfolio,Project template,Simulation,Can be consolidated,Active,Closed"
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)