
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317268934141
 :NAME :SAN_RDPM_UA_S_PRJ_STATUS
 :COMMENT "Project Status"
 :DATASET 118081000141
 :FORMULA "PROJECT._STA_RA_PRJ_STATUS  "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)