
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317296823176
 :NAME :SAN_RDPM_UA_SPONSOR_CODE
 :COMMENT "Sponsor Code"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_UT_SPONSOR
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)