
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317250052210
 :NAME :SAN_RDPM_UA_S_STUDY_MANAGER_SITE
 :COMMENT "Study Manager Site"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"USER\",SAN_RDPM_RO_STUDY_MANAGER,\"SAN_UA_S_AD_SITE\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)