
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317296823476
 :NAME :SAN_RDPM_UA_ACT_STUDY_SPONSOR_CODES
 :COMMENT "Study Sponsor Codes"
 :DATASET 118081000141
 :FORMULA "LIST_REMOVE(\"\",LIST_REMOVE_DUPLICATES(String_value(\"__USER_TABLE_SAN_UT_SPONSOR\", SAN_RDPM_UA_ACT_STUDY_SPONSOR_NAME, \"SAN_RDPM_UA_SPONSOR_CODE\")))"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)