
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317280946573
 :NAME :SAN_UA_PC_ORIGIN_OF_NME
 :COMMENT "Origin of NME"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_PROJECT_CODES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_ORIGIN_OF_NME
)