
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317275020182
 :NAME :SAN_UA_B_IS_ACT_BIO
 :COMMENT "? is there a BIO activity"
 :DATASET 118081000141
 :FORMULA "ITER_BOOLEAN_THERE_IS_ONE(\"CHILDREN\",\"SAN_RDPM_UF_OBS_BIO\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)