
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317241605110
 :NAME :SAN_UA_RDPM_S_PROT_BRD
 :COMMENT "GMP products & documents"
 :DATASET 118081000141
 :FORMULA "if  WBS_TYPE.SAN_UA_RDPM_S_ACT_PROT_BRD <> \"\" then WBS_TYPE.SAN_UA_RDPM_S_ACT_PROT_BRD FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_ACT_PROT_BRD
)