
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317253200910
 :NAME :SAN_RDPM_UA_B_REPORTING_PHASE
 :COMMENT "Is a Reporting Phase"
 :DATASET 118081000141
 :FORMULA "IF WBS_TYPE.SAN_RDPM_UA_ACT_B_REPORTING_PHASE THEN TRUE ELSE FALSE FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)