
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317253242976
 :NAME :SAN_RDPM_UA_ACT_N_PRIORITY_F
 :COMMENT "Priority (F)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "PROJECT._PAC_AA_N_PRIO"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)