
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317256068674
 :NAME :SAN_RDPM_UA_D_ISTORE_AS
 :COMMENT "iStore Actual Start"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)