
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317250365241
 :NAME :SAN_RDPM_UA_B_IGNORE_AT_ORDER
 :COMMENT "Ignore activity types order"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CLIN_MS_RULES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)