
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317253297976
 :NAME :SAN_RDPM_UA_ACT_B_DISPLAYED_MR_TIMELINE
 :COMMENT "Displayed in Stage Progression and Key Milestone"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)