
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317296853476
 :NAME :SAN_RDPM_UA_ACT_DELAY_PS_REF_BASELINE2
 :COMMENT "Delay Planned Start vs Ref#2"
 :DATASET 118081000141
 :DEFAULT-VALUE 0
 :FORMULA "IF OC.DATE2<>\"\" THEN  DIFF_DATE(DATE_VALUE(\"ACTIVITY\",ID,\"SD_\"+OC.DATE2),PS,CAL) ELSE -1 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME:DURATION
)