
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317274576377
 :NAME :SAN_RDPM_UA_PH_TRANSLATOR_COUNTRY
 :COMMENT "Translator Country"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RWE_UT_COUNTRY
)