
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317256034474
 :NAME :SAN_RDPM_UA_S_PHARMA_ISTORE_CODE_END_MS
 :COMMENT "iStore Code End [Pharma]"
 :DATASET 118081000141
 :FORMULA "WBS_TYPE.SAN_RDPM_UA_S_CLIN_MS_END_PHARMA +\"_\"+SAN_RDPM_UA_S_IMPACT_CODE"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)