
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317291676241
 :NAME :SAN_RDPM_UA_S_COST_ACCOUNT_MAIN
 :COMMENT "Cost account main"
 :DATASET 118081000141
 :FORMULA "IF IS_A_LEAF THEN COST_ACCOUNT.DESC FI"
 :NCLASS DOD:CBS-NODE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)