
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317296295210
 :NAME :SAN_RDPM_UA_B_AUTO_STATE_TC
 :COMMENT "Automatically open/close to timecard?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::WBS_TYPE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)