
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317296235941
 :NAME :SAN_UA_RDPM_N_COST_METRIC_QTY
 :COMMENT "Cost Metric Value"
 :DATASET 118057330253
 :DEFAULT-VALUE 0.0d0
 :NCLASS DOD:EXPENDITURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)