
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317253107141
 :NAME :SAN_RDPM_UA_S_APPLY_TO
 :COMMENT "Apply To"
 :DATASET 118081000141
 :FORMULA "IF FILE=\"SAN_CF_RDPM_COMMON_DATA\" THEN  	\"COMMON\" ELSE 	IF FILE=\"SAN_CF_RDPM_COMMON_DATA_PHARMA\" THEN 		\"PHARMA\" 	ELSE 		IF FILE=\"SAN_CF_RDPM_COMMON_DATA_VACCINES\" THEN 			\"VACCINES\" 		FI 	FI FI"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CLIN_MS_RULES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)