
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317268445741
 :NAME :SAN_RDPM_UA_S_TARGET_POP_ACT
 :COMMENT "Target Population Activity"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_TARGET_POP
 :PTYPES (:|Continuum.RDPM.Pasteur.Indication|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE KERNEL-ORDO:WORK-STRUCTURE
)