
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317296297276
 :NAME :SAN_RDPM_UA_S_APPLY_TO_STUDY_TYPE
 :COMMENT "Apply to study type"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::WBS_TYPE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::...WBS_TYPE
)