
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317274682682
 :NAME :SAN_RDPM_UA_T_VARIANCE_ANALYSIS_BASELINE2
 :COMMENT "Variance analysis Baseline 2"
 :DATASET 118081000141
 :FORMULA "REFERENCE_STRING_VALUE(\"ACTIVITY\",ID,\"SAN_RDPM_UA_NP_PHARMA_VAR_ANAL\" ,OC.DATE2)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)