
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317292198410
 :NAME :SAN_RDPM_UA_EXPERIMENTAL_PERIOD_END
 :COMMENT "Experimental period end"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN ITER_DATE_MAX(\"ALL_CHILDREN\",\"BELONGS(\\\"WBS_TYPE\\\",OC.SAN_RDPM_CS_AT_IN_LIFE_PERIOD)\",\"PF\") FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)