
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317275019082
 :NAME :SAN_RDPM_UF_OBS_BIO
 :COMMENT "BIO?"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"RESPONSIBILITY\",OC.SAN_RDPM_CS_OBS_BIO) or BELONGS(\"RESPONSIBILITY\",\"JA,JE,DF\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)