
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317253155377
 :NAME :SAN_RDPM_UA_COST_ACCOUNT
 :COMMENT "Cost account"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_STUDY_CURRENCY_EXP
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE DOD:CBS-NODE
)