
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317268933841
 :NAME :SAN_RDPM_UA_S_PRJ_PROJECT_NAME
 :COMMENT "Project Name"
 :DATASET 118081000141
 :FORMULA "PROJECT.NAME "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)