
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317271657382
 :NAME :SAN_UA_B_CSO_RESOURCE
 :COMMENT "CSO/EGDS?"
 :DATASET 118081000141
 :FORMULA "RES. SAN_RDPM_UA_B_IS_CSO_RESOURCE"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)