
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317295826569
 :NAME :SAN_RDPM_UA_AH_DIRECT_MD
 :COMMENT "Direct MD (Actual)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "SAN_RDPM_UA_AH_WORKING_MD - SAN_RDPM_CF_AH_STD_WK_PERIOD"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)