
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317300318910
 :NAME :SAN_RDPM_UA_PRJ_ROOT_PRODUCT_CODE_F
 :COMMENT "All Root Products Codes (F)"
 :DATASET 118081000141
 :FORMULA "IF LEVEL = 1 THEN  LIST_REMOVE(\"\",LIST_REMOVE_DUPLICATES(LIST_COLLECT(\"ACTIVITIES\",\" LEVEL = 2 \",\"SAN_RDPM_DA_ALL_ROOT_PRODUCT_CODES\"))) FI"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)