
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317316902310
 :NAME :SAN_RDPM_UA_B_IS_STEP
 :COMMENT "Is a Step?"
 :DATASET 118081000141
 :FORMULA "WBS_TYPE.SAN_RDPM_UA_AT_B_IS_STEP"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)