
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317300733510
 :NAME :SAN_RDPM_UA_N_WEEK_NUMBER_OF_PF
 :COMMENT "Week # of planned finish"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "WEEK_NUMBER(PF)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)