
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317326316469
 :NAME :SAN_RDPM_UA_AH_PCT_DIRECT_ACT
 :COMMENT "% Direct (Actual)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF SAN_RDPM_UA_AH_WORKING_MD=0 THEN 0 ELSE 100* SAN_RDPM_UA_AH_DIRECT_MD / SAN_RDPM_UA_AH_WORKING_MD FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)