
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317320366441
 :NAME :SAN_RDPM_UA_B_IS_A_IPSO
 :COMMENT "Is IPSO?"
 :DATASET 118081000141
 :FORMULA "TYPE in (\"IPSO 1\",\"IPSO 2\")"
 :NCLASS DOD:EXPENDITURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)