
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317320318573
 :NAME :SAN_RDPM_UF_FF_S_LIST_OF_PROJECTS
 :COMMENT "List of Projects"
 :DATASET 118081000141
 :FORMULA "LIST_REMOVE(\"\",LIST_COLLECT(\"_FF_REL_PROJECT\",\"SAN_RDPM_UA_PRJ_RND_PRJ_VAC\",\"SAN_UA_RWE_PROJECT_CODE_PRIME\")) "
 :NCLASS TEMP-TABLE::_FF_PT_FAVOR_FILTERS
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)