
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317316508074
 :NAME :SAN_RDPM_UA_OC_D_ATS_SD
 :COMMENT "Activity Tracking Statistics - Start Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)