
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317303600310
 :NAME :SAN_RDPM_UA_S_SCOPE
 :COMMENT "Scope"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_RES_CTR_TYP =\"CONTS\" THEN \"I\" ELSE \"YES\" FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)