
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317324395610
 :NAME :SAN_PC_UA_S_REL_COUNTRY_GROUP
 :COMMENT "Country Group"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_RELATION_COUNT_GROUP
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_COUNTRY_GROUPS
)