
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317323139374
 :NAME :SAN_RDPM_UA_S_PACK_LOAD_IMPORT_ERROR
 :COMMENT "Import error"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PACK_LOAD_IMPORT
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:MULTI-LINE-STRING
)