
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317316512074
 :NAME :SAN_RDPM_UA_OC_D_ATS_ED_CALC
 :COMMENT "Activity Tracking Satistics - End Date [Calc]"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF SAN_RDPM_UA_OC_D_ATS_ED<>-1 THEN  PERIOD_START(SAN_RDPM_UA_OC_D_ATS_ED,\"MONTH\",1) ELSE PERIOD_START($DATE_OF_THE_DAY,\"MONTH\",1) FI"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)