
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317312611173
 :NAME :SAN_RDPM_UA_AT_B_DISPLAY_IN_PRD_PLAN
 :COMMENT "Display in supply plan?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::WBS_TYPE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)