
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317320365841
 :NAME :SAN_RDPM_UA_B_RND_PHARMA_PROJECT
 :COMMENT "R&D Pharma Project ?"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_B_RND_PHARMA_ACTIVITY"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)