
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317320541841
 :NAME :SAN_UA_RDPM_N_NOA_CRO_FEES_SML_PRSIT_A2
 :COMMENT "SAN_UA_RDPM_N_NOA_CRO_FEES_SML_PRSIT_A2"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "(SAN_RDPM_UA_N_SITE_FROM_STUDY/(4/4.33)*2)/10 * SAN_RDPM_UA_PRIMARY_PHASE_PERIOD"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)