
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317301284410
 :NAME :SAN_UA_RDPM_S_PROT_BRD_PARENT
 :COMMENT "Parent GMP products & documents"
 :DATASET 118081000141
 :FORMULA "SAN_UA_RDPM_S_PROT_BRD.SAN_RDPM_UT_ACT_PROT_BRD"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_ACT_PROT_BRD
)