
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317326317469
 :NAME :SAN_RDPM_UA_AH_DIRECT_MD_VAR
 :COMMENT "Direct MD (Var)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "SAN_RDPM_UA_AH_DIRECT_MD - SAN_RDPM_CF_AVAIL_PERIOD "
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)