
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317312612273
 :NAME :SAN_RDPM_UF_ACT_PRODUCT_MANUFACTURING_GROUP
 :COMMENT "Supply plan group (F)"
 :DATASET 118081000141
 :FORMULA "WBS_TYPE.SAN_RDPM_UA_AT_PRODUCT_MANUFACTURING_GROUP"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)