
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317323988482
 :NAME :SAN_RDPM_UA_B_DOSS_RCDC_PLANNED
 :COMMENT "Is there a DOSS-RCDC Resources planned?"
 :DATASET 118081000141
 :FORMULA "ITER_BOOLEAN_THERE_IS_ONE(\"ALLOCATIONS\",\"RES.SAN_RDPM_UA_B_IS_DOSS_RESOURCE and SKILLS=\\\"RCDC\\\"\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)