
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317324212182
 :NAME :SAN_RDPM_UA_N_TOTAL_MD_PLANNED_DOSS_RCDC
 :COMMENT "Total of planned man-day for DOSS-RCDC"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "ITER_NUMBER_SUM(\"ALLOCATIONS\",\"RES.SAN_RDPM_UA_B_IS_DOSS_RESOURCE and SKILLS=\\\"RCDC\\\"\",\"TOTAL_LOAD\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)