
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317303361510
 :NAME :SAN_UA_RDPM_ACT_S_STUDY_NAME
 :COMMENT "Study Name"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN NAME ELSE WBS_ELEMENT.SAN_UA_RDPM_ACT_S_STUDY_NAME FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)