
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317316595974
 :NAME :SAN_RDPM_OC_S_ATS_HEADCOUNT_FILTER
 :COMMENT "Activity Tracking Statistics - Headcount Filter"
 :DATASET 118081000141
 :DEFAULT-VALUE "Direct"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)