
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317316530474
 :NAME :SAN_RDPM_UA_N_ATS_NB_PERC_TC_INTEGRATED
 :COMMENT "% Integrated Timecards"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF SAN_RDPM_UA_N_ATS_NB_TC>0 THEN SAN_RDPM_UA_N_ATS_NB_TC_INTEGRATED/SAN_RDPM_UA_N_ATS_NB_TC FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pasteur| :|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)