
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317326316969
 :NAME :SAN_RDPM_UA_AH_PCT_DIRECT_VAR
 :COMMENT "% Direct (Var)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "SAN_RDPM_UA_AH_PCT_DIRECT_ACT - SAN_UA_RDPM_RES_PERC_DIRECT "
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)