
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317304655476
 :NAME :SAN_RDPM_UA_ACT_DISPLAY_MR_KEY_MILESTONE
 :COMMENT "Display in MR current year key milestones section?"
 :DATASET 118081000141
 :DEFAULT-VALUE T
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)