
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317326800169
 :NAME :SAN_RDPM_UA_AH_NON_DIRECT_MD
 :COMMENT "Standard MD (Actual)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "SAN_RDPM_CF_AH_STD_WK_PERIOD"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)