
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317320318873
 :NAME :SAN_RDPM_UA_FF_B_EXPORT_TO_DATAHUB
 :COMMENT "Export to Datahub?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_FF_PT_FAVOR_FILTERS
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)