
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317316521974
 :NAME :SAN_RDPM_UA_S_RES_PARENTS
 :COMMENT "Parents list ID"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"ALL_PARENTS\",TRUE,\"ID\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)