
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317316559974
 :NAME :SAN_RDPM_UA_B_ATS_PORTFOLIO
 :COMMENT "Activity Tracking Statistics Portfolio"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_FF_PT_FAVOR_FILTERS
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)