
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317316000476
 :NAME :SAN_RDPM_UA_OC_S_FTE_CATEGORY_FILTER
 :COMMENT "FTE Category Filter"
 :DATASET 118081000141
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)