
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317323976582
 :NAME :SAN_RDPM_UA_D_TASK_CURRENT_ACTUAL_DATE
 :COMMENT "Task Current date (AS or AF depending on task type)"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF GETINTERNALSTRINGVALUE(\"ACTIVITY\",ID,\"TASK_TYPE\") = \"END-MILESTONE\" THEN period_start(AF,\"Day\",-1) ELSE AS FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)