
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 317323993082
 :NAME :SAN_RDPM_UA_D_CMC_SIGN_OFF_DATE
 :COMMENT "CMC sign-off date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF SAN_RDPM_UA_B_DOSS_RCDC_PLANNED THEN (IF AF<>\"\" THEN AF ELSE PF FI) ELSE -1 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)