
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319708020410
 :NAME :SAN_RDPM_UA_AH_STUDY_GROUP
 :COMMENT "Study group (F)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_DA_ACT_STUDY_GROUP"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)