
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319715770382
 :NAME :SAN_RDPM_UA_MOVE_REASON_IN
 :COMMENT "In?"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_RES_MOV_REAS
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)