
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319705931910
 :NAME :SAN_RDPM_UA_PH_PROJECT_NAME
 :COMMENT "Project name"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_UA_RDPM_S_PROJECT_TC"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)