
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319705940010
 :NAME :SAN_RDPM_UA_PH_DEP_GROUPING
 :COMMENT "Department grouping (F)"
 :DATASET 118081000141
 :FORMULA "RES.SAN_RDPM_UA_RES_DEP_GRP"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)