
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319733097682
 :NAME :SAN_RDPM_UA_N_SUCCESS_RATE_LAST_QUATERLY
 :COMMENT "Success Rate last Quaterly baseline"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "REFERENCE_NUMBER_VALUE(\"ACTIVITY\",ID,\"SAN_RDPM_UA_N_SR\",OC.SAN_RDPM_CS_LAST_QUATERLY_PHARMA)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)