
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319706806210
 :NAME :SAN_RDPM_UA_ACT_N_NB_COUNT_LAT
 :COMMENT "Number of Countries LAT"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY  THEN ITER_NUMBER_SUM(\"ALL_CHILDREN\",\"SAN_RDPM_UA_B_IS_A_COUNTRY AND SAN_UA_RDPM_PV_REG_VACC=OC.SAN_RDPM_CS_LATIN_AMERICA_VACC_REG_CODE\",\"1\") ELSE 0 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)