
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319708018610
 :NAME :SAN_RDPM_UA_AH_PROJECT_NAME
 :COMMENT "Project name"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_UA_RDPM_S_PROJECT_TC"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)