
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319710964782
 :NAME :SAN_RDPM_UA_S_PH_ROOT_PROJECT_DESC
 :COMMENT "Project description (F)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_S_ROOT_PROJECT_DESC"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)