
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319708023610
 :NAME :SAN_RDPM_UA_AH_COST_CENTER
 :COMMENT "Cost Center (F)"
 :DATASET 118081000141
 :FORMULA "RES.SAN_RDPM_UA_RES_COST_CENTER"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)