
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319705934110
 :NAME :SAN_RDPM_UA_PH_ACTIVITY_SITE
 :COMMENT "Site (Activity)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY._RM_REVIEW_RA_LOCATION "
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur| :|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)