
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319722229182
 :NAME :SAN_RDPM_UA_S_CLIN_INDICATION_COHORT_F
 :COMMENT "Cohort Clinical indication (F)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF BELONGS(\"WBS_TYPE\",OC.SAN_RDPM_CS_COHORT_AT) THEN SAN_RDPM_UA_CLIN_INDICATION ELSE WBS_ELEMENT.SAN_RDPM_UA_S_CLIN_INDICATION_COHORT_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)