
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319710963682
 :NAME :SAN_RDPM_UA_S_PH_STUDY_TYPE
 :COMMENT "Study type (F)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_UA_S_ACT_STUDY_TYPE"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)