
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319706638141
 :NAME :SAN_RDPM_UA_SITES_SUBJECTS_BB_SPLIT
 :COMMENT "Acivities on which split of sites/subjects for the BB will be done"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "SAN_UA_RDPM_S_CSU_REGION<>\"\" AND SAN_DA_ACT_B_IN_HUMAN"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)