
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319706751070
 :NAME :SAN_RDPM_UA_OC_KEY_MILESTONE_FUNCTION_FILTER
 :COMMENT "Key Milestone Function"
 :DATASET 118081000141
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE KERNEL-ORDO::...RESOURCE
)