
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319705935710
 :NAME :SAN_RDPM_UA_PH_ALL_ROOT_PRODUCT_CODE
 :COMMENT "All Root Product Codes (F)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_DA_ALL_ROOT_PRODUCT_CODES"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)