
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319722446382
 :NAME :SAN_RDPM_UA_B_IS_RTMED_RESOURCE
 :COMMENT "is RTMED Resource?"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"OBS_ELEMENT\",OC.SAN_RDPM_CS_OBS_RTMED)"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)