
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319710966082
 :NAME :SAN_RDPM_UA_D_M2_PS
 :COMMENT "PS Start Development - M2"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF LEVEL = 1 THEN ITER_DATE_MIN(\"ALL_CHILDREN\",\"?TASK and BELONGS(\\\"WBS_TYPE\\\",\\\"Start Development - M2\\\")\",\"PS\") ELSE SPJ.SAN_RDPM_UA_D_M2_PS FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)