
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319705930510
 :NAME :SAN_RDPM_UA_PH_PORTFOLIO_MAIN
 :COMMENT "Portfolio (Main)"
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_UA_PRTF_MAIN"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)