
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319736739182
 :NAME :SAN_RDPM_UA_S_ACT_LAST_MODIF_AUTHOR
 :COMMENT "Last Modification Date & Author"
 :DATASET 118081000141
 :FORMULA "LAST_MODIFICATION_DATE +\" By \"+ STRING_VALUE(\"USER\",LAST_MODIFICATION_USER, \"DESC\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur| :|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)