
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319708018010
 :NAME :SAN_RDPM_UA_AH_PORTFOLIO_MAIN
 :COMMENT "Portfolio (Main)"
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_UA_PRTF_MAIN"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)