
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319733394482
 :NAME :SAN_RDPM_UA_ACT_PLAN_SITE_COHORT
 :COMMENT "Planned sites cohorts"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "NUMBER_VALUE(\"ACTIVITY\",SYNCHRONIZE_WITH.SAN_UA_RDPM_ACT_S_COHORT_ID,\"SAN_RDPM_CF_COHORT_SITES\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)