
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319705943410
 :NAME :SAN_RDPM_UA_PH_PS
 :COMMENT "Planned Start (Activity)"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "ACTIVITY.PS"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)