
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319736800482
 :NAME :SAN_RDPM_UA_N_WEIGHT_PROPAGATED
 :COMMENT "Weighting propagation"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF WBS_TYPE.SAN_RDPM_UA_PHARMA_PROJECT_PHASE THEN WEIGHT ELSE WBS_ELEMENT.SAN_RDPM_UA_N_WEIGHT_PROPAGATED FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur| :|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)