
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319705939510
 :NAME :SAN_RDPM_UA_PH_BU
 :COMMENT "Business Unit (F)"
 :DATASET 118081000141
 :FORMULA "RES.SAN_UA_RDPM_RES_BU"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)