
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319723445582
 :NAME :SAN_RDPM_UA_S_INDICATION_SHORTNAME
 :COMMENT "Indication Shortname"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_PRJ_RND_IND THEN LIST_COLLECT(\"ACTIVITIES\",\"SAN_RDPM_UA_B_IS_AN_INDICATION\",\"SAN_RDPM_UA_S_INDIC_SHORTNAME\") ELSE \"\" FI"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)