
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319708059910
 :NAME :SAN_RDPM_UA_AH_INDICATION_DESC
 :COMMENT "Indication description (F)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_ACT_INDICATION_DESC"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)