
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319708019510
 :NAME :SAN_RDPM_UA_AH_ACTIVITY_SITE
 :COMMENT "Site (Activity)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY._RM_REVIEW_RA_LOCATION "
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)