
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319705933510
 :NAME :SAN_RDPM_UA_PH_ACTIVITY_NAME
 :COMMENT "Activity name"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.NAME"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)