
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319722444182
 :NAME :SAN_RDPM_UA_S_SITE_CSU_CLUSTER_DESC
 :COMMENT "CSU Cluster Description"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_COUNTRY.SAN_RDPM_UA_CTRY_CSU_CLUSTER.DESC"
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)