
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319706796010
 :NAME :SAN_RDPM_UA_S_LIST_COUNTRIES_GE
 :COMMENT "List of Countries GE"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY  THEN LIST_COLLECT(\"ALL_CHILDREN\",\"SAN_RDPM_UA_B_IS_A_COUNTRY AND SAN_UA_RDPM_PV_REG_VACC=OC.SAN_RDPM_CS_EUROPE_VACC_REG_CODE\",\"SAN_RDPM_UA_ACT_COUNT\") ELSE \"\" FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)