
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319708022210
 :NAME :SAN_RDPM_UA_AH_PF
 :COMMENT "Planned Finish (Activity)"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "ACTIVITY.PF"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)