
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319708021910
 :NAME :SAN_RDPM_UA_AH_PS
 :COMMENT "Planned Start (Activity)"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "ACTIVITY.PS"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)