
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319708021610
 :NAME :SAN_RDPM_UA_AH_ONB_ACT
 :COMMENT "ONB (act)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "NUMBER(ACTIVITY.ONB,\"####\")"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)