
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319705937310
 :NAME :SAN_RDPM_UA_B_PH_APAO_PROJ
 :COMMENT "APAO Project?"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_B_APAO_PROJ"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)