
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319706621570
 :NAME :SAN_RDPM_UA_OC_MILESTONE_TYPE
 :COMMENT "Milestone type"
 :DATASET 118081000141
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)