
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319722446682
 :NAME :SAN_UA_B_RTMED_RESOURCE
 :COMMENT "RTMED Planned hours?"
 :DATASET 118081000141
 :FORMULA "RES. SAN_RDPM_UA_B_IS_RTMED_RESOURCE"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)