
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319714024282
 :NAME :SAN_RDPM_UA_S_PROVIDER_ACTIVITY
 :COMMENT "Provider Activity"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_ACT_PROVIDER"
 :NCLASS DOD:EXPENDITURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)