
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319706621870
 :NAME :SAN_RDPM_UA_OC_DKM_TYPE
 :COMMENT "DKM Type of data"
 :DATASET 118081000141
 :DEFAULT-VALUE "Validated key milestones"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)