
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319733229782
 :NAME :SAN_UA_RDPM_ACT_S_COHORT_ID
 :COMMENT "Cohort identifier"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF BELONGS(\"WBS_TYPE\",OC.SAN_RDPM_CS_COHORT_AT) THEN ID ELSE WBS_ELEMENT.SAN_UA_RDPM_ACT_S_COHORT_ID FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)