
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319719723582
 :NAME :SAN_RDPM_UA_S_PROJECT_MOLECULE_TYPE
 :COMMENT "Project Entity Type"
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_UA_PROJ_MOLECULE_TYPE"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)