
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319715388082
 :NAME :SAN_RDPM_UA_S_ACT_PROJECT_RES_DESC
 :COMMENT "Project Responsibility Description"
 :DATASET 118081000141
 :FORMULA "PROJECT.SAN_RDPM_UA_S_PROJECT_RESP_DESC"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)