
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319708021310
 :NAME :SAN_RDPM_UA_AH_APAO_PROJ_LIST
 :COMMENT "APAO Project List"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_APAO_PROJ_LIST"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)