
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319708020110
 :NAME :SAN_RDPM_UA_AH_STAD_STAT
 :COMMENT "Study status (F)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_ACT_STAD_STAT"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)