
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 319705933210
 :NAME :SAN_RDPM_UA_PH_FUNC_WORKPACK
 :COMMENT "Functional Workpackage (F)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_UA_RDPM_ACT_S_FUNC_WORKPACK"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)