
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321190999241
 :NAME :SAN_RDPM_UA_S_PH_UNIQUE_IND_CODE_F
 :COMMENT "Unique Ind Code (F)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_S_UNIQUE_IND_CODE_F"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)