
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321196511041
 :NAME :SAN_RWE_UA_S_ESTRA_REG_COUNTRY_GROUP
 :COMMENT "Country groups"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_REGION
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::...__USER_TABLE_SAN_RDPM_UT_COUNTRY_GROUPS
)