
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321182527476
 :NAME :SAN_RDPM_UA_ACT_TIMELINE_INDICATION_STATUS_FILTER
 :COMMENT "Timeline Indication Status Filter"
 :DATASET 118081000141
 :FORMULA "IF FILE._ROA_NF_B_ROADMAP_PROJECT THEN TRUE ELSE SAN_RDPM_UF_ACT_BPS_INDICATION_STATUS=\"Ongoing\" FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)