
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321191045841
 :NAME :SAN_RDPM_UA_N_LINE_ID_ACTIVITY
 :COMMENT "Line identifier of the activity"
 :DATASET 118081000141
 :FORMULA "ACTIVITY._PM_DA_S_LINE_ID"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY_ACTIVITY
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)