
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321183387941
 :NAME :SAN_RDPM_UA_PH_OBS_ELEMENT
 :COMMENT "OBS Element"
 :DATASET 118081000141
 :FORMULA "RES.OBS_ELEMENT"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)