
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321190999141
 :NAME :SAN_RDPM_UA_S_AH_UNIQUE_IND_CODE_F
 :COMMENT "Unique Ind Code (F)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_S_UNIQUE_IND_CODE_F"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)