
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321178211277
 :NAME :SAN_RDPM_UA_S_FIRST_PRREP_PARENT_F
 :COMMENT "SAN_RDPM_UA_S_FIRST_PRREP_PARENT_F"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF WBS_TYPE = \"V_S_PRREP\" THEN ID ELSE WBS_ELEMENT.SAN_RDPM_UA_S_FIRST_PRREP_PARENT_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)