
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321196511541
 :NAME :SAN_RDPM_UA_S_VAC_REG_COUNTRY_GROUP
 :COMMENT "Country groups"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_VACC_REG
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::...__USER_TABLE_SAN_RDPM_UT_COUNTRY_GROUPS
)