
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321183995310
 :NAME :SAN_RDPM_UA_GCI_STUDY_STATUS
 :COMMENT "Study Status"
 :DATASET 118081000141
 :FORMULA "SAN_RDPM_UA_GCI_ASSAY_ACTIVITY.SAN_RDPM_UA_ACT_STAD_STAT"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY_ACTIVITY
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)