
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321181435241
 :NAME :SAN_UA_RDPM_FILTER_OPERATIONALITY
 :COMMENT "Operationality filter with default value"
 :DATASET 118081000141
 :DEFAULT-VALUE "Direct"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)