
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321182321010
 :NAME :SAN_RDPM_UA_S_PORTFOLIO_NOTIFICATION_USERS
 :COMMENT "Users for notifications"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PM_PRJ_PORT
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE GENERIC-IO::...OPX2-USER
)