
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321193791874
 :NAME :SAN_RDPM_UA_B_OC_BPAC_DISPLAY_BUDGET
 :COMMENT "Display budget?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "OC.SAN_RDPM_UA_S_OC_BPAC_FTE_CATEGORY =\"\" OR LIST_FIND(\"Budget\",OC.SAN_RDPM_UA_S_OC_BPAC_FTE_CATEGORY)"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)