
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321196862210
 :NAME :SAN_RDPM_UA_S_COMPLEX_FACTOR_CDL
 :COMMENT "Complexity factor CDL"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY  AND SAN_UA_ACT_B_CALCULATED_IN_HUMAN THEN san_pjs_get_wbs_form_number_value_on_object(ID,\"CLIN-CDM-CDL\",\"USER_ATTRIBUTE_SAN_UA_N_COMPLEXITY_FACTOR\") ELSE \"\" FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)