
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321181903610
 :NAME :SAN_RDPM_UA_B_NEW_PROJECT_CODE
 :COMMENT "Is a new project code?"
 :DATASET 118081000141
 :FORMULA "PERIOD_START($DATE_OF_THE_DAY,\"DAY\",-1)<SAN_RDPM_UA_D_PC_CREATION_DATE"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_UT_PROJECT_CODES
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)