
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321181904210
 :NAME :SAN_RDPM_UA_S_PORTFOLIO_NOTIFICATION_EMAILS
 :COMMENT "E-Mails of users"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"USER\",SAN_RDPM_UA_S_PORTFOLIO_NOTIFICATION_USERS,\"EMAIL_ADDRESS\")"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PM_PRJ_PORT
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)