
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321196510041
 :NAME :SAN_RDPM_UA_S_CSU_CLUST__COUNTRY_GROUP
 :COMMENT "Country groups"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CSU_CLUSTER
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::...__USER_TABLE_SAN_RDPM_UT_COUNTRY_GROUPS
)