
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321183410241
 :NAME :SAN_RDPM_UA_B_TC_VACCINES_MCQ_COMPLETE
 :COMMENT "Is Vaccine user and TC MCQ complete?"
 :DATASET 118081000141
 :FORMULA "(NOT USER_IN_GROUP($CURRENT_USER,\"O_GBU_VACCINES\")) OR EVALUATE_BOOLEAN_ON_OBJECT(\"_GUI_PT_MODULES\",\"TM\",\"SAN_RDPM_DA_B_MCQ_SCORE_REACHED\")"
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)