
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321199638374
 :NAME :SAN_RDPM_UA_B_CLINICAL_ACT
 :COMMENT "Clinical activity"
 :DATASET 118081000141
 :FORMULA "BELONGS(\"OBS_ELEMENT\",\"R&D - CLIN,R&D - GCD\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)