
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321183385176
 :NAME :SAN_RDPM_UA_ACT_YEARLY_LEAD_LAG_MONTH
 :COMMENT "Yearly Lead/Lag (Month)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF TASK_TYPE = \"Start milestone\" AND SAN_RDPM_UA_YEARLY_BL_START_DATE <> -1 THEN IF PS < SAN_RDPM_UA_YEARLY_BL_START_DATE THEN \"-\" FI+ print_number(TRUNCATE(ABS(SAN_RDPM_UA_YEARLY_BL_START_DATE-PS)/1440/30.416), \"####\")+\"m \"+ print_number(TRUNCATE(MOD(ABS(SAN_RDPM_UA_YEARLY_BL_START_DATE-PS)/1440,30.416)/7)+IF MOD(MOD(ABS(SAN_RDPM_UA_YEARLY_BL_START_DATE-PS)/1440,30.416),7)>=3 THEN 1 ELSE 0 FI, \"####\")+\"w\" ELSE IF SAN_RDPM_UA_YEARLY_BL_FINISH_DATE <> -1 THEN IF PF < SAN_RDPM_UA_YEARLY_BL_FINISH_DATE THEN \"-\" FI+ print_number(TRUNCATE(ABS(SAN_RDPM_UA_YEARLY_BL_FINISH_DATE-PF)/1440/30.416), \"####\")+\"m \"+ print_number(TRUNCATE(MOD(ABS(SAN_RDPM_UA_YEARLY_BL_FINISH_DATE-PF)/1440,30.416)/7)+IF MOD(MOD(ABS(SAN_RDPM_UA_YEARLY_BL_FINISH_DATE-PF)/1440,30.416),7)>=3 THEN 1 ELSE 0 FI, \"####\")+\"w\" FI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)