
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321178213841
 :NAME :SAN_RDPM_UA_S_CG_CSU_CLUSTER
 :COMMENT "CSU Cluster"
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"USER_ATTRIBUTE_INVERSE_SAN_RDPM_UA_S_CSU_CLUST__COUNTRY_GROUP.__USER_TABLE_SAN_RDPM_UT_CSU_CLUSTER\",\"TRUE\",\"ID\")"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_COUNTRY_GROUPS
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)