
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321261287382
 :NAME :SAN_RDPM_UA_S_GLOBAL_QC_ON_TIMECARD_ACCOUNT
 :COMMENT "Global QC on Timecard account"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_S_QC_ON_TIMECARD_ACCOUNT<>\"\" THEN SAN_RDPM_UA_S_QC_ON_TIMECARD_ACCOUNT ELSE \"x - Timecard account active\" FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)