
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321201640110
 :NAME :SAN_RDPM_UA_HES_PS
 :COMMENT "Planned Start (Activity)"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "ACTIVITY.PS"
 :NCLASS DOD::TIME-SYNTHESIS
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)