
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321289193482
 :NAME :SAN_RDPM_UA_S_EXTERNAL_PARTNER_WBS
 :COMMENT "External partner WBS"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)