
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321201384876
 :NAME :SAN_RDPM_UA_B_BASELINE_ADMIN_VACC_MONTHLY
 :COMMENT "Vaccines Monthly Baseline?"
 :DATASET 118081000141
 :FORMULA "_L1_AA_S_REF_TEMPLATE = OC.SAN_RDPM_CS_VACCINE_MONTHLY_BL_TEMPLATE AND LIST_FIND(_L1_AA_S_REF_PRJTYP, OC.SAN_RDPM_CS_VACCINE_MONTHLY_BL_DATASET)"
 :NCLASS TEMP-TABLE::_L1_PT_REF_ADMIN
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)