
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321257882682
 :NAME :SAN_RDPM_UA_B_IS_FINANCIAL_TASK
 :COMMENT "Is Financial Task?"
 :DATASET 118081000141
 :FORMULA "belongs(\"WBS_TYPE\",OC.SAN_RDPM_CS_AT_FIN_TASK)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)