
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321262062982
 :NAME :SAN_RDPM_UA_CSC_SSM_NAME_F
 :COMMENT "CSC-SSM Name (F)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"RESOURCE\",SAN_RDPM_UA_S_CSC_SSM_NAME_WBSF,\"SAN_RDPM_UA_S_RESOURCE_CONTRACT_TYPE\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)