
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321289174182
 :NAME :SAN_RDPM_UA_D_COMMITTEE_BASELINE_DATE
 :COMMENT "Committee Baseline Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "ITER_DATE_MAX(\"REFERENCES\",\"NAME=\\\"COMMITTEE\\\"\",\"AD\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)