
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321264116382
 :NAME :SAN_RDPM_UA_B_IS_CSCM_RESOURCE
 :COMMENT "is CSCM Resource?"
 :DATASET 118081000141
 :FORMULA "FROM(\"CSCM\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)