
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321221474241
 :NAME :SAN_RDPM_UA_OC_STUDY_CODE_CONSOLID
 :COMMENT "Study Code Consolidation filter"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)