
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321201640410
 :NAME :SAN_RDPM_UA_HES_PF
 :COMMENT "Planned Finish (Activity)"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "ACTIVITY.PF"
 :NCLASS DOD::TIME-SYNTHESIS
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
)