
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321203757210
 :NAME :SAN_RDPM_UA_CLIN_FTE_TRIAL_FILTER
 :COMMENT "Filter for clinical FTE by trial"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "FROM(\"R&D - GCD\") AND ID<>\"R&D - GCD\""
 :NCLASS KERNEL-ORDO:RESOURCE-SKILL
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)