
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321217970010
 :NAME :SAN_RDPM_UA_STUD_CODE_FILTER_CONTEXT
 :COMMENT "Study code context filter"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "FROM(OC.SAN_RDPM_UA_CO_STUDY_CODE)"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_PRIME_CODES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)