
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321217334741
 :NAME :SAN_RDPM_UA_CRITICAL_PATH_ACT_DESC
 :COMMENT "Activity description"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CRITICAL_PATH
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)