
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321292895182
 :NAME :SAN_RDPM_UA_D_RPP_US_APPROVAL_PF
 :COMMENT "Planned US Approval"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF WBS_TYPE IN(\"OL-b_SUBAPP\") THEN ITER_DATE_MIN(\"ALL_CHILDREN\",\"BELONGS(\\\"WBS_TYPE\\\",\\\"US approval\\\")\",\"PF\") ELSE -1 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)