
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321235429041
 :NAME :SAN_RDPM_UA_S_PH_RES_DPT_VAC
 :COMMENT "Department"
 :DATASET 118081000141
 :FORMULA "RES.SAN_UA_RDPM_RES_DEP"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)