
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321257384782
 :NAME :SAN_RDPM_UA_PRJ_PRODUCT_CODE_SYNONYM_F
 :COMMENT "Product Code Synonym (F)"
 :DATASET 118081000141
 :FORMULA "IF LEVEL = 1 THEN  LIST_REMOVE(\"\",LIST_REMOVE_DUPLICATES(LIST_COLLECT(\"ACTIVITIES\",\" LEVEL = 2 \",\"SAN_RDPM_UA_S_PRODUCT_CODE_SYNONYM\"))) FI"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)