
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321200769141
 :NAME :SAN_RDPM_UA_B_EQUA_BATCH_FILT
 :COMMENT "Equations batch filter "
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:OBS-NODE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)