
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321201663610
 :NAME :SAN_RDPM_UA_HES_ACTIVITY_TYPE
 :COMMENT "Activity type"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.WBS_TYPE"
 :NCLASS DOD::TIME-SYNTHESIS
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)