
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321289174682
 :NAME :SAN_RDPM_UA_S_COMMITTEE_BASELINE_DESC
 :COMMENT "Committee Baseline Description"
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"REFERENCES\",\"NAME=\\\"COMMITTEE\\\"\",\"DESC\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)