
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321201172041
 :NAME :SAN_RDPM_UA_CONTEXT_SITE_FILTER
 :COMMENT "Context site filter"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "FROM(OC.SAN_RDPM_UA_OC_S_SITE)"
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_LOCATIONS
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)