
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321221647141
 :NAME :SAN_RDPM_UA_LIST_SKILL_OF_LAST_GEN_RES
 :COMMENT "List of Primary Skill"
 :DATASET 118081000141
 :FORMULA "IF SAN_AL_RDPM_RES_LAST_GEN THEN LIST_REMOVE(\"\",LIST_REMOVE_DUPLICATES(LIST_COLLECT(\"ALL_CHILDREN\",\"\",\"PRIMARY_SKILL\"))) FI"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)