
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321261125182
 :NAME :SAN_RDPM_UA_S_ACT_DEV_STRATEGY
 :COMMENT "Development Strategy"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_DA_S_DEV_STRATEGY"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)