
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321206707941
 :NAME :SAN_RDPM_UA_ACT_PROD_TYPE
 :COMMENT "Product Type"
 :DATASET 118081000141
 :FORMULA "WBS_TYPE.SAN_UA_RDPM_S_ACT_PROT_BRD.SAN_RDPM_UA_PROD_TYPE "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)