
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321201684610
 :NAME :SAN_RDPM_UA_HES_STUDY_CODE
 :COMMENT "Internal Study Code"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_UA_ACT_STUDY_CODE"
 :NCLASS DOD::TIME-SYNTHESIS
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)