
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321259293382
 :NAME :SAN_RDPM_UA_N_GRPM_PM_ONB
 :COMMENT "ONB of GRPM PM"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF SAN_RDPM_UA_B_IS_FINANCIAL_TASK then ITER_NUMBER_MAX(\"ALLOCATED_RESOURCES\",\"RES=\\\"GRPM\\\" and PRIMARY_SKILL=\\\"PM\\\"\",\"ONB\") ELSE -1 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)