
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321235429341
 :NAME :SAN_RDPM_UA_S_PLATFORM_PH
 :COMMENT "Platform"
 :DATASET 118081000141
 :FORMULA "RES.SAN_UA_RDPM_RES_PLAT"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)