
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321202336776
 :NAME :SAN_RDPM_UA_ACT_CUSTOMIZED_PROJECT_F
 :COMMENT "Customized indication? (F)"
 :DATASET 118081000141
 :FORMULA "IF  SAN_RDPM_UA_ACT_CUSTOMIZED_PROJECT THEN  TRUE ELSE  WBS_ELEMENT.SAN_RDPM_UA_ACT_CUSTOMIZED_PROJECT_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)