
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321235209982
 :NAME :SAN_RDPM_UA_S_INDICATION_OWNER_DESC_F
 :COMMENT "Indication Owner Description (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_B_IS_AN_INDICATION THEN OBS_ELEMENT.DESC ELSE WBS_ELEMENT.SAN_RDPM_UA_S_INDICATION_OWNER_DESC_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)