
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321267707182
 :NAME :SAN_RDPM_UA_CC_BASE_ENTITY
 :COMMENT "Base Entity"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_COST_CENTER
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_BAS_ENT
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)