
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321217936210
 :NAME :SAN_RDPM_UA_ACT_PRJ_CODE_MODIF_DATE
 :COMMENT "Project Code Modification Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "IF SAN_UA_ACT_STUDY_CODE <> \"\" THEN SAN_UA_ACT_STUDY_CODE.SAN_RDPM_UA_PRJ_CODE_MODIF_DATE ELSE -1 FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)