
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321299047882
 :NAME :SAN_RDPM_UA_S_ASSAY_NATURE_SORT_WBS
 :COMMENT "Nature of assay (WBS)"
 :DATASET 118081000141
 :FORMULA "LIST_REMOVE(\"\",IF SAN_UA_RDPM_B_IS_A_STUDY THEN LIST_REMOVE_DUPLICATES(LIST_COLLECT(\"ALL_CHILDREN\",\"TRUE\",\"SAN_RDPM_UA_S_ASSAY_NATURE_SORT\")) ELSE \"\" FI)"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)