
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321221650641
 :NAME :SAN_RDPM_USA_STUDY_PREPARATION_FEES
 :COMMENT "USA Study Preparation Fees (USD)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "(((SAN_RDPM_UA_N_SITE_FROM_STUDY / (4 / 4.33) * 2) / 3) / 10) * 2  * OC.SAN_RDPM_CS_VACC_CSM_CRA_RATE +  (((((SAN_RDPM_UA_N_SITE_FROM_STUDY / (4 / 4.33) * 2) / 3) / 10) / 10 )) * 2 * OC.SAN_RDPM_CS_VACC_CSM_CRA_MGR_RATE + ((((((SAN_RDPM_UA_N_SITE_FROM_STUDY / (4 / 4.33) * 2) / 3) / 10) / 10 ) / 3 )) * 2 * OC.SAN_RDPM_CS_VACC_CSM_SR_CRA_MGR_RATE + IF SAN_RDPM_UA_N_SITE_FROM_STUDY>=10 AND SAN_RDPM_UA_N_SITE_FROM_STUDY<=29 THEN ((OC.SAN_RDPM_CS_VACC_CSM_PRJ_MGR_RATE/2)+(((OC.SAN_RDPM_CS_VACC_CSM_SENIOR_PRJ_MGR_RATE)/2)/8))*2 FI + IF SAN_RDPM_UA_N_SITE_FROM_STUDY>=20 AND SAN_RDPM_UA_N_SITE_FROM_STUDY<=29 THEN 2*(OC.SAN_RDPM_CS_VACC_CSM_LEAD_CLIN_RESEARCH_RATE/2) FI + IF SAN_RDPM_UA_N_SITE_FROM_STUDY>=30 AND SAN_RDPM_UA_N_SITE_FROM_STUDY<=49 THEN (OC.SAN_RDPM_CS_VACC_CSM_PRJ_MGR_RATE + ((OC.SAN_RDPM_CS_VACC_CSM_SENIOR_PRJ_MGR_RATE)/8) + OC.SAN_RDPM_CS_VACC_CSM_LEAD_CLIN_RESEARCH_RATE)*2 FI + IF SAN_RDPM_UA_N_SITE_FROM_STUDY>=50 AND SAN_RDPM_UA_N_SITE_FROM_STUDY<=74 THEN ((OC.SAN_RDPM_CS_VACC_CSM_PRJ_MGR_RATE + ((OC.SAN_RDPM_CS_VACC_CSM_SENIOR_PRJ_MGR_RATE)/8) + OC.SAN_RDPM_CS_VACC_CSM_LEAD_CLIN_RESEARCH_RATE)*1.5)*2 FI + IF SAN_RDPM_UA_N_SITE_FROM_STUDY>=75 THEN ((OC.SAN_RDPM_CS_VACC_CSM_PRJ_MGR_RATE + ((OC.SAN_RDPM_CS_VACC_CSM_SENIOR_PRJ_MGR_RATE)/8) + OC.SAN_RDPM_CS_VACC_CSM_LEAD_CLIN_RESEARCH_RATE)*2)*2 FI + ((SAN_RDPM_UA_N_SITE_FROM_STUDY/150)*OC.SAN_RDPM_CS_VACC_CSM_DOC_SPE_RATE*(2))  +(((SAN_RDPM_UA_N_SITE_FROM_STUDY/150)+(SAN_RDPM_UA_N_SITE_FROM_STUDY/50))*OC.SAN_RDPM_RA_MANAGER_RATE*(2))  +((SAN_RDPM_UA_N_SITE_FROM_STUDY/50)*OC.SAN_RDPM_CS_VACC_CSM_DOC_ASS_RATE*(2))"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)