
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321265488882
 :NAME :SAN_RDPM_UA_S_ACT_COMMITMENT_PIVOTAL
 :COMMENT "Commitment / Pivotal ?"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_S_COMMITMENT_PIVOTAL"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)