
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321294856282
 :NAME :SAN_RDPM_UA_PH_EXTERNAL_PARTNER_WBS
 :COMMENT "External partner WBS"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_S_EXTERNAL_PARTNER_WBS"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)