
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321293121882
 :NAME :SAN_UA_SC_S_OFFICIAL_STUDY_CODE
 :COMMENT "Official Study Code"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_PRIME_CODES
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)