
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321260896741
 :NAME :SAN_RDPM_UA_PROJECT_TEAM_MEMBER_NOTIF_DONE
 :COMMENT "Email notification sent to Team Member?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)