
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321201639210
 :NAME :SAN_RDPM_UA_HES_ALL_ROOT_PRODUCT_CODE
 :COMMENT "All Root Product Codes (F)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_DA_ALL_ROOT_PRODUCT_CODES"
 :NCLASS DOD::TIME-SYNTHESIS
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)