
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321235084082
 :NAME :SAN_RDPM_UA_S_A4P_INITIATIVES_PLANNED
 :COMMENT "A4P initiatives planned"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :ACT_FOR_PATIENT...
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)