
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321221650141
 :NAME :SAN_RDPM_USA_SITE_CLOSE_FEES
 :COMMENT "USA Site Close Fees (USD)"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "((SAN_RDPM_UA_N_SITE_FROM_STUDY * 1) / 10) * (SAN_RDPM_UA_CLOSE_OUT_PERIOD) * OC.SAN_RDPM_CS_VACC_CSM_CRA_RATE +  ((((SAN_RDPM_UA_N_SITE_FROM_STUDY * 1) / 10) / 10 )) * (SAN_RDPM_UA_CLOSE_OUT_PERIOD) * OC.SAN_RDPM_CS_VACC_CSM_CRA_MGR_RATE + (((((SAN_RDPM_UA_N_SITE_FROM_STUDY * 1) / 10) / 10 ) / 3 )) * OC.SAN_RDPM_CS_VACC_CSM_SR_CRA_MGR_RATE * SAN_RDPM_UA_CLOSE_OUT_PERIOD + IF SAN_RDPM_UA_N_SITE_FROM_STUDY>=10 AND SAN_RDPM_UA_N_SITE_FROM_STUDY<=29 THEN ((OC.SAN_RDPM_CS_VACC_CSM_PRJ_MGR_RATE/2)+(((OC.SAN_RDPM_CS_VACC_CSM_SENIOR_PRJ_MGR_RATE)/2)/8))*SAN_RDPM_UA_CLOSE_OUT_PERIOD FI + IF SAN_RDPM_UA_N_SITE_FROM_STUDY>=20 AND SAN_RDPM_UA_N_SITE_FROM_STUDY<=29 THEN SAN_RDPM_UA_CLOSE_OUT_PERIOD *(OC.SAN_RDPM_CS_VACC_CSM_LEAD_CLIN_RESEARCH_RATE/2) FI + IF SAN_RDPM_UA_N_SITE_FROM_STUDY>=30 AND SAN_RDPM_UA_N_SITE_FROM_STUDY<=49 THEN (OC.SAN_RDPM_CS_VACC_CSM_PRJ_MGR_RATE + ((OC.SAN_RDPM_CS_VACC_CSM_SENIOR_PRJ_MGR_RATE)/8) + OC.SAN_RDPM_CS_VACC_CSM_LEAD_CLIN_RESEARCH_RATE)*(SAN_RDPM_UA_CLOSE_OUT_PERIOD) FI + IF SAN_RDPM_UA_N_SITE_FROM_STUDY>=50 AND SAN_RDPM_UA_N_SITE_FROM_STUDY<=74 THEN ((OC.SAN_RDPM_CS_VACC_CSM_PRJ_MGR_RATE + ((OC.SAN_RDPM_CS_VACC_CSM_SENIOR_PRJ_MGR_RATE)/8) + OC.SAN_RDPM_CS_VACC_CSM_LEAD_CLIN_RESEARCH_RATE)*1.5)* (SAN_RDPM_UA_CLOSE_OUT_PERIOD) FI + IF SAN_RDPM_UA_N_SITE_FROM_STUDY>=75 THEN ((OC.SAN_RDPM_CS_VACC_CSM_PRJ_MGR_RATE + ((OC.SAN_RDPM_CS_VACC_CSM_SENIOR_PRJ_MGR_RATE)/8) + OC.SAN_RDPM_CS_VACC_CSM_LEAD_CLIN_RESEARCH_RATE)*2)*(SAN_RDPM_UA_CLOSE_OUT_PERIOD) FI + ((SAN_RDPM_UA_N_SITE_FROM_STUDY/150)*OC.SAN_RDPM_CS_VACC_CSM_DOC_SPE_RATE*(SAN_RDPM_UA_CLOSE_OUT_PERIOD))  +(((SAN_RDPM_UA_N_SITE_FROM_STUDY/150)+(SAN_RDPM_UA_N_SITE_FROM_STUDY/50))*OC.SAN_RDPM_RA_MANAGER_RATE*(SAN_RDPM_UA_CLOSE_OUT_PERIOD))  +((SAN_RDPM_UA_N_SITE_FROM_STUDY/50)*OC.SAN_RDPM_CS_VACC_CSM_DOC_ASS_RATE*(SAN_RDPM_UA_CLOSE_OUT_PERIOD))"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)