
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321217935210
 :NAME :SAN_RDPM_UA_PRJ_CODE_MODIF_DATE
 :COMMENT "Project Code Modification Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RWE_PRIME_CODES
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
)