
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321217337841
 :NAME :SAN_RDPM_UA_CURRENT_MAJOR_ISSUE_IMPACT
 :COMMENT "Impact"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_MR_ISSUES
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :IMPACT
)