
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321253613982
 :NAME :SAN_RDPM_UA_S_CURRENT_CMC_CYCLE_ID
 :COMMENT "Current CMC cycle ID"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF WBS_TYPE.SAN_RDPM_UA_PHARMA_IS_A_CYCLE AND TASK_TYPE IN(\"Start milestone\") AND ?STARTED AND AS=SAN_RDPM_UA_D_AS_CURRENT_CMC_CYCLE_F THEN ID FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)