
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321234365282
 :NAME :SAN_RDPM_UA_RES_ABS_REASON
 :COMMENT "Absence reason"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:AVAIBILITY
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :ABSENCE_REASON
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)