
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321260900641
 :NAME :SAN_RDPM_UA_USER_TEAM_MEMBER_MAIL_CONTENT
 :COMMENT "Mail content for team member alert on modification of Group list"
 :DATASET 118081000141
 :FORMULA "\"<html> <p>\"+WRITE_TEXT_KEY(\"RDPM.SAN_RDPM_TK_EMAIL_TEAM_MEMBER_MAIL_1\")+\"</p>  <p>\"+WRITE_TEXT_KEY(\"RDPM.SAN_RDPM_TK_EMAIL_TEAM_MEMBER_MAIL_2\")+\" \"+LIST_COLLECT(\"USER_ATTRIBUTE_INVERSE_SAN_RDPM_UA_USER.__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER\",\"SAN_RDPM_UA_PROJECT_ROLE.SAN_RDPM_UA_PROJECT_ROLE_B_EMAIL AND SAN_RDPM_UA_PROJECT_TEAM_MEMBER_NOTIF_DONE\",\"SAN_RDPM_UF_S_PROJECT_CODE\")+\"-\"+LIST_COLLECT(\"USER_ATTRIBUTE_INVERSE_SAN_RDPM_UA_USER.__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER\",\"SAN_RDPM_UA_PROJECT_ROLE.SAN_RDPM_UA_PROJECT_ROLE_B_EMAIL AND SAN_RDPM_UA_PROJECT_TEAM_MEMBER_NOTIF_DONE\",\"PROJECT.NAME\")+\" \"+WRITE_TEXT_KEY(\"RDPM.SAN_RDPM_TK_EMAIL_TEAM_MEMBER_MAIL_3\")+\"</p>  <p>\"+WRITE_TEXT_KEY(\"RDPM.SAN_RDPM_TK_EMAIL_TEAM_MEMBER_MAIL_4\")+\" \"+\"<a href=\"+OC._HOME_ST_DEFAULT_APPLICATION_URL+\">\"+\"https://sanofi-continuum.planisware.live\"+\"</a>\"+ \"</p> <p>\"+WRITE_TEXT_KEY(\"RDPM.SAN_RDPM_TK_EMAIL_TEAM_MEMBER_MAIL_5\")+\" \"+LIST_COLLECT(\"USER_ATTRIBUTE_INVERSE_SAN_RDPM_UA_USER.__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER\",\"SAN_RDPM_UA_PROJECT_ROLE.SAN_RDPM_UA_PROJECT_ROLE_B_EMAIL AND SAN_RDPM_UA_PROJECT_TEAM_MEMBER_NOTIF_DONE\",\"PROJECT._PO_DA_S_PROJECT_ROLE_262033882840\")+\"</p> <p>\"+WRITE_TEXT_KEY(\"RDPM.SAN_RDPM_TK_EMAIL_TEAM_MEMBER_MAIL_6\")+\"</p> </html>\""
 :NCLASS GENERIC-IO:OPX2-USER
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:MULTI-LINE-STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)