
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321259293682
 :NAME :SAN_RDPM_UA_B_GRPM_LAST_ONB
 :COMMENT "PH GRPM PM last ONB"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF ACTIVITY.SAN_RDPM_UA_B_IS_FINANCIAL_TASK AND RES=\"GRPM\" AND PRIMARY_SKILL=\"PM\" AND ONB=ACTIVITY.SAN_RDPM_UA_N_GRPM_PM_ONB THEN TRUE ELSE FALSE FI"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)