
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321295672082
 :NAME :SAN_RDPM_UA_B_EXCLUDED_ROLE
 :COMMENT "Excluded Role?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::_RM_REVIEW_PT_ROLE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)