
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321201639510
 :NAME :SAN_RDPM_UA_HES_BU
 :COMMENT "Business Unit (F)"
 :DATASET 118081000141
 :FORMULA "RES.SAN_UA_RDPM_RES_BU"
 :NCLASS DOD::TIME-SYNTHESIS
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)