
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321206474976
 :NAME :SAN_RDPM_UA_ACT_ONGOING_STUDY_COUNT
 :COMMENT "Ongoing Study Count (input)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
)