
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321257390282
 :NAME :SAN_RDPM_UA_S_PROJECT_CMC_CYCLE
 :COMMENT "Project CMC Cycle"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_PRJ_RND_PRJ THEN LIST_REMOVE(\"\",LIST_COLLECT(\"ACTIVITY\",\"LEVEL=2\",\"SAN_RDPM_UA_S_ACT_CURRENT_CMC_CYCLE\")) FI"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)