
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321265486482
 :NAME :SAN_RDPM_UA_S_COMMITMENT_PIVOTAL
 :COMMENT "Commitment / Pivotal ?"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :COMMITMENT_PIVOTAL
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)