
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321201641010
 :NAME :SAN_RDPM_UA_HES_STUDY_GROUP
 :COMMENT "Study group (F)"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_DA_ACT_STUDY_GROUP"
 :NCLASS DOD::TIME-SYNTHESIS
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)