
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321201132210
 :NAME :SAN_RDPM_UA_B_IN_BVA_REPORT
 :COMMENT "Display in consolidated BVA report?"
 :DATASET 118081000141
 :NCLASS TEMP-TABLE::WBS_TYPE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)