
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321235626482
 :NAME :SAN_RDPM_UA_S_PHARMACOLOGICAL_EFFECT_F
 :COMMENT "Pharmacological effect (F)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"PROJECT\",SAN_RDPM_UA_PRJ_S_ROOT_PROJECT,\"SAN_RDPM_UA_S_PHARMACOLOGICAL_EFFECT\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)