
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321201719810
 :NAME :SAN_RDPM_UA_HES_DEPART_GROUPING
 :COMMENT "Department grouping"
 :DATASET 118081000141
 :FORMULA "RES.SAN_RDPM_UA_RES_DEP_GRP"
 :NCLASS DOD::TIME-SYNTHESIS
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
)