
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321203756610
 :NAME :SAN_RDPM_UA_CLIN_FTE_TRIAL_FILTER
 :COMMENT "Filter for clinical FTE by trial"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "PROJECT.PM_PRJ_FILTER AND ((SAN_UA_RDPM_B_IS_A_STUDY and SAN_UA_ACT_B_CALCULATED_IN_HUMAN) or (SAN_RDPM_UA_ACT_S_CALCULATED_STUDY_CODE=\"\" AND (BELONGS(\"WBS_TYPE\",OC.SAN_RDPM_CS_NON_STUD_ACT))))"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
)