
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321235868082
 :NAME :SAN_RDPM_UA_S_WBSF_TO_SDM_TEAM
 :COMMENT "SDM Role - Team"
 :DATASET 118081000141
 :DOCUMENTATION "SDM team always get CPM-CTM. Does not use FPI as a condition"
 :FORMULA "san_pjs_get_wbs_form_string_value_on_object(ID,\"CPM-SDM\",\"USER_ATTRIBUTE_SAN_UA_S_TEAM\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)