
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321305191882
 :NAME :SAN_RDPM_UA_ACTUALS_WORKDAY_END_EMPLOYMENT
 :COMMENT "WD - End Employment Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)