
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321314479582
 :NAME :SAN_RDPM_UA_WORKDAY_BUSINESS_TITLE
 :COMMENT "WD - Business Title"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY\",SAN_UA_RDPM_RES_EMPL_NUM,\"SAN_RDPM_UA_ACTUALS_WORKDAY_BUSINESS_TITLE\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)