
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302200882
 :NAME :SAN_RDPM_UA_S_KEY_MILESTONE_LEADER
 :COMMENT "Key Milestone Leader"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE KERNEL-ORDO:RESOURCE
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)