
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321321138082
 :NAME :SAN_RDPM_UA_S_GL_CODE_ASSAYS_SAMPLES
 :COMMENT "GL Code Assays/Samples"
 :DATASET 118081000141
 :FORMULA "IF WBS_TYPE IN(\"V_ASSAY\",\"V_ASSAY_EXT\") THEN \"6226310\" ELSE IF WBS_TYPE IN(\"V_S_SAMP-E\",\"V_S_SAMP-S\") THEN \"6226360\" ELSE \"\"  FI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)