
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302522182
 :NAME :SAN_RDPM_UA_S_CYCLE
 :COMMENT "Cycle"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_CYCLE_F"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur| :|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)