
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321317022582
 :NAME :SAN_RDPM_UA_S_HES_ACTIVITY_ONB
 :COMMENT "Activity ONB"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "ACTIVITY.ONB"
 :NCLASS DOD::TIME-SYNTHESIS
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)