
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321316167982
 :NAME :SAN_RDPM_UA_N_DU_DBL_PS_FPI_PS
 :COMMENT "Duration from DBL PS to FPI PS"
 :DATASET 118081000141
 :DEFAULT-VALUE 0
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN  DIFF_DATE(SAN_RDPM_UF_ACT_D_FPI_PS_F,SAN_RDPM_UF_ACT_D_DBL_PS_F,CAL) FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME:DURATION
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)