
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321316664782
 :NAME :SAN_RDPM_UA_T_EXTERN_SUCC_INFO_INTER_BB
 :COMMENT "External successor information inter BB"
 :DATASET 118081000141
 :FORMULA "SUBSTITUTE(GET_CHAR(10),\",\",LIST_COLLECT(\"SLINKS\",\"SAN_RDPM_UA_LK_B_EXTERNAL_BB_ACTIVITY \",\"SAN_RDPM_UA_LK_S_SUCC_INFO\"))"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:MULTI-LINE-STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)