
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321319303682
 :NAME :SAN_RDPM_UA_ACT_CGI_RN_F
 :COMMENT "GCI Release number (F)"
 :DATASET 118081000141
 :FORMULA "IF WBS_TYPE IN(\"V_S_GCI-LAB\",\"V_S_SAMP\",\"V_S_DBL\") THEN SAN_RDPM_UA_ACT_CGI_RN ELSE WBS_ELEMENT.SAN_RDPM_UA_ACT_CGI_RN_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)