
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321321930282
 :NAME :SAN_RDPM_UA_S_DS_DP_QTY_UNIT
 :COMMENT "DS/DP Quantity Unit"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :DS_DP_UNIT
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)