
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321316942482
 :NAME :SAN_RDPM_UA_S_TASK_TYPE_DATE
 :COMMENT "Task Type Date"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF TASK_TYPE=\"End milestone\" THEN PRINT_END_DATE(PF,\"DD-MMM-YY\") ELSE PRINT_DATE(PS,\"DD-MMM-YY\") FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)