
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302027682
 :NAME :SAN_RDPM_UA_S_OFFICIAL_STUDY_CODE
 :COMMENT "Official Study Code (F)"
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN IF SAN_UA_ACT_STUDY_CODE<>\"\" THEN SAN_UA_ACT_STUDY_CODE.SAN_UA_SC_S_OFFICIAL_STUDY_CODE FI ELSE WBS_ELEMENT.SAN_RDPM_UA_S_OFFICIAL_STUDY_CODE FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)