
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321319518582
 :NAME :SAN_RDPM_UA_B_IS_THERE_V_S_GCI_LAB
 :COMMENT "Is there a V_S_GCI-LAB?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "ITER_BOOLEAN_THERE_IS_ONE(\"ALL_CHILDREN\",\"?WBS_ELEMENT AND BELONGS(\\\"WBS_TYPE\\\",\\\"V_S_GCI-LAB\\\")\") "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)