
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302509382
 :NAME :SAN_RDPM_UA_N_NBR_LIPID_F
 :COMMENT "# of Lipid (F)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "IF SAN_RDPM_UA_B_IS_AN_INDICATION THEN SAN_RDPM_UA_N_NBR_LIPID ELSE WBS_ELEMENT.SAN_RDPM_UA_N_NBR_LIPID_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)