
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302064582
 :NAME :SAN_RDPM_UA_B_ROLE_EXCLUDED_RES
 :COMMENT "Role Excluded Resource"
 :DATASET 118081000141
 :FORMULA "san_pjs_get_wbs_form_string_value_on_object(ACTIVITY,_RM_REVIEW_RA_ROLE,\"USER_ATTRIBUTE_SAN_UA_B_EXCLUDED_RES\")"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)