
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302014682
 :NAME :SAN_RDPM_UA_S_PH_AG_LIPID_DPDT
 :COMMENT "Ag/Lipid dependent"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_S_AG_LIPID_DPDT"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)