
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321303248182
 :NAME :SAN_RDPM_UA_WORKDAY_COMPLETED_HIRE_BP
 :COMMENT "WD - Completed hire BP"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"__USER_TABLE_SAN_RDPM_UT_OPEN_POSITION_WORKDAY\",SAN_RDPM_RES_S_WORK_DAY_REF,\"SAN_RDPM_UA_OPEN_POSITION_WORKDAY_COMPLETED_HIRE_BP\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)