
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321321929682
 :NAME :SAN_RDPM_UA_S_DOP_PRODUCT_TYPE
 :COMMENT "Product Type"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :DOP_PRODUCT_TYPE
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)