
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321318917182
 :NAME :SAN_RDPM_UA_ACT_GCI_ASSAY
 :COMMENT "GCI Assay"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)