
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321320211682
 :NAME :SAN_RDPM_UA_S_PHASE_TYPE
 :COMMENT "Phase Activity Type"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF _PAC_NF_B_PHASE THEN WBS_TYPE ELSE WBS_ELEMENT.SAN_RDPM_UA_S_PHASE_TYPE FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)