
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302366982
 :NAME :SAN_RDPM_UA_N_RTMED_COSTMATERIAL_ISR
 :COMMENT "Additional cost kit with ISR"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "ROUND_NUMBER_WITH_PRECISION((1.05*SAN_RDPM_UF_BUDGETED_SAMPLES+SAN_RDPM_UF_ISR_SAMPLES)/500,0)*5500"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)