
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321321139582
 :NAME :SAN_RDPM_UA_N_TOTAL_GOOD_RECEIPTS
 :COMMENT "Total good receipts ($)"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)