
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302510982
 :NAME :SAN_RDPM_UA_N_AH_NBR_ANTIGEN
 :COMMENT "# of Antigen"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "ACTIVITY.SAN_RDPM_UA_N_NBR_ANTIGEN_F"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)