
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321315652482
 :NAME :SAN_RDPM_UA_S_WBSF_CTM_SOURCING
 :COMMENT "CTM Role - Sourcing"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_S_OBS_CALCULATED_FPI_FSI = \"DB1400\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"EDO-CTM\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") ELSE IF SAN_RDPM_UA_S_OBS_CALCULATED_FPI_FSI = \"DB1500\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"TO-CTM\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") ELSE IF SAN_RDPM_UA_S_OBS_CALCULATED_FPI_FSI = \"DB1501\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"EDOO-CTM\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") ELSE IF SAN_RDPM_UA_S_OBS_CALCULATED_FPI_FSI = \"DB1401\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"EDCO-CTM\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") ELSE IF SAN_RDPM_UA_S_OBS_CALCULATED_FPI_FSI = \"DB1200\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"CPM-CTM\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") ELSE \"\" FI FI FI FI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)