
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321303351482
 :NAME :SAN_RDPM_UA_S_PORTFOLIO_STRATEGIC_GROUPING
 :COMMENT "Portfolio Strategic Grouping"
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"ACTIVITY\",\"LEVEL=1\",\"SAN_RDPM_UA_S_PORTFOLIO_STRATEGIC_GROUPING\")"
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)