
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302661082
 :NAME :SAN_RDPM_UA_S_BB_STATUS
 :COMMENT "Building Block Status"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :BB_STATUS
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)