
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321301791882
 :NAME :SAN_RDPM_UA_S_AG_LIPID_DPDT
 :COMMENT "Ag/Lipid dependent"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :AG_LIPID_DEPENDENT
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)