
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321319522882
 :NAME :SAN_RDPM_UA_ACT_GCI_MANUAL_DURATION
 :COMMENT "GCI Manual duration"
 :DATASET 118081000141
 :DEFAULT-VALUE 0
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME:DURATION
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)