
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321314479882
 :NAME :SAN_RDPM_UA_WORKDAY_ESTIMATED_LAST_DAY_OF_LEAVE
 :COMMENT "WD - Estimated Last Day of Leave"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :FORMULA "DATE_VALUE(\"__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY\",SAN_UA_RDPM_RES_EMPL_NUM,\"SAN_RDPM_UA_ACTUALS_WORKDAY_LAST_DAY_OF_LEAVE\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)