
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321317809682
 :NAME :SAN_RDPM_UA_OBS_DEPARTMENT_GROUPING
 :COMMENT "Department grouping"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "LIST_REMOVE_DUPLICATES(LIST_COLLECT(\"SAN_RDPM_REL_OBS_TO_RES\",\"_INF_AA_B_GENERIC_RES\",\"SAN_RDPM_UA_RES_DEP_GRP\"))"
 :NCLASS KERNEL-ORDO:OBS-NODE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)