
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321319217582
 :NAME :SAN_RDPM_UA_ACT_GCI_LAB
 :COMMENT "GCI Lab"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY\",SAN_RDPM_UA_ACT_GCI_ASSAY,\"SAN_RDPM_UA_GA_LAB\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)