
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321305192582
 :NAME :SAN_RDPM_UA_ACTUALS_WORKDAY_FTE_PCT
 :COMMENT "WD - FTE %"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)