
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321320177182
 :NAME :SAN_RDPM_UF_B_PIVOTAL_SCRIPT_FILTER
 :COMMENT "Pivotal script filter"
 :DATASET 118081000141
 :FORMULA "NOT ?FINISHED AND NOT SAN_RDPM_UA_B_CLIN_STUDY_HOLD_CANC"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)