
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321315951482
 :NAME :SAN_RDPM_UA_PAST_ABSENCE_REASON
 :COMMENT "Past absence reason"
 :DATASET 118081000141
 :FORMULA "LIST_COLLECT(\"Availabilities\",\"TYPE=\\\"ABSENCE\\\" and SAN_RDPM_UA_AVAIL_LAST_PAST_ABSENCE\",\"SAN_RDPM_UA_RES_ABS_REASON\")"
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)