
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321318922282
 :NAME :SAN_RDPM_UA_GCI_ASSAY_EXTERNAL
 :COMMENT "External?"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY_ACTIVITY
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)