
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302560282
 :NAME :SAN_RDPM_UA_BENCHMARK_MODALITY
 :COMMENT "Benchmark modality"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :BENCHMARK_MODALITY
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)