
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321315653382
 :NAME :SAN_RDPM_UA_S_WBSF_EDO_TO_DBD_SOURCING
 :COMMENT "DBD Role - Sourcing"
 :DATASET 118081000141
 :FORMULA "IF SAN_RDPM_UA_S_OBS_CALCULATED_DBL = \"DB1400\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"EDO-DBD\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") ELSE IF SAN_RDPM_UA_S_OBS_CALCULATED_DBL = \"DB1502\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"CDMS-DBD\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") ELSE IF SAN_RDPM_UA_S_OBS_CALCULATED_DBL = \"DB1501\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"TO-DBD\",\"USER_ATTRIBUTE_SAN_UA_S_SOURCING\") ELSE \"\" FI FI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)