
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321319301482
 :NAME :SAN_RDPM_UA_B_IS_STUDY_OR_BELONGING
 :COMMENT "Is study or belonging to ?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY THEN TRUE ELSE WBS_ELEMENT.SAN_UA_RDPM_B_IS_A_STUDY FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)