
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302510382
 :NAME :SAN_RDPM_UA_N_PH_NBR_LIPID
 :COMMENT "# of Lipid"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "ACTIVITY.SAN_RDPM_UA_N_NBR_LIPID_F"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)