
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321317625082
 :NAME :SAN_RDPM_UA_OPEN_POSITION_DEPT_GROUPING
 :COMMENT "Department grouping"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"OBS_ELEMENT\",SAN_RDPM_UA_OPEN_POSITION_BOOST_SERVICE_CODE,\"SAN_RDPM_UA_OBS_DEPARTMENT_GROUPING\")"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_OPEN_POSITION_WORKDAY
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)