
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321318442682
 :NAME :SAN_RDPM_UA_GCI_ASSAY_VENDOR
 :COMMENT "GCI Assay Provider"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY_ACTIVITY
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::_INF_PT_CBS3
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)