
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302524782
 :NAME :SAN_UA_RDPM_AH_RES_OPER
 :COMMENT "Operationality"
 :DATASET 118081000141
 :FORMULA "RES.SAN_UA_RDPM_RES_OPER"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur| :|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)