
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321314700182
 :NAME :SAN_RDPM_UA_OPEN_POSITION_BOOST_SERVICE_CODE
 :COMMENT "BOOST - Service Code"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"__USER_TABLE_SAN_RDPM_UT_BOOST_INFORMATION\",NAME,\"SAN_RDPM_UA_FINANCE_SERVICE_CODE\")"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_OPEN_POSITION_WORKDAY
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)