
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321303952982
 :NAME :SAN_RDPM_UA_OPEN_POSITION_WORKDAY_HIRE_DATE
 :COMMENT "WD - Hire Date"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_OPEN_POSITION_WORKDAY
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:DATE+
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)