
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321319573082
 :NAME :SAN_RDPM_UA_S_CSC_SSMS_NAME_WBSF
 :COMMENT "CSC SSMS Name from WBS Form"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "san_pjs_get_wbs_form_string_value_on_object(ID,\"CSC-SSMS\",\"USER_ATTRIBUTE_SAN_UA_S_LEADER\")"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)