
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321301637482
 :NAME :SAN_RDPM_UA_DEPARTMENT_CONTRIBUTOR
 :COMMENT "Key Milestone Department Contributors"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE KERNEL-ORDO::...RESOURCE
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)