
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321321141482
 :NAME :SAN_RDPM_UA_S_CASA_NON_CASA
 :COMMENT "CASA or non CASA"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :CASA_OR_NON_CASA
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)