
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321314700782
 :NAME :SAN_RDPM_UA_ACTUALS_BOOST_CONTRACT_TYPE
 :COMMENT "BOOST - Contract type"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"__USER_TABLE_SAN_RDPM_UT_BOOST_INFORMATION\",NAME,\"SAN_RDPM_UA_FINANCE_CONTRACT_TYPE\")"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)