
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321318439982
 :NAME :SAN_RDPM_UA_GA_DUPLICATE_ASSAY
 :COMMENT "Number of duplicate assay runs per sample"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)