
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321319686882
 :NAME :SAN_RDPM_UA_ACT_GCI_ASSAY_THEORETICAL_DURATION
 :COMMENT "GCI Assay theoretical duration"
 :DATASET 118081000141
 :DEFAULT-VALUE 0
 :FORMULA "IF SAN_RDPM_UA_ACT_GCI_MANUAL_STAFF=\"\" THEN  DURATION(PRINT_NUMBER(SAN_RDPM_UA_ACT_GCI_ASSAY_SAMPLE_NUMBER *   NUMBER_VALUE(\"__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY\",SAN_RDPM_UA_ACT_GCI_ASSAY,\"SAN_RDPM_UA_GA_DUPLICATE_ASSAY\") * NUMBER_VALUE(\"__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY\",SAN_RDPM_UA_ACT_GCI_ASSAY,\"SAN_RDPM_UA_GA_VALENCE\") *    (  ((1 + NUMBER_VALUE(\"__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY\",SAN_RDPM_UA_ACT_GCI_ASSAY,\" SAN_RDPM_UA_GA_RETEST\"))*5) / (NUMBER_VALUE(\"__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY\",SAN_RDPM_UA_ACT_GCI_ASSAY,\" SAN_RDPM_UA_GA_CAPACITY\")*NUMBER_VALUE(\"__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY\",SAN_RDPM_UA_ACT_GCI_ASSAY,\" SAN_RDPM_UA_GA_STAFF\"))) ,\"####.00\")) ELSE  DURATION(PRINT_NUMBER(SAN_RDPM_UA_ACT_GCI_ASSAY_SAMPLE_NUMBER *   NUMBER_VALUE(\"__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY\",SAN_RDPM_UA_ACT_GCI_ASSAY,\"SAN_RDPM_UA_GA_DUPLICATE_ASSAY\") * NUMBER_VALUE(\"__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY\",SAN_RDPM_UA_ACT_GCI_ASSAY,\"SAN_RDPM_UA_GA_VALENCE\") *    (  ((1 + NUMBER_VALUE(\"__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY\",SAN_RDPM_UA_ACT_GCI_ASSAY,\" SAN_RDPM_UA_GA_RETEST\"))*5) / (NUMBER_VALUE(\"__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY\",SAN_RDPM_UA_ACT_GCI_ASSAY,\" SAN_RDPM_UA_GA_CAPACITY\")*SAN_RDPM_UA_ACT_GCI_MANUAL_STAFF)) ,\"####.00\")) FI "
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME:DURATION
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)