
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321321905682
 :NAME :SAN_RDPM_D_LATEST_DATE_DML
 :COMMENT "Latest finish (DML)"
 :DATASET 118081000141
 :DEFAULT-VALUE -1
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TIME-TYPES:END-DATE+
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)