
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321317808282
 :NAME :SAN_RDPM_UA_B_DISPLAY_VACC_GPM_ROADMAP
 :COMMENT "Display in Vaccine GPM roadmap?"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur| :|Roadmap|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)