
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 321302638682
 :NAME :SAN_RDPM_UA_S_BB_STATUS_F
 :COMMENT "Building Block Status (F)"
 :DATASET 118081000141
 :FORMULA "IF WBS_TYPE.SAN_RDPM_UA_AT_B_BUILD_BLOCK THEN SAN_RDPM_UA_S_BB_STATUS ELSE WBS_ELEMENT.SAN_RDPM_UA_S_BB_STATUS_F FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)