
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 336984138641
 :NAME :SAN_RDPM_UA_ADJUVANT_AH
 :COMMENT "Adjuvant"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_ADJUVANT"
 :NCLASS DOD:WORK-PERFORMED
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)