
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 336984138041
 :NAME :SAN_RDPM_UA_S_PH_OBS_ELEMENT
 :COMMENT "OBS Element"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.OBS_ELEMENT"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)