
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 336984139141
 :NAME :SAN_RDPM_UA_ADJUVANT_PH
 :COMMENT "Adjuvant"
 :DATASET 118081000141
 :FORMULA "ACTIVITY.SAN_RDPM_UA_ADJUVANT"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)