
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 336984124641
 :NAME :SAN_RDPM_UA_ADJUVANT
 :COMMENT "Adjuvant"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :ADJUVANT
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)