
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 336984098741
 :NAME :SAN_RDPM_UA_S_PRJ_TEAM_INDICATION_OWNER_DESC_F
 :COMMENT "Indication Owner Description (F)"
 :DATASET 118081000141
 :FORMULA "STRING_VALUE(\"ACTIVITY\",PROJECT_ROOT_ACTIVITY(PROJECT),\"SAN_RDPM_UA_S_INDICATION_OWNER_DESC_F\")"
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)