
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 337654297341
 :NAME :SAN_RDPM_UA_S_ROLE_CPLX_FACTOR
 :COMMENT "Role Complexity Factor"
 :DATASET 118081000141
 :DEFAULT-VALUE 0.0d0
 :FORMULA "san_pjs_get_wbs_form_number_value_on_object(ACTIVITY,_RM_REVIEW_RA_ROLE,\"USER_ATTRIBUTE_SAN_UA_N_COMPLEXITY_FACTOR\")"
 :NCLASS KERNEL-ORDO:TASK-ALLOC
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE NUMBER
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)