
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 337654780141
 :NAME :SAN_RDPM_UA_S_WBSF_STT_LEADER_CPLX_FACTOR
 :COMMENT "STT Role - Complexity Factor"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF SAN_UA_RDPM_B_IS_A_STUDY AND SAN_UA_S_ACT_CALCULATED_OBS_STAT_ANALYSIS=\"DB1600\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"BP-STT\",\"USER_ATTRIBUTE_SAN_UA_N_COMPLEXITY_FACTOR\") ELSE IF SAN_UA_RDPM_B_IS_A_STUDY AND SAN_UA_S_ACT_CALCULATED_OBS_STAT_ANALYSIS=\"BS1000\" THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"STAT-STT\",\"USER_ATTRIBUTE_SAN_UA_N_COMPLEXITY_FACTOR\") ELSE IF SAN_UA_RDPM_B_IS_A_STUDY THEN san_pjs_get_wbs_form_string_value_on_object(ID,\"STAT-STT\",\"USER_ATTRIBUTE_SAN_UA_N_COMPLEXITY_FACTOR\") FI FI FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)