
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 337654462541
 :NAME :SAN_RDPM_UA_MRNA_INITIATIVE_OBJECTIVE
 :COMMENT "mRNA initiative objective"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :MRNA_INITIATIVE_OBJECTIVE
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)