
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 338831324941
 :NAME :SAN_RDPM_UA_RES_SKILL_LEVEL
 :COMMENT "Skill level"
 :DATASET 118081000141
 :DEFAULT-VALUE :||
 :NCLASS KERNEL-ORDO:RESOURCE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :SKILL_LEVEL
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)