
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 340178690441
 :NAME :SAN_RDPM_UA_B_BLOCKBUSTER_OPPORTUNITY_ACTIVITY_LEVEL
 :COMMENT "Blockbuster Opportunity (F)"
 :DATASET 118081000141
 :FORMULA "Project.SAN_RDPM_UA_B_BLOCKBUSTER_OPPORTUNITY_PROJECT_LEVEL"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur| :|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)