
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 340178707341
 :NAME :SAN_RDPM_UA_S_DEV_MS_CLINICAL_STUDY
 :COMMENT "Dev milestone clinical study"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pasteur| :|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :SPECIFIC_CLINICAL_STUDY...
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)