
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 340178816941
 :NAME :SAN_RDPM_UA_ACT_DEV_FLAG
 :COMMENT "Device flag"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE :DEVICE_FLAG...
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)