
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 340891426841
 :NAME :SAN_RDPM_UA_PROJECT_ROLE_SUBTEAMS
 :COMMENT "Subteam(s)"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_PROJECT_ROLE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::...__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)