
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 340895168841
 :NAME :SAN_RDPM_ACT_REASON_FOR_CHANGE
 :COMMENT "Reason for change"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:MULTI-LINE-STRING
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)