
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 340893452441
 :NAME :SAN_RDPM_UA_DELAY_CATEGORY
 :COMMENT "Delay Category"
 :DATASET 118081000141
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM.Pharma|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OPX2-USER::__USER_TABLE_SAN_RDPM_UT_DELAY_CATEGORY
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)