
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 340895267441
 :NAME :SAN_RDPM_UA_DELAY_CATEGORY_ACTIVITY_TYPE
 :COMMENT "Activity Type in Delay Category Entity"
 :DATASET 118081000141
 :NCLASS OPX2-USER::__USER_TABLE_SAN_RDPM_UT_DELAY_CATEGORY
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE TEMP-TABLE::...WBS_TYPE
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)