
(NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :OBJECT-NUMBER 341707828441
 :NAME :SAN_RDPM_UA_B_BB_ACTIVITY
 :COMMENT "Is from BB?"
 :ADMIN-ONLY T
 :DATASET 118081000141
 :FORMULA "IF WBS_TYPE.SAN_RDPM_UA_AT_B_BUILD_BLOCK THEN TRUE ELSE WBS_ELEMENT.SAN_RDPM_UA_B_BB_ACTIVITY FI"
 :NCLASS KERNEL-ORDO:WORK-STRUCTURE
 :PTYPES (:|Continuum.RDPM|)
 :SOURCE-DCR-SYNC-OBJECTS 0
 :TYPE OBJECT:YES-OR-NO
 :_USERATT_AA_B_HIDE_IN_CFG "0"
)