
(TEMP-TABLE::_L1_PT_SF
 :OBJECT-NUMBER 321314959582
 :NAME "SAN_RDPM_SF_WORKDAY_EFFECTIVE_END_DATE"
 :COMMENT "WD - End Employment Date"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_SF_FONT_BOLD "0"
 :_L1_AA_B_SF_FONT_ITALIC "0"
 :_L1_AA_N_SF_FONT_SIZE 8.0d0
 :_L1_AA_S_SF_BACKGROUND1 "OBJ28"
 :_L1_AA_S_SF_BACKGROUND2 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_BACKGROUND3 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_BACKGROUND4 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_BACKGROUND5 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_ENTITY "RESOURCE"
 :_L1_AA_S_SF_FONT "Tahoma"
 :_L1_AA_S_SF_FOREGROUND1 "OBJ36"
 :_L1_AA_S_SF_FOREGROUND2 "OBJ36"
 :_L1_AA_S_SF_FOREGROUND3 "OBJ36"
 :_L1_AA_S_SF_FOREGROUND4 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_FOREGROUND5 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_FORMULA1 "(DATE_VALUE(\"__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY\",SAN_UA_RDPM_RES_EMPL_NUM,\"SAN_RDPM_UA_ACTUALS_WORKDAY_END_EMPLOYMENT\")<>-1 AND EFFECTIVE_END_DATE<>(DATE_VALUE(\"__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY\",SAN_UA_RDPM_RES_EMPL_NUM,\"SAN_RDPM_UA_ACTUALS_WORKDAY_END_EMPLOYMENT\")+'1d')) AND NOT SAN_RDPM_UA_RES_SHARED AND NOT SAN_RDPM_UA_RES_MOVE_REASON_IN IN(\"Mission\")"
 :_L1_AA_S_SF_FORMULA2 "EFFECTIVE_END_DATE=(DATE_VALUE(\"__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY\",SAN_UA_RDPM_RES_EMPL_NUM,\"SAN_RDPM_UA_ACTUALS_WORKDAY_END_EMPLOYMENT\")+'1d')"
 :_L1_AA_S_SF_FORMULA3 "(DATE_VALUE(\"__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY\",SAN_UA_RDPM_RES_EMPL_NUM,\"SAN_RDPM_UA_ACTUALS_WORKDAY_END_EMPLOYMENT\")<>-1 AND EFFECTIVE_END_DATE<>(DATE_VALUE(\"__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY\",SAN_UA_RDPM_RES_EMPL_NUM,\"SAN_RDPM_UA_ACTUALS_WORKDAY_END_EMPLOYMENT\")+'1d')) AND (SAN_RDPM_UA_RES_SHARED OR SAN_RDPM_UA_RES_MOVE_REASON_IN IN(\"Mission\"))"
 :_L1_AA_S_SF_STRING1 "DATE_VALUE(\"__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY\",SAN_UA_RDPM_RES_EMPL_NUM,\"SAN_RDPM_UA_ACTUALS_WORKDAY_END_EMPLOYMENT\")"
 :_L1_AA_S_SF_STRING2 "DATE_VALUE(\"__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY\",SAN_UA_RDPM_RES_EMPL_NUM,\"SAN_RDPM_UA_ACTUALS_WORKDAY_END_EMPLOYMENT\")"
 :_L1_AA_S_SF_STRING3 "DATE_VALUE(\"__USER_TABLE_SAN_RDPM_UT_ACTUALS_WORKDAY\",SAN_UA_RDPM_RES_EMPL_NUM,\"SAN_RDPM_UA_ACTUALS_WORKDAY_END_EMPLOYMENT\")"
 :_L1_AA_S_SF_TYPE "STRING"
)