
(TEMP-TABLE::_L1_PT_SF
 :OBJECT-NUMBER 143488143271
 :NAME "SAN_RDPM_SF_LEAD_LAG_MONTH"
 :COMMENT "Yearly Lead/Lag (months)"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_SF_FONT_BOLD "0"
 :_L1_AA_B_SF_FONT_ITALIC "0"
 :_L1_AA_N_SF_FONT_SIZE 8.0d0
 :_L1_AA_S_SF_BACKGROUND1 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_BACKGROUND2 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_BACKGROUND3 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_BACKGROUND4 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_BACKGROUND5 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_ENTITY "ACTIVITY"
 :_L1_AA_S_SF_FONT "Tahoma"
 :_L1_AA_S_SF_FOREGROUND1 "OBJ1"
 :_L1_AA_S_SF_FOREGROUND2 "OBJ9"
 :_L1_AA_S_SF_FOREGROUND3 "OBJ1"
 :_L1_AA_S_SF_FOREGROUND4 "OBJ9"
 :_L1_AA_S_SF_FOREGROUND5 "OBJ36"
 :_L1_AA_S_SF_FORMULA1 "IF TASK_TYPE = \"Start milestone\" THEN ((SAN_RDPM_UA_YEARLY_BL_START_DATE <> -1) AND YEAR_NUMBER(SAN_RDPM_UA_YEARLY_BL_START_DATE)=YEAR_NUMBER($DATE_OF_THE_DAY) AND (DIFF_DATE(SAN_RDPM_UA_YEARLY_BL_START_DATE,PS,\"\")>'28d')) ELSE ((SAN_RDPM_UA_YEARLY_BL_FINISH_DATE <> -1) AND YEAR_NUMBER(SAN_RDPM_UA_YEARLY_BL_FINISH_DATE)=YEAR_NUMBER($DATE_OF_THE_DAY) AND (DIFF_DATE(SAN_RDPM_UA_YEARLY_BL_FINISH_DATE,PF,\"\")>'28d')) FI"
 :_L1_AA_S_SF_FORMULA2 "IF TASK_TYPE = \"Start milestone\" THEN ((SAN_RDPM_UA_YEARLY_BL_START_DATE <> -1) AND YEAR_NUMBER(SAN_RDPM_UA_YEARLY_BL_START_DATE)=YEAR_NUMBER($DATE_OF_THE_DAY) AND (DIFF_DATE(SAN_RDPM_UA_YEARLY_BL_START_DATE,PS,\"\")<'-28d')) ELSE ((SAN_RDPM_UA_YEARLY_BL_FINISH_DATE <> -1) AND YEAR_NUMBER(SAN_RDPM_UA_YEARLY_BL_FINISH_DATE)=YEAR_NUMBER($DATE_OF_THE_DAY) AND (DIFF_DATE(SAN_RDPM_UA_YEARLY_BL_FINISH_DATE,PF,\"\")<'-28d')) FI"
 :_L1_AA_S_SF_FORMULA3 "IF TASK_TYPE = \"Start milestone\" THEN ((SAN_RDPM_UA_YEARLY_BL_START_DATE <> -1) AND YEAR_NUMBER(SAN_RDPM_UA_YEARLY_BL_START_DATE)<>YEAR_NUMBER($DATE_OF_THE_DAY)AND (DIFF_DATE(SAN_RDPM_UA_YEARLY_BL_START_DATE,PS,\"\")>'3M')) ELSE((SAN_RDPM_UA_YEARLY_BL_FINISH_DATE <> -1) AND YEAR_NUMBER(SAN_RDPM_UA_YEARLY_BL_FINISH_DATE)<>YEAR_NUMBER($DATE_OF_THE_DAY)AND (DIFF_DATE(SAN_RDPM_UA_YEARLY_BL_FINISH_DATE,PF,\"\")>'3M')) FI"
 :_L1_AA_S_SF_FORMULA4 "IF TASK_TYPE = \"Start milestone\" THEN ((SAN_RDPM_UA_YEARLY_BL_START_DATE <> -1) AND YEAR_NUMBER(SAN_RDPM_UA_YEARLY_BL_START_DATE)<>YEAR_NUMBER($DATE_OF_THE_DAY) AND (DIFF_DATE(SAN_RDPM_UA_YEARLY_BL_START_DATE,PS,\"\")<'-3M')) ELSE ((SAN_RDPM_UA_YEARLY_BL_FINISH_DATE <> -1) AND YEAR_NUMBER(SAN_RDPM_UA_YEARLY_BL_FINISH_DATE)<>YEAR_NUMBER($DATE_OF_THE_DAY) AND (DIFF_DATE(SAN_RDPM_UA_YEARLY_BL_FINISH_DATE,PF,\"\")<'-3M')) FI"
 :_L1_AA_S_SF_FORMULA5 "TRUE"
 :_L1_AA_S_SF_STRING1 "SAN_RDPM_UA_ACT_YEARLY_LEAD_LAG_MONTH"
 :_L1_AA_S_SF_STRING2 "SAN_RDPM_UA_ACT_YEARLY_LEAD_LAG_MONTH"
 :_L1_AA_S_SF_STRING3 "SAN_RDPM_UA_ACT_YEARLY_LEAD_LAG_MONTH"
 :_L1_AA_S_SF_STRING4 "SAN_RDPM_UA_ACT_YEARLY_LEAD_LAG_MONTH"
 :_L1_AA_S_SF_STRING5 "IF (IF TASK_TYPE = \"Start milestone\" THEN SAN_RDPM_UA_YEARLY_BL_START_DATE <> -1 ELSE SAN_RDPM_UA_YEARLY_BL_FINISH_DATE <> -1 FI) THEN SAN_RDPM_UA_ACT_YEARLY_LEAD_LAG_MONTH ELSE \"No baseline\" FI"
 :_L1_AA_S_SF_TYPE "STRING"
)