
(TEMP-TABLE::_L1_PT_SF
 :OBJECT-NUMBER 143364816672
 :NAME "SAN_RDPM_SF_TC_STAT_VAL"
 :COMMENT "Validated"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_SF_FONT_BOLD "0"
 :_L1_AA_B_SF_FONT_ITALIC "0"
 :_L1_AA_N_SF_FONT_SIZE 0.0d0
 :_L1_AA_S_SF_BACKGROUND1 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_BACKGROUND2 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_BACKGROUND3 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_BACKGROUND4 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_BACKGROUND5 "_INF_PA_TRANSPARENT"
 :_L1_AA_S_SF_ENTITY "CONTEXT-OPX2"
 :_L1_AA_S_SF_FORMULA1 "$LANGUAGE=\"ENGLISH\""
 :_L1_AA_S_SF_FORMULA2 "$LANGUAGE=\"FRENCH\""
 :_L1_AA_S_SF_FORMULA3 "$LANGUAGE=\"GERMAN\""
 :_L1_AA_S_SF_IMAGE1 "SAN_RDPM_IM_TC_STAT_EN_VALID_IMG"
 :_L1_AA_S_SF_IMAGE2 "SAN_RDPM_IM_TC_STAT_FR_VALID_IMG"
 :_L1_AA_S_SF_IMAGE3 "SAN_RDPM_IM_TC_STAT_DE_VALID_IMG"
 :_L1_AA_S_SF_TYPE "IMAGE"
)