
(USER-TRACE::USER-TRACE
 :OBJECT-NUMBER 282702006582
 :ATTRIBUTE-ID :EFFECTIVE-FINISH
 :DATASET 118081000141
 :FILTER "( PROJECT.SAN_RDPM_B_RND_PHARMA_PROJECT and _WPM_RO_WORKPACKAGE_MANAGER=\"DO_LOCAL_MA_CPL\" ) OR PROJECT.SAN_RDPM_B_RND_VACCINES_PROJECT"
 :ON-CLASS KERNEL-ORDO:WORK-STRUCTURE
)