
(USER-TRACE::USER-TRACE
 :OBJECT-NUMBER 282702114082
 :ATTRIBUTE-ID :USER_ATTRIBUTE_SAN_RDPM_UA_S_PHARMA_NICKNAME
 :DATASET 118081000141
 :FILTER "PROJECT.SAN_RDPM_B_RND_PHARMA_PROJECT and _WPM_RO_WORKPACKAGE_MANAGER=\"DO_LOCAL_MA_CPL\""
 :ON-CLASS KERNEL-ORDO:WORK-STRUCTURE
)