
(USER-TRACE::USER-TRACE
 :OBJECT-NUMBER 282702115482
 :ATTRIBUTE-ID :USER_ATTRIBUTE_SAN_RDPM_UA_ACT_COUNT
 :DATASET 118081000141
 :FILTER "PROJECT.SAN_RDPM_B_RND_PHARMA_PROJECT and _WPM_RO_WORKPACKAGE_MANAGER=\"DO_LOCAL_MA_CPL\" and BELONGS(\"WBS_TYPE\",OC.SAN_RDPM_CS_AT_STUDY)"
 :ON-CLASS KERNEL-ORDO:WORK-STRUCTURE
)