
(USER-TRACE::USER-TRACE
 :OBJECT-NUMBER 282702114382
 :ATTRIBUTE-ID :SAN_RDPM_CF_SITES_0
 :DATASET 118081000141
 :FILTER "PROJECT.SAN_RDPM_B_RND_PHARMA_PROJECT and _WPM_RO_WORKPACKAGE_MANAGER=\"DO_LOCAL_MA_CPL\" and BELONGS(\"WBS_TYPE\",OC.SAN_RDPM_CS_AT_STUDY)"
 :ON-CLASS KERNEL-ORDO:WORK-STRUCTURE
)