
(USER-TRACE::USER-TRACE
 :OBJECT-NUMBER 319721099082
 :ATTRIBUTE-ID :USER_ATTRIBUTE_SAN_RDPM_UA_ACT_B_DESAC_COST_ALGO
 :DATASET 118081000141
 :FILTER "PROJECT.SAN_RDPM_B_RND_PHARMA_PROJECT AND BELONGS(\"WBS_TYPE\",\"Study conduct\")"
 :ON-CLASS KERNEL-ORDO:WORK-STRUCTURE
)