
(USER-TRACE::USER-TRACE
 :OBJECT-NUMBER 340895152741
 :ATTRIBUTE-ID :USER_ATTRIBUTE_SAN_RDPM_UA_BUDGET_DECISION
 :DATASET 118081000141
 :FILTER "PROJECT.SAN_RDPM_B_RND_PHARMA_PROJECT OR PROJECT.SAN_RDPM_B_RND_VACCINES_PROJECT"
 :INFO-PAD-FORMULA "SAN_RDPM_ACT_REASON_FOR_CHANGE"
 :ON-CLASS KERNEL-ORDO:WORK-STRUCTURE
)