
(USER-LOCK:USER-LOCK
 :OBJECT-NUMBER 353993199
 :NAME :_TC_LO_TOTAL_TASK
 :COMMENT "Lock on total task (for timecard)"
 :ACTIVE T
 :DATASET 96270999
 :EVALUATE-FILTER-BEFORE-APPLY NIL
 :FILTER "FILE = \"_MOD_TC\""
 :ON-CLASS KERNEL-ORDO:WORK-STRUCTURE
 :ON-CREATE NIL
 :ON-MODIFY T
 :ON-MODIFY-ATTRIBUTES NIL
 :ON-REMOVE T
 :ORIGIN :PROJECT
 :PTYPES NIL
 :TYPE :READ-ONLY
)