
(TEMP-TABLE::_ATV_PT_ATT_VAL
 :OBJECT-NUMBER 118083856462
 :NAME "_FIN_ATV_FIN_AA_S_FILTER"
 :ARCHIVE-DATE_VALUE 0
 :DATASET 118057330253
 :DATE+_VALUE 0
 :DURATION_VALUE 0
 :END-DATE_VALUE 0
 :NUMBER_VALUE 0.0d0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :SOURCE-DCR-SYNC-OBJECTS 0
 :STRING_VALUE "FALSE"
 :YES-OR-NO_VALUE "0"
 :_ATV_AA_B_OBJ_EDITED "1"
 :_ATV_AA_N_OBJECT_ONB 1225710599
 :_ATV_AA_N_TARGET_ONB 0
 :_ATV_AA_S_CLASS "_FIN_PT_PNL"
 :_ATV_AA_S_OBJECT_ID "DEFAULT_PNL"
)