
(TEMP-TABLE::_ATV_PT_ATT_VAL
 :OBJECT-NUMBER 118081045041
 :NAME "_GUI_ATV_S_OTHER_PROJECT_TYPE"
 :ARCHIVE-DATE_VALUE 0
 :DATASET 118081000141
 :DATE+_VALUE 0
 :DURATION_VALUE 0
 :END-DATE_VALUE 0
 :NUMBER_VALUE 0.0d0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :SOURCE-DCR-SYNC-OBJECTS 0
 :STRING_VALUE "Continuum.RDPM.Pharma,Continuum.RDPM.Vaccin"
 :YES-OR-NO_VALUE "0"
 :_ATV_AA_B_OBJ_EDITED "1"
 :_ATV_AA_N_OBJECT_ONB 1248638199
 :_ATV_AA_N_TARGET_ONB 0
 :_ATV_AA_S_CLASS "_GUI_PT_MODULES"
 :_ATV_AA_S_OBJECT_ID "PM"
)