
(TEMP-TABLE::_ATV_PT_ATT_VAL
 :OBJECT-NUMBER 260078851373
 :NAME "_IHM_TB_DA_S_FILTER"
 :ARCHIVE-DATE_VALUE 0
 :DATASET 118057330253
 :DATE+_VALUE 0
 :DURATION_VALUE 0
 :END-DATE_VALUE 0
 :NUMBER_VALUE 0.0d0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :SOURCE-DCR-SYNC-OBJECTS 0
 :STRING_VALUE "IF GetCurrentModule(\"\")=\"RD_PM_VACCINES\" THEN USER_IN_GROUP($CURRENT_USER,\"OR_FUNCT_ADM_VACCINES,R_ITS_ADMIN,R_STPM,R_PM,R_PORT_VACCINES\") ELSE TRUE FI"
 :YES-OR-NO_VALUE "0"
 :_ATV_AA_B_OBJ_EDITED "1"
 :_ATV_AA_N_OBJECT_ONB 1316293599
 :_ATV_AA_N_TARGET_ONB 0
 :_ATV_AA_S_CLASS "_IHM_TB_PT_TOOLS"
)