
(TEMP-TABLE::_ATV_PT_ATT_VAL
 :OBJECT-NUMBER 142735487441
 :NAME "_RE_AA_S_GROUP_READ"
 :ARCHIVE-DATE_VALUE 0
 :DATASET 118081000141
 :DATE+_VALUE 0
 :DURATION_VALUE 0
 :END-DATE_VALUE 0
 :NUMBER_VALUE 0.0d0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :SOURCE-DCR-SYNC-OBJECTS 0
 :STRING_VALUE "M_PHARMA"
 :YES-OR-NO_VALUE "0"
 :_ATV_AA_B_OBJ_EDITED "1"
 :_ATV_AA_N_OBJECT_ONB 142735420141
 :_ATV_AA_N_TARGET_ONB 0
 :_ATV_AA_S_CLASS "_SC_PT_REPORTING"
 :_ATV_AA_S_OBJECT_ID "RD_PHARMA.PM_REPORT_RELEASES_KANBAN_WITH_GRAPH_BACKLOG"
)