
(TEMP-TABLE::_ATV_PT_ATT_VAL
 :OBJECT-NUMBER 142934421762
 :NAME "_RE_AA_S_GROUP_READ"
 :ARCHIVE-DATE_VALUE 0
 :DATASET 118057330253
 :DATE+_VALUE 0
 :DURATION_VALUE 0
 :END-DATE_VALUE 0
 :NUMBER_VALUE 0.0d0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :SOURCE-DCR-SYNC-OBJECTS 0
 :STRING_VALUE "M_CHC_IRIS,M_ROADMAP"
 :YES-OR-NO_VALUE "0"
 :_ATV_AA_B_OBJ_EDITED "1"
 :_ATV_AA_N_OBJECT_ONB 1409100499
 :_ATV_AA_N_TARGET_ONB 0
 :_ATV_AA_S_CLASS "_SC_PT_REPORTING"
 :_ATV_AA_S_OBJECT_ID "ROA._PM_REPORT_SYNCHRONIZED_FROM"
)