
(TEMP-TABLE::_ATV_PT_ATT_VAL
 :OBJECT-NUMBER 117935319098
 :NAME "_RE_AA_S_GROUP_READ"
 :ARCHIVE-DATE_VALUE 0
 :DATASET 118057330253
 :DATE+_VALUE 0
 :DURATION_VALUE 0
 :END-DATE_VALUE 0
 :NUMBER_VALUE 0.0d0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :SOURCE-DCR-SYNC-OBJECTS 0
 :STRING_VALUE "OR_FUNCT_ADM_CONTINUUM,OR_FUNCT_ADM_PHARMA,OR_FUNCT_ADM_RWE,OR_FUNCT_ADM_VACCINES,R_ITS_ADMIN,R_PORT_PHARMA,OR_PLANNER_PHARMA"
 :YES-OR-NO_VALUE "0"
 :_ATV_AA_B_OBJ_EDITED "1"
 :_ATV_AA_N_OBJECT_ONB 1309172099
 :_ATV_AA_N_TARGET_ONB 0
 :_ATV_AA_S_CLASS "_SC_PT_REPORTING"
 :_ATV_AA_S_OBJECT_ID "Administration._ADM_RE_DATA_MODEL"
)