
(TEMP-TABLE::_IHM_TB_PT_TOOLS
 :OBJECT-NUMBER 5528067799
 :NAME "_TC_REPORT_CHOOSE_DATES"
 :COMMENT "_TC_REPORT_CHOOSE_DATES"
 :DATASET 96270999
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :_IHM_AA_N_TOOL_VERSION 0.0d0
 :_IHM_TB_AA_B_CHK_VAL_LIST "0"
 :_IHM_TB_AA_B_LIST_INPUT "0"
 :_IHM_TB_AA_B_NEEDS_CHECK "0"
 :_IHM_TB_AA_B_ONLY_VISIBLE "0"
 :_IHM_TB_AA_B_SELECT_INPUT "0"
 :_IHM_TB_AA_S_TYPE "REPORT"
)