
(TEMP-TABLE::_IHM_TB_PT_TOOLS
 :OBJECT-NUMBER 317241698610
 :NAME "placeholder"
 :DATASET 118081000141
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :_IHM_AA_N_TOOL_VERSION 0.0d0
 :_IHM_TB_AA_B_CHK_VAL_LIST "0"
 :_IHM_TB_AA_B_LIST_INPUT "0"
 :_IHM_TB_AA_B_LOM "0"
 :_IHM_TB_AA_B_NEEDS_CHECK "0"
 :_IHM_TB_AA_B_ONLY_VISIBLE "0"
 :_IHM_TB_AA_B_SELECT_INPUT "1"
 :_IHM_TB_AA_S_ATTR_NAME "USER_ATTRIBUTE_SAN_RDPM_UA_OC_S_SITE"
 :_IHM_TB_AA_S_CLASS_NAME "CONTEXT-OPX2"
)