
(REQUEST-OBJECT:METHOD-REQUEST
 :OBJECT-NUMBER 44430699
 :NAME :_PE_CREATEEQUAFIELDS
 :COMMENT ""
 :DATASET 44047899
 :DOCUMENTATION ""
 :FILTER-F ""
 :GROUP-BY NIL
 :MACRO-STRING "CREATE_EQUATION_FIELDS"
 :OBJECT-CLASS TEMP-TABLE::_PE_PT_EQUA_EQUATION
 :ORDERED-BY NIL
)