
(REQUEST-OBJECT:METHOD-REQUEST
 :OBJECT-NUMBER 60426099
 :NAME :_PE_MA_LOCK_EQUATION_COMMON_FILE
 :COMMENT ""
 :DATASET 44047899
 :DOCUMENTATION ""
 :FILTER-F "NAME = \"EQUATION\""
 :GROUP-BY NIL
 :MACRO-STRING "LOCK-DATASET"
 :OBJECT-CLASS GENERIC-IO:COMMON-DATASET
 :ORDERED-BY NIL
)