
(TEMP-TABLE::PERMANENT-TABLE
 :OBJECT-NUMBER 127221408499
 :NAME "_DQA_PT_RULE_SET"
 :COMMENT "Rules template"
 :COMMENT-FIELD T
 :DATASET 127151640799
 :INHERIT-FROM TEMP-TABLE::_DQA_PT_SANITY_CHECK
 :IS-BS T
 :NAME-FIELD T
 :NAME-INDEX T
 :ORIGIN-NUMBER 0
)