
(TEMP-TABLE::PERMANENT-TABLE
 :OBJECT-NUMBER 44059899
 :NAME "_PE_PT_EQUA_EQACTATT"
 :COMMENT :|PE.Equation.action_attribute|
 :DATASET 44047899
 :ORIGIN-NUMBER 0
 :SAVE-WITH TEMP-TABLE::_PE_PT_EQUA_EQUATION
)