
(TEMP-TABLE::PERMANENT-TABLE
 :OBJECT-NUMBER 44288399
 :NAME "_PE_PT_EQUA_FILTERATT"
 :COMMENT :|PE.EquationTemplate.filter_attribute|
 :DATASET 44047899
 :IMAGE-NAME "OPX2_PERMANENT_TABLE_ICON"
 :NAME-FIELD T
 :ORIGIN-NUMBER 0
 :SAVE-WITH TEMP-TABLE::_PE_PT_EQUA_EQUATION
)