
(TEMP-TABLE::PERMANENT-TABLE
 :OBJECT-NUMBER 44060099
 :NAME "_PE_PT_EQUA_EQUATEMP"
 :COMMENT :|PE.EquationTemplate|
 :COMMENT-FIELD T
 :DATASET 44047899
 :NAME-FIELD T
 :NAME-INDEX T
 :ORIGIN-NUMBER 0
 :SAVE-WITH TEMP-TABLE::_PE_PT_EQUA_EQUATION
)