
(TEMP-TABLE::PERMANENT-TABLE
 :OBJECT-NUMBER 117702732299
 :NAME "_RB_PT_CONTAINER"
 :COMMENT "Container for level 1 cells (report-builder)"
 :COMMENT-FIELD T
 :DATASET 14047310199
 :NAME-FIELD T
 :NAME-INDEX T
 :OPTIMIZE-PRELATION T
 :ORIGIN-NUMBER 0
)