
(TEMP-TABLE::PERMANENT-TABLE
 :OBJECT-NUMBER 127918178399
 :NAME "_RB_PT_CALENDAR"
 :COMMENT :|Report.Calendar|
 :COMMENT-FIELD T
 :DATASET 14047310199
 :IS-BS T
 :IS-FRENCH-FEMININ :UNKNOWN
 :NAME-FIELD T
 :NAME-INDEX T
 :OPTIMIZE-PRELATION T
 :ORIGIN-NUMBER 0
)