
(TEMP-TABLE::PERMANENT-TABLE
 :OBJECT-NUMBER 117703130999
 :NAME "_RB_PT_GAUGE_CELL"
 :COMMENT :|Report.GaugeCell|
 :COMMENT-FIELD T
 :DATASET 14047310199
 :INHERIT-FROM TEMP-TABLE::_RB_PT_CONTAINER
 :NAME-FIELD T
 :NAME-INDEX T
 :OPTIMIZE-PRELATION T
 :ORIGIN-NUMBER 0
)