
(TEMP-TABLE::PERMANENT-TABLE
 :OBJECT-NUMBER 117702732399
 :NAME "_RB_PT_LAYOUT_CELL"
 :COMMENT :|Report.LayoutCell|
 :COMMENT-FIELD T
 :DATASET 14047310199
 :INHERIT-FROM TEMP-TABLE::_RB_PT_CONTAINER
 :NAME-FIELD T
 :NAME-INDEX T
 :OPTIMIZE-PRELATION T
 :ORIGIN-NUMBER 0
)