
(REPORT-OBJECTS:CELL-STYLE
 :OBJECT-NUMBER 117722800099
 :NAME :_GUI_CSS_63_FOLDER_NO_TOOLBAR_NO_MENU
 :COMMENT "Css for the style manager but without style manager left 6.3"
 :DATASET 1238591899
 :ON-CLASS REPORT-OBJECTS:SUBFORM-CELL
 :ORIGIN :PROJECT
 :PARENT-INDEXES NIL
 :PROPERTIES NIL
)