
(REPORT-OBJECTS:CELL-STYLE
 :OBJECT-NUMBER 117800594499
 :NAME :_GUI_CSS_GREY_STANDARD_BUTTON
 :COMMENT "Standard css for grey button on white background"
 :DATASET 1238591899
 :ON-CLASS REPORT-OBJECTS:LABEL-CELL
 :ORIGIN :PROJECT
 :PARENT-INDEXES NIL
 :PROPERTIES NIL
)