
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 100954899
 :NAME :_TC_AA_S_FILTER_ON_RESOURCE
 :COMMENT "Formula applied on the resource table, to filter the resources which can be consulted"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE OBJECT:MULTI-LINE-STRING
 :USE-FOR-INDEX T
)