
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 100954799
 :NAME :_TC_AA_S_LIST_RESOURCES_MANAGED
 :COMMENT "List of resources controled by the current user in timecard"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE OBJECT:MULTI-LINE-STRING
 :USE-FOR-INDEX T
)