
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 103228599
 :NAME :_TC_AA_B_BILLABLE
 :COMMENT :|timeCard.isBillable|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :DEFAULT-VALUE T
 :LENGTH 0
 :NCLASS DOD:WORK-PERFORMED
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)