
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1067226999
 :NAME :_TC_AA_B_REFRESH_MENU
 :COMMENT "Internal attribute used to know if the menu must be refreshed"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE OBJECT:YES-OR-NO
)