
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1087480099
 :NAME :_TC_AA_B_PERC_DEF
 :COMMENT :|timeCard.InputPercentage|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TIME-CARD-BASE:TIME-CARD-PARAMETER
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)