
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1090462499
 :NAME :_TC_AA_B_ON_SITE
 :COMMENT :|timeCard.OnSite|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :LENGTH 0
 :NCLASS DOD:WORK-PERFORMED
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)