
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 113326299
 :NAME :_TC_AA_S_QUICK_FORMULA
 :COMMENT "Formula applied on activity table in timecard ofr quick search"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)