
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117515039999
 :NAME :_RB_AA_N_TABREP_FONT_SIZE
 :COMMENT :|Report.FontSize|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DEFAULT-VALUE 0.0d0
 :DOCUMENTATION "Filed used to set the size of the font for a dashboard component."
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS::TAB-REPORT
 :STORAGE-MODE :TEMPORARY
 :TYPE NUMBER
)