
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117517617699
 :NAME :_RB_AA_S_POS_IN_MODULE
 :COMMENT :|Report.SelectScreen|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DOCUMENTATION "Field used to defined the label used when publishing tabulated reports into a module."
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS::TAB-REPORT
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)