
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117694081899
 :NAME :_RB_AA_S_CELL_NAME
 :COMMENT :|Report.Name|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DOCUMENTATION "Cell name (for popup add query/layout) ..."
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS::TAB-REPORT
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)