
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117647249799
 :NAME :_RB_AA_N_CELL_HEIGHT
 :COMMENT :|Report.Height|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DEFAULT-VALUE 0.0d0
 :DOCUMENTATION "Height of query cell (in cm)."
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS::TAB-REPORT
 :STORAGE-MODE :IN-TABLE
 :TYPE NUMBER
)