
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117769835899
 :NAME :_PE_AA_S_EQUA_ERR_DOC
 :COMMENT :|PE.Equation.error_documation|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 4000
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATION
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:MULTI-LINE-STRING
)