
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117759574299
 :NAME :_PE_AA_EQUA_B_OPTIONAL
 :COMMENT :|PE.Equation.rel_is_optional|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_ACTIONATT
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)