
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117778736699
 :NAME :_PE_AA_N_CTX_NB_EQUA
 :COMMENT :|PE.Equation.number_of_equation|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :DEFAULT-VALUE 0.0d0
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE NUMBER
)