
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117703168299
 :NAME :_RB_AA_S_BORDER_COLOR
 :COMMENT :|Report.BorderColor|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DOCUMENTATION "Border color"
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_RB_PT_CONTAINER
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)