
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117744553299
 :NAME :_RB_AA_B_SCROLLABLE
 :COMMENT :|Report.Scrollable|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS::TAB-REPORT
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)