
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117769904199
 :NAME :_RB_AA_B_DISPLAY_LEGEND
 :COMMENT :|Report.DisplayLegend|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DOCUMENTATION "Do I want to display legend on my query? "
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_RB_PT_CONTAINER
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)