
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117703167199
 :NAME :_RB_AA_N_BOTTOM_BORDER
 :COMMENT :|Report.BorderBottom|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DEFAULT-VALUE 0.0d0
 :DOCUMENTATION "Bottom border"
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_RB_PT_CONTAINER
 :STORAGE-MODE :IN-TABLE
 :TYPE NUMBER
)