
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117703168399
 :NAME :_RB_AA_S_BORDER_LABEL
 :COMMENT :|Report.BorderLabel|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DOCUMENTATION "Border label"
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_RB_PT_CONTAINER
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)