
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117885068399
 :NAME :_RB_AA_S_DRILLDOWN_TYPE
 :COMMENT :|Report.DrilldownType|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DEFAULT-VALUE :01_NO_DRILL_DOWN
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_RB_PT_CONTAINER
 :STORAGE-MODE :IN-TABLE
 :TYPE :_DBB_AT_DRILL_DOWN_T
)