
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117872464299
 :NAME :_RB_AA_B_VSCROLL
 :COMMENT :|Report.VScrollbar|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DOCUMENTATION "Add vertical scrollbar in preview mode (report-builder)"
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS::TAB-REPORT
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)