
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117885131199
 :NAME :_RB_AA_S_DRILL_TABLE_TYP
 :COMMENT "_RB_AA_S_DRILL_TABLE_TYP"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DEFAULT-VALUE :||
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_RB_PT_CONTAINER
 :STORAGE-MODE :IN-TABLE
 :TYPE :_DBB_AT_DRILL_TABLE
)