
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117832240499
 :NAME :_RB_AA_N_ONB_ORIGIN_TR
 :COMMENT :|Report.OnboriginTabreport|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DEFAULT-VALUE 0.0d0
 :DOCUMENTATION "Onb of original tabreport. Used only by publication tabreport to get back original report.
"
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS::TAB-REPORT
 :STORAGE-MODE :IN-TABLE
 :TYPE NUMBER
)