
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117836585699
 :NAME :_PE_AA_N_EQUA_CHECK_CACHE
 :COMMENT "Check result cache"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :DEFAULT-VALUE 0.0d0
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATION
 :STORAGE-MODE :IN-TABLE
 :TYPE NUMBER
)