
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117898509199
 :NAME :_RB_AA_S_CUSTOM_RIGHTS
 :COMMENT :|Report.CustomOrDefaultRights|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DEFAULT-VALUE :||
 :DOCUMENTATION "List of groups or members with read permission for this reporting."
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS::TAB-REPORT
 :STORAGE-MODE :IN-TABLE
 :TYPE :_RB_AT_RIGHTS_PUBINT
)