
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 117945436499
 :NAME :_RB_AA_B_HSCROLLBAR
 :COMMENT :|Report.HScrollbar|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DOCUMENTATION "Display horizontal scrollbar in report-builder's preview mode"
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)