
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 118190910499
 :NAME :_RB_AA_B_DATA_MINING
 :COMMENT :|Planisware_explorer.drill_down_dataMining|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DOCUMENTATION "Is there data mining on this query?"
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_RB_PT_CONTAINER
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)