
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 118593524799
 :NAME :_RB_AA_B_IS_CUSTOM_RIGHTS
 :COMMENT :|Report.IsCustomRightsActivated|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS::TAB-REPORT
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)