
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 118607571699
 :NAME :_TC_AA_S_COMMENT
 :COMMENT :|timeCard.Comment|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS DOD:WORK-PERFORMED
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)