
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 118775010999
 :NAME :_RB_AA_S_TABLECELL_NAME
 :COMMENT :|Report.TableCellName|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS::TAB-REPORT
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)