
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 118828146599
 :NAME :_RB_AA_S_REGCHART_CLASS
 :COMMENT :|Report.RegionChartClass|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS::TAB-REPORT
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)