
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 123290571499
 :NAME :_GUI_AA_B_DISPLAY_SWITCH
 :COMMENT :|Reporting.display_switcher|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "Indicates if we display or not the switcher"
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_SC_PT_REPORTING
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)