
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 123879212899
 :NAME :_RB_AA_B_HIDE_FILTER_PAN
 :COMMENT :|Report.HideFilterPanel|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DOCUMENTATION "Hide filter panel on reporting"
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS::TAB-REPORT
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)