
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 123845493199
 :NAME :_TC_PARM_S_ACT_GROUPING
 :COMMENT :|timeCard.ActivityAttributGrouping|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TIME-CARD-BASE:TIME-CARD-PARAMETER
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)