
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 124131272799
 :NAME :_TC_AA_S_VAL_BY
 :COMMENT :|timeCard.validatedby|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)