
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 124131272899
 :NAME :_TC_AA_S_PUB_BY
 :COMMENT :|timeCard.publishedby|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)