
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 124131272999
 :NAME :_TC_AA_D_PUB_DATE
 :COMMENT :|timeCard.publicationDate|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :DEFAULT-VALUE -1
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :STORAGE-MODE :IN-TABLE
 :TYPE TIME-TYPES:DATE+
)