
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 124485672999
 :NAME :_TC_PARM_B_HIDE_EXT1
 :COMMENT :|timeCard.hideExtraunit1|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TIME-CARD-BASE:TIME-CARD-PARAMETER
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)