
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1246451499
 :NAME :_TC_AA_S_GROUP_TC_LINE
 :COMMENT "Group line criteria"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PROPAGATE T
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)