
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1248505399
 :NAME :_GUI_AA_S_MODULE_INFO
 :COMMENT :|ihm.module_information|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "Field used to store the module informations "
 :LENGTH 4000
 :NCLASS TEMP-TABLE::_GUI_PT_MODULES
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:MULTI-LINE-STRING
)