
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 124972286399
 :NAME :_L1_AA_S_CPT_ADD_CLASS2
 :COMMENT :|compact_load_macro_l1.add_class2|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 124972110599
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_L1_PT_COMPACT_MACROS
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)