
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 124972285799
 :NAME :_L1_AA_S_CPT_5BS_FILTER
 :COMMENT :|BudgetManager.breakdown_desc|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 124972110599
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_L1_PT_COMPACT_MACROS
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)