
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 124972287499
 :NAME :_L1_AA_B_CPT_FIXED_DATES
 :COMMENT :|compact_load_macro_l1.fixed_dates|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 124972110599
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_L1_PT_COMPACT_MACROS
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)