
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 124972285099
 :NAME :_L1_AA_S_CPT_SKILL_FILTER
 :COMMENT :|compact_load_macro_l1.skill_filter|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 124972110599
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_L1_PT_COMPACT_MACROS
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)