
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 124972264699
 :NAME :_L1_AA_S_CPT_DATA_TYPE
 :COMMENT :|compact_load_macro_l1.data_type|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 124972110599
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_L1_PT_COMPACT_MACROS
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)