
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 126056862099
 :NAME :_TC_PARM_S_ACT_SORT
 :COMMENT :|timeCard.SortBy|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TIME-CARD-BASE:TIME-CARD-PARAMETER
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)