
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 126271721799
 :NAME :_L1_AA_S_IPR_PAGE
 :COMMENT :|intranet_page_rights.page|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 124972110599
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_L1_PT_INTRANET_PAGE
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)