
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 126410000499
 :NAME :_L1_AA_B_IPR_PLW_RIGHTS
 :COMMENT :|intranet_page_rights.use_opx2_rights|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 124972110599
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_L1_PT_INTRANET_PAGE
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)