
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 126595360299
 :NAME :_L1_AA_CTX_IPR_MODULE_FILTER
 :COMMENT :|intranet_page_rights.module|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 124972110599
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE STRING
)