
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 127221409199
 :NAME :_DQA_AA_S_DATA_SCOPE
 :COMMENT :|data_quality.rule.dataScope|
 :ALLOCATION-MODE :OPTIONAL
 :CATEGORY "Additional attributes"
 :DATASET 127151640799
 :ENCRYPTION :STRING
 :LENGTH 4000
 :NCLASS TEMP-TABLE::_DQA_PT_SANITY_CHECK
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)