
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 127221407899
 :NAME :_DQA_AA_B_LOCK_OPERATOR
 :COMMENT "Lock on target and operator"
 :ALLOCATION-MODE :OPTIONAL
 :CATEGORY "Additional attributes"
 :DATASET 127151640799
 :DEFAULT-VALUE 0.0d0
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_DQA_PT_SANITY_CHECK
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)