
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 127221409599
 :NAME :_DQA_AA_S_RULE_DESC
 :COMMENT :|data_quality.description|
 :ALLOCATION-MODE :OPTIONAL
 :CATEGORY "Additional attributes"
 :DATASET 127151640799
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_DQA_PT_SANITY_CHECK
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)