
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 127497348699
 :NAME :_L1_AA_CTX_CALL_ON_STR
 :COMMENT :|l1_potentially_callers.string_input|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 124972110599
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE STRING
)