
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 127410217099
 :NAME :_DQA_AA_D_LAST_UPDATE
 :COMMENT "Latest update"
 :ALLOCATION-MODE :OPTIONAL
 :CATEGORY "Additional attributes"
 :DATASET 127151640799
 :DEFAULT-VALUE -1
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_DQA_PT_REL_RULE
 :STORAGE-MODE :IN-TABLE
 :TYPE TIME-TYPES:DATE+
)