
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 127504917499
 :NAME :_DQA_AA_N_TOTAL_KO
 :COMMENT :|data_quality.rule.totalKO|
 :ALLOCATION-MODE :OPTIONAL
 :CATEGORY "Additional attributes"
 :DATASET 127151640799
 :DEFAULT-VALUE 0.0d0
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_DQA_PT_REL_RULE
 :STORAGE-MODE :IN-TABLE
 :TYPE NUMBER
)