
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 127611309699
 :NAME :_DBB_AA_S_CUSTOM_RIGHTS
 :COMMENT :|Report.CustomOrDefaultRights|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DEFAULT-VALUE :||
 :DOCUMENTATION "List of groups or members with read permission for this reporting."
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS PORTFOLIO-EXPLORER::DASHBOARD
 :STORAGE-MODE :IN-TABLE
 :TYPE :_RB_AT_RIGHTS_PUBINT
)