
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 127708262199
 :NAME :_DQA_AA_S_ADD_FIELD
 :COMMENT "Additional field"
 :ALLOCATION-MODE :OPTIONAL
 :CATEGORY "Additional attributes"
 :DATASET 127151640799
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_DQA_PT_REL_RULE
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)