
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 127708496899
 :NAME :_RB_AA_S_GAUGEOBJECT
 :COMMENT "_RB_AA_S_GAUGEOBJECT"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS REPORT-OBJECTS:LABEL-CELL
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)