
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 127918178499
 :NAME :_RB_AA_N_SORT
 :COMMENT :|Report.SortOrder|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DEFAULT-VALUE 0.0d0
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_RB_PT_CALENDAR
 :STORAGE-MODE :IN-TABLE
 :TYPE NUMBER
)