
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 127918179299
 :NAME :_RB_AA_S_COLOR_FONT
 :COMMENT :|Report.FontColor|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_RB_PT_CALENDAR
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)