
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 127918487099
 :NAME :_RB_AA_D_CAL_DATE
 :COMMENT :|Report.CalSelectDate|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DEFAULT-VALUE -1
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :IN-TABLE
 :TYPE TIME-TYPES:DATE+
)