
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 128272098499
 :NAME :_DQA_AA_S_FCT_OR_FORMULA
 :COMMENT :|data_quality.rule.formulaOrFunction|
 :ALLOCATION-MODE :OPTIONAL
 :CATEGORY "Additional attributes"
 :DATASET 127151640799
 :DEFAULT-VALUE :||
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_DQA_PT_RULE_SET
 :STORAGE-MODE :IN-TABLE
 :TYPE :_DQA_AT_FCT_FORMULA
)