
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 128296009699
 :NAME :_DQA_AA_S_FCTDRAWLEFTSIDE
 :COMMENT :|data_quality.rule.fctDrawLeftSide|
 :ALLOCATION-MODE :OPTIONAL
 :CATEGORY "Additional attributes"
 :DATASET 127151640799
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_DQA_PT_RULE_SET
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)