
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 129490336699
 :NAME :_DQA_AA_S_USCRIPT_FCT
 :COMMENT "Fonction defined by user script "
 :ALLOCATION-MODE :OPTIONAL
 :CATEGORY "Additional attributes"
 :DATASET 127151640799
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_DQA_PT_RULE_SET
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:MULTI-LINE-STRING
)