
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 129646354099
 :NAME :_PM_AA_B_TR_PRJ_CONTENT
 :COMMENT :|transactions_l1.display_child_object|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 124972110599
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-PROJECT:ORDO-PROJECT
 :STORAGE-MODE :TEMPORARY
 :TYPE OBJECT:YES-OR-NO
)