
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 129865516099
 :NAME :_GUI_AA_S_TABLE_LINE_HEIGHT
 :COMMENT :|grid.table_line_height|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DEFAULT-VALUE :STANDARD
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :IN-TABLE
 :TYPE :_GUI_AT_LINE_SIZE
)