
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 130024065599
 :NAME :_DQA_AA_N_COST_VERSION
 :COMMENT "Last cost version"
 :ALLOCATION-MODE :OPTIONAL
 :CATEGORY "Additional attributes"
 :DATASET 127151640799
 :DEFAULT-VALUE 0.0d0
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS TEMP-TABLE::_DQA_PT_REL_RULE
 :STORAGE-MODE :IN-TABLE
 :TYPE NUMBER
)