
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1309230099
 :NAME :_GUI_AA_N_REFRESH_COUNTER
 :COMMENT "Refresh counter for navigation bar"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DEFAULT-VALUE 0.0d0
 :DOCUMENTATION "Field used to activate the selective refresh when performing actions on the navigation tab bar"
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE NUMBER
)