
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1323551799
 :NAME :_GUI_AA_B_P6_NAVIGATION_MODE
 :COMMENT :|ihm.activate_old_gui|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DEFAULT-VALUE T
 :DOCUMENTATION "Field used to store the graphical preference for the user"
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)