
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1326410299
 :NAME :_GUI_AA_S_NAV_SCRIPT
 :COMMENT :|ihm.On_Nav_In_Module|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :LENGTH 0
 :NCLASS TEMP-TABLE::_GUI_PT_MODULES
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)