
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1326047899
 :NAME :_GUI_AA_S_ACTIVE_SETTING
 :COMMENT :|ihm.activeStatusField|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "Stores the name of the setting used to activate/deactivate the module (for compatibility)"
 :LENGTH 0
 :NCLASS TEMP-TABLE::_GUI_PT_MODULES
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)