
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1334970499
 :NAME :_GUI_AA_B_ALWAYS_ACTIVE
 :COMMENT :|ihm.alwaysEnabled|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "Field used to to define whether the module has to be always active or not."
 :LENGTH 0
 :NCLASS TEMP-TABLE::_GUI_PT_MODULES
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)