
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1336799699
 :NAME :_GUI_AA_S_OPEN_FUNCTION
 :COMMENT :|ihm.openingFunction|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "Field used to store the opening function for a module"
 :LENGTH 0
 :NCLASS TEMP-TABLE::_GUI_PT_MODULES
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)