
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1336799799
 :NAME :_GUI_AA_B_NEW_TAB_OK
 :COMMENT :|ihm.newTabOpeningPossible|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "Field used to defined if the module can open new tab on his object"
 :LENGTH 0
 :NCLASS TEMP-TABLE::_GUI_PT_MODULES
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)