
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1338467999
 :NAME :_GUI_AA_S_PAGE_TEMPLATE
 :COMMENT :|ihm.pageTemplate|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :LENGTH 0
 :NCLASS TEMP-TABLE::_GUI_PT_MODULES
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)