
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1340857499
 :NAME :_GUI_AA_B_START_MODULE
 :COMMENT :|ihm.isTheStartingModule|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "Field used to to define whether the module is the entry module or not."
 :LENGTH 0
 :NCLASS TEMP-TABLE::_GUI_PT_MODULES
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)