
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1341638399
 :NAME :_GUI_AA_S_DEF_USER_GROUP
 :COMMENT :|ihm.defaultUserGroups|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "Field used to store the DEFAULT VALUE of the user groups which can have access to the page"
 :LENGTH 4000
 :NCLASS TEMP-TABLE::_GUI_PT_MODULES
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)