
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1343763399
 :NAME :_IHM_AA_B_HIDE_TOOLBAR
 :COMMENT "Hide toolbar on the reporting"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :LENGTH 0
 :NCLASS TEMP-TABLE::_SC_PT_REPORTING
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)