
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 13964853199
 :NAME :_TC_PARM_S_ACT_FILTER
 :COMMENT :|teamMember.activity_filter_for_agenda|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :LENGTH 0
 :NCLASS TIME-CARD-BASE:TIME-CARD-PARAMETER
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)