
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 14078669799
 :NAME :_RB_AA_B_MENU_CLOSED
 :COMMENT "Window menu is closed"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE OBJECT:YES-OR-NO
)