
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 14193174999
 :NAME :_RB_AA_S_REPORT_FONT
 :COMMENT :|Report.Font|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DOCUMENTATION "To define the police for a report component"
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PROPAGATE T
 :STORAGE-MODE :TEMPORARY
 :TYPE STRING
)