
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1423978399
 :NAME :_TC_AA_S_CONTROL_FILTER
 :COMMENT :|timeCard.ControlFilter|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :LENGTH 0
 :NCLASS TIME-CARD-BASE:TIME-CARD-PARAMETER
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)