
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 14250568599
 :NAME :_RB_AA_N_FONT_SIZE
 :COMMENT :|Report.FontSize|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 14047310199
 :DEFAULT-VALUE 0.0d0
 :DOCUMENTATION "field used to set the size of the font for a dashboard component"
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PROPAGATE T
 :STORAGE-MODE :TEMPORARY
 :TYPE NUMBER
)