
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1436729599
 :NAME :_GUI_AA_URL_COMPLEMENT
 :COMMENT :|ihm._GUI_AA_URL_COMPLEMENT|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :LENGTH 0
 :NCLASS REPORT-OBJECTS:REPORT
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)