
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1710936699
 :NAME :_GUI_AA_S_ADVANCED_FEAT
 :COMMENT :|ihm._GUI_ATV_S_DATASOURCE_ADVANCED_FN|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "IS-00021548 : Field used to store the formula for displaying the tool in planisware panel"
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TEMP-TABLE::_GUI_PT_MODULES
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)