
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1716221399
 :NAME :_GUI_AA_S_KERNEL_FN
 :COMMENT :|ihm.IntranetPageFormulaField|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "IS-00021548"
 :LENGTH 0
 :NCLASS TEMP-TABLE::_GUI_PT_PANEL_TOOLS
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)