
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1717971999
 :NAME :_GUI_AA_S_ZOOM_IN
 :COMMENT :|ihm.zoomIn|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "IS-00021548 : Field used to store the formula for displaying the tool in planisware panel"
 :LENGTH 0
 :NCLASS TEMP-TABLE::_GUI_PT_MODULES
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)