
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 1717955499
 :NAME :_GUI_AA_B_TOOLS
 :COMMENT :|ihm.PresentInToolsSection|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "IS-00021548 : Field used to know if the tool is in the Tools section"
 :LENGTH 0
 :NCLASS TEMP-TABLE::_GUI_PT_PANEL_TOOLS
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)