
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 359534499
 :NAME :_TC_AA_N_FORECAST_0
 :COMMENT "2007_JUL_26_SU_Estimate"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :DEFAULT-VALUE 0.0d0
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TIME-CARD-BASE:TIME-CARD-LINE
 :STORAGE-MODE :TEMPORARY
 :TYPE NUMBER
)