
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 373018499
 :NAME :_TC_AA_S_TIMESCALE
 :COMMENT "timescale (timcard parameters)"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE STRING
)