
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 426366299
 :NAME :_TC_AA_B_SWITCH_EXTRAUNIT4
 :COMMENT "Display/hide extra unit 4 in a time sheet"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)