
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 44162699
 :NAME :_PE_AA_EQUA_ONBASECLASS
 :COMMENT :|PE.Equation.evaluate_on_activation_class|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_ACTIONATT
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)