
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 44162599
 :NAME :_PE_AA_EQUA_ETVISBL
 :COMMENT :|PE.EquationTemplate.visibility|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATEMP
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)