
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 44162799
 :NAME :_PE_AA_EQUA_DFTVAL
 :COMMENT :|PE.Equation.default_value|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_ACTIONATT
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)