
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 44162099
 :NAME :_PE_AA_EQUA_FROMOBJECT
 :COMMENT :|PE.Equation.from_object|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATION
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)