
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 44163299
 :NAME :_PE_AA_EQUA_ACTATTVAL
 :COMMENT :|PE.Equation.value|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 4000
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQACTATT
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)