
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 44163099
 :NAME :_PE_AA_EQUA_AAISCALC
 :COMMENT :|PE.Equation.is_calculated|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_ACTIONATT
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)