
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 44162399
 :NAME :_PE_AA_EQUA_OTHERFILT2
 :COMMENT :|PE.EquationTemplate.filter_on_action_class|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 4000
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATEMP
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)