
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 44161699
 :NAME :_PE_DA_EQUA_MDYFDS_NEEDED
 :COMMENT :|PE.Equation.mandatory_fields_needed|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_OBJECTCLASS
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)