
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 44161799
 :NAME :_PE_AA_EQUA_OPXCLASS
 :COMMENT :|PE.Equation.opx_class|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_OBJECTCLASS
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)