
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 4419504599
 :NAME :_IHM_AA_S_REPORT_TYPE
 :COMMENT :|ihm.dataset_class_report_type|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DEFAULT-VALUE :REPORT
 :DOCUMENTATION "Field used to select the report type for the dataset class"
 :LENGTH 0
 :NCLASS IO-ORDO::PROJECT-TYPE
 :STORAGE-MODE :IN-TABLE
 :TYPE :_IHM_AT_DC_REP_TYPE
)