
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 44629499
 :NAME :_PE_AA_EQUA_BASEFILTER
 :COMMENT :|PE.Equation.base_filter|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 4000
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATION
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)