
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 44737299
 :NAME :_PE_AA_EQUA_INPUTMODE
 :COMMENT :|PE.Equation.input_mode|
 :ALLOCATION-MODE :INSTANCE
 :DATASET 44047899
 :DEFAULT-VALUE 1.0d0
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_FILTERATT
 :STORAGE-MODE :IN-TABLE
 :TYPE :_PE_AT_EQUA_INPUTMOD
)