
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 44842799
 :NAME :_PE_AA_EQUA_PRIORITY
 :COMMENT :|PE.EquationTemplate.priority|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :DEFAULT-VALUE 0
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATEMP
 :STORAGE-MODE :IN-TABLE
 :TYPE NUMBER
)