
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 4977555399
 :NAME :TC_AA_N_MESSAGE
 :COMMENT "Number of message"
 :ALLOCATION-MODE :OPTIONAL
 :CATEGORY "Additional attributes"
 :DATASET 96270999
 :DEFAULT-VALUE 0.0d0
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE NUMBER
)