
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 4978101499
 :NAME :_TC_AA_OC_MSG_NOTE_PAD
 :COMMENT "Note pad temporary"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE OBJECT:MULTI-LINE-STRING
)