
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 4981676599
 :NAME :_TCCONV_AA_B_READ
 :COMMENT "Message read"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :LENGTH 0
 :NCLASS TEMP-TABLE::_TC_PT_CONV_TIMECARD
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)