
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 5024928799
 :NAME :_GUI_AA_S_OTHER_PRJTYPE
 :COMMENT :|ihm.other_visibilities_project_type_def|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 1238591899
 :DOCUMENTATION "Field used to store other project type value for a module"
 :LENGTH 0
 :NCLASS TEMP-TABLE::_GUI_PT_MODULES
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)