
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 504707599
 :NAME :_PE_AA_N_TEMPLATE_OVN
 :COMMENT :|PE.templateOvn|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :DOCUMENTATION "field used to store the equation template ovn"
 :LENGTH 0
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATION
 :STORAGE-MODE :IN-TABLE
 :TYPE NUMBER
)