
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 5055127499
 :NAME :_TCCONV_AA_D_TC_SD
 :COMMENT "Time card start date"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :DEFAULT-VALUE -1
 :LENGTH 0
 :NCLASS TEMP-TABLE::_TC_PT_CONV_TIMECARD
 :STORAGE-MODE :IN-TABLE
 :TYPE TIME-TYPES:DATE+
)