
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 5083667399
 :NAME :_TCCONV_AA_S_COMMENT
 :COMMENT "Comment"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :LENGTH 4000
 :NCLASS TEMP-TABLE::_TC_PT_CONV_TIMECARD
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:MULTI-LINE-STRING
)