
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 5260585099
 :NAME :_TC_AA_S_PERIOD
 :COMMENT "Period"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)