
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 5282318899
 :NAME :_TC_AA_B_ACT_REP
 :COMMENT "Activity question"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :ENCRYPTION :STRING
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)