
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 698968599
 :NAME :_PE_AA_S_TPLMODIF_DETAILS
 :COMMENT :|PE.modificationsNotPropagatedToTheEquations|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 44047899
 :LENGTH 4000
 :NCLASS TEMP-TABLE::_PE_PT_EQUA_EQUATEMP
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)