
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 99907399
 :NAME :_TC_AA_B_EXTEND_RESEARCH
 :COMMENT :|timeCard.tc_extendsearch|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PROPAGATE T
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)