
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 99909599
 :NAME :_TC_AA_S_ATTRI_3_VALUE
 :COMMENT "Third expression entered by the user to filter projects"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)