
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 99907299
 :NAME :_TC_N_CURRENT_RS_NUMBER
 :COMMENT "ressource courante controlée par l'utilisateur"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :DEFAULT-VALUE 0
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PROPAGATE T
 :STORAGE-MODE :TEMPORARY
 :TYPE NUMBER
)