
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 99916499
 :NAME :_TC_AA_B_TC_RELOAD
 :COMMENT "Sheet has been reloaded from database"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS TIME-CARD-BASE:TIME-CARD
 :STORAGE-MODE :TEMPORARY
 :TYPE OBJECT:YES-OR-NO
)