
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 99910399
 :NAME :_TC_AA_S_FILTER_ON_TABLE
 :COMMENT "Formula applied on the activity table, to filter the activities which can be inserted"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :DEFAULT-VALUE "_TC_AA_B_VISIBLE_IN_TC = true"
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 4000
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)