
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 99915899
 :NAME :_TM_AA_S_RES_FIRST_NAME
 :COMMENT :|teamMember.firstName|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :LENGTH 0
 :NCLASS KERNEL-ORDO:RESOURCE
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)