
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 99913599
 :NAME :_TC_AA_N_RESOURCE
 :COMMENT "Onb de la ressource ccourante"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :DEFAULT-VALUE 0
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE NUMBER
)