
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 99913399
 :NAME :_TC_AA_D_TC_SD_TO_DISPLAY
 :COMMENT :|timeCard.StartDate|
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :DEFAULT-VALUE -1
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE TIME-TYPES:DATE+
)