
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 99914999
 :NAME :_TC_AA_NP_STATUS_MODIF_TRACE
 :COMMENT "Liste les modifications de status de la feuille"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :TEMPORARY
 :TYPE OBJECT:MULTI-LINE-STRING
 :USE-FOR-INDEX T
)