
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 99911299
 :NAME :_TC_AA_B_SWITCH_EXTRAUNIT2
 :COMMENT "Display/Hide extra unit 2 in a time sheet"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :DEFAULT-VALUE T
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :IN-TABLE
 :TYPE OBJECT:YES-OR-NO
)