
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 99913899
 :NAME :_TC_AA_S_RESOURCE
 :COMMENT "Current timecard resource"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :STORAGE-MODE :IN-TABLE
 :TYPE STRING
)