
(NEW-ATTRIBUTE:NEW-ATTRIBUTE
 :OBJECT-NUMBER 99910299
 :NAME :_TC_AA_B_EXTEND_FILTER
 :COMMENT "Allow user to extend search to whole database"
 :ALLOCATION-MODE :OPTIONAL
 :DATASET 96270999
 :HIDDEN-IN-INTRANET-SERVER T
 :LENGTH 0
 :NCLASS ORDO-REQUEST:CONTEXT-OPX2
 :PROPAGATE T
 :STORAGE-MODE :TEMPORARY
 :TYPE OBJECT:YES-OR-NO
)