
(TEMP-TABLE::_L1_PT_SR
 :OBJECT-NUMBER 321209389041
 :NAME "SAN_RDPM_SR_FNL_PF_L1"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM| :|Continuum.eSTRA|)"
 :_L1_AA_B_SR_ALLOWCASC "0"
 :_L1_AA_B_SR_AUTOPAIR "0"
 :_L1_AA_B_SR_LOCKSYNC "0"
 :_L1_AA_N_SR_PRIORITY 120.0d0
 :_L1_AA_S_SR_FILTER "SAN_RDPM_UF_ACT_B_SR_FILTER_FNL_PF"
 :_L1_AA_S_SR_SYNCSCRIPT "namespace _san_rdpm_sync_func; san_rdpm_js_sync_fnl_pf(this);"
)