
(TEMP-TABLE::TEMP-TABLE
 :OBJECT-NUMBER 129504505099
 :NAME "_L1_TT_LINKED_TRANSACTIONS"
 :COMMENT :|transactions_l1.transaction_linked|
 :COMMENT-FIELD T
 :DATASET 124972110599
 :DEPENDS-ON-CONTEXT NIL
 :DOCUMENTATION ""
 :IMAGE-NAME ""
 :IS-BS NIL
 :MACRO ""
 :NAME-FIELD T
 :NAME-INDEX T
 :ORIGIN :PROJECT
)