
(TEMP-TABLE::TEMP-TABLE
 :OBJECT-NUMBER 1576840299
 :NAME "_TC_LIST_ATTRIBUTES"
 :COMMENT "Temporary Table to manage the list of attributes"
 :COMMENT-FIELD T
 :DATASET 96270999
 :DEPENDS-ON-CONTEXT T
 :DOCUMENTATION ""
 :IMAGE-NAME ""
 :IS-BS NIL
 :MACRO ""
 :NAME-FIELD T
 :NAME-INDEX T
 :ORIGIN :PROJECT
)