
(TEMP-TABLE::_L1_PT_ROLES
 :OBJECT-NUMBER 310236604670
 :NAME "SAN_RDPM_RO_STUDY_MANAGER"
 :COMMENT "Study Manager Name"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pasteur|)"
 :_L1_AA_B_SINGLE_VAL_FIELD "1"
 :_L1_AA_S_ROLE_CLASS "$KERNEL-ORDO::WORK-STRUCTURE$"
)