
(TEMP-TABLE::_AL_PT_AL
 :OBJECT-NUMBER 316665548270
 :NAME "SAN_RDPM_AL_PE_INIT"
 :DATASET 118081000141
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :PTYPES "(:|Continuum.RDPM|)"
 :_AL_AA_AL_B_IS_ACTIVE "1"
 :_AL_AA_AL_B_ON_ALL_MODIF "0"
 :_AL_AA_AL_B_ON_CREATION "1"
 :_AL_AA_AL_B_ON_DELETE "0"
 :_AL_AA_AL_B_ON_LOAD "0"
 :_AL_AA_AL_B_ON_SAVE "0"
 :_AL_AA_AL_N_PRIORITY 0.0d0
 :_AL_AA_AL_S_CLASS "Planned expenditure"
 :_AL_AA_AL_S_FILTER "NOT TYPE IN (\"*Site*\",\"*Subject*\",\"Autoinjector\",\"Capsule\",\"Cartridge\",\"g\",\"kg\",\"Kit\",\"Pen\",\"Tablet\",\"PFS\",\"Vector genome\",\"Vial\") and not type  in (\"IPSO 1\",\"IPSO 2\")"
 :_AL_AA_AL_S_LABEL "Alert to initialize Expenditure type"
 :_AL_AA_AL_S_MSG_TYPE "NOOP"
 :_AL_AA_B_CREA_FI "0"
 :_AL_AA_N_ALERT_ONB 0
 :_AL_AA_S_MODIFY_ATTR1 "TYPE"
 :_AL_AA_S_MODIFY_FORMULA1 "IF PROJECT._ADM_ST_TEMPLATE_PRJ_FILTER OR EQUATION_OBJECT<>\"\" THEN  \"AUTO\" ELSE IF SAN_RDPM_UA_PE_N_LIBRARY_ONB<>0 THEN TYPE ELSE \"MANUAL\" FI FI"
 :_AL_AA_S_NAME "EXPENDITURE"
 :_AL_SEND_EMAIL "0"
 :_NTF_AA_B_GEN_NOTIF "0"
 :_NTF_RA_REPORTING 0
 :_TALK_RA_SHOUTOUT_MODULE 0
 :_TALK_RA_SHOUTOUT_REPORT 0
)