
(TEMP-TABLE::_L1_PT_COMPOSITE_CURVES
 :OBJECT-NUMBER 296654800072
 :NAME "SAN_RDPM_CC_HEAD"
 :COMMENT "Headcount"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_S_CC_EVAL_FORMULA "SAN_RDPM_AGT_AVAIL_ENTR +SAN_RDPM_AGT_AVAIL_EXIT "
 :_L1_AA_S_CC_FILTER1 "RESOURCE"
 :_L1_AA_S_CC_VALUE1 "not _INF_AA_B_GENERIC_RES "
)