
(TEMP-TABLE::_L1_PT_CG
 :OBJECT-NUMBER 310382164674
 :NAME "SAN_RDPM_SGC_SOURCING_REQ"
 :COMMENT "Sourcing Request Number"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_S_CG_DEF_FILE "PRINT_NUMBER(YEAR_NUMBER($DATE_OF_THE_DAY),\"####\")"
 :_L1_AA_S_CG_ENTITY "RESOURCE"
 :_L1_AA_S_CG_FORMULA "STRING(\"0\",5-LENGTH(PRINT_NUMBER(VALEUR,\"####\")))+PRINT_NUMBER(VALEUR,\"####\")"
)