
(TEMP-TABLE::_L1_PT_CG
 :OBJECT-NUMBER 143490494072
 :NAME "SAN_RDPM_SEQ_COMP_NAME"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_S_CG_DEF_FILE "ID"
 :_L1_AA_S_CG_ENTITY "__USER_TABLE_SAN_RDPM_UT_COMPETITOR"
 :_L1_AA_S_CG_FORMULA "\"CP_\"+STRING(\"0\",5-LENGTH(PRINT_NUMBER(VALEUR,\"####\")))+PRINT_NUMBER(VALEUR,\"####\")"
)