
(COMPOSITE-CURVE-TYPE:COMPOSITE-CURVE-TYPE
 :OBJECT-NUMBER 118497962499
 :COMMENT "TC Integrated ?"
 :DATASET 96270999
 :DOCUMENTATION ""
 :FILTER NIL
 :FORMULA "Undefined: function _TC_INTEGRATED_TC"
 :ORIGIN :PROJECT
 :REPRESENTATION :_TC_CC_INTEGRATED
)