
(COMPOSITE-CURVE-TYPE:COMPOSITE-CURVE-TYPE
 :OBJECT-NUMBER 118623702199
 :COMMENT "TC validated"
 :DATASET 96270999
 :DOCUMENTATION ""
 :FILTER NIL
 :FORMULA "Undefined: function _TC_STATUS_CURRENT_TC"
 :ORIGIN :PROJECT
 :REPRESENTATION :_TC_CC_VALIDATED
)