
(COMPOSITE-CURVE-TYPE:COMPOSITE-CURVE-TYPE
 :OBJECT-NUMBER 840175299
 :COMMENT "Cost_tc_supply"
 :DATASET 96270999
 :DOCUMENTATION "Cost tc"
 :FILTER NIL
 :FORMULA "Undefined: attribute (ARCHIVED_ESTIMATE_AT_COMPLETION__RM_ET_AGENDA)"
 :ORIGIN :PROJECT
 :REPRESENTATION :_TC_CC_N_COST_SUPPLY
)