
(TEMP-TABLE::_L1_PT_SETTINGS
 :OBJECT-NUMBER 143584561660
 :NAME "EMAIL_NOTIFICATION_RECEPIENT"
 :COMMENT "Recepients for Email Notifications for Non Prod"
 :DATASET 143364256541
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_CUST_SETTING "0"
 :_L1_AA_DU_CUST_SETTING 0
 :_L1_AA_D_CUST_SETTING 0
 :_L1_AA_N_CUST_SETTING 0.0d0
 :_L1_AA_S_CUST_SETTING "AMS_20_GSC_CRCF_PLANISWARE@emailph4.aventis.com"
 :_L1_AA_S_TYP_CUST_SETTING "STRING"
)