
(TEMP-TABLE::_L1_PT_SETTINGS
 :OBJECT-NUMBER 321200640741
 :NAME "SAN_CS_MONTH_REP_LAST_EXPORT_ONB_EVENT"
 :COMMENT "ONB of the event that store the MR zip file"
 :DATASET 143364256541
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_CF_CUST_SET "0"
 :_L1_AA_B_CUST_SETTING "0"
 :_L1_AA_B_GLOBAL_CUST_SET "1"
 :_L1_AA_B_PRJ_CUST_SET "0"
 :_L1_AA_DU_CUST_SETTING 0
 :_L1_AA_D_CUST_SETTING 0
 :_L1_AA_N_CUST_SETTING 0.0d0
 :_L1_AA_S_TYP_CUST_SETTING "NUMBER"
)