
(TEMP-TABLE::_L1_PT_TABLE_KEY
 :OBJECT-NUMBER 283130855169
 :NAME "ACTIVITY:(:USER_ATTRIBUTE_SAN_RDPM_UA_S_ACT_PROJECT_ID_F :USER_ATTRIBUTE_SAN_RDPM_UF_B_CRITIC_PATH_REF)"
 :COMMENT "SAN_RDPM_TK_NEWLY_CRITIC_PATH"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_S_TK_ENTITY "ACTIVITY"
 :_L1_AA_S_TK_KEY_ATT "USER_ATTRIBUTE_SAN_RDPM_UA_S_ACT_PROJECT_ID_F,USER_ATTRIBUTE_SAN_RDPM_UF_B_CRITIC_PATH_REF"
)