
(TEMP-TABLE::_L1_PT_TABLE_KEY
 :OBJECT-NUMBER 321315205382
 :NAME "RESOURCE:(:USER_ATTRIBUTE_SAN_UA_RDPM_RES_EMPL_NUM)"
 :COMMENT "Employee number"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_S_TK_ENTITY "RESOURCE"
 :_L1_AA_S_TK_KEY_ATT "USER_ATTRIBUTE_SAN_UA_RDPM_RES_EMPL_NUM"
)