
(NEW-ATTRIBUTE:NAT
 :OBJECT-NUMBER 123329883499
 :NAME :_RB_AT_NEWORIMPORT_H
 :COMMENT "Create new region chart or import existing one"
 :DATASET 14047310199
 :DOCUMENTATION ""
 :MAX ""
 :MIN ""
 :ORIGIN :PROJECT
 :SUBTYPE STRING
)