
(NEW-ATTRIBUTE:NAT
 :OBJECT-NUMBER 5297602799
 :NAME :_TC_AT_YES_NO
 :COMMENT "yes no for activity selection"
 :DATASET 96270999
 :DOCUMENTATION ""
 :MAX ""
 :MIN ""
 :ORIGIN :PROJECT
 :SUBTYPE STRING
)