
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 118038430855
 :NAME "SAN_DMR_RWE_PRIME_CODE"
 :DATASET 118057330253
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.eSTRA|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_RWE_UA_S_STUDY_CODE"
 :_L1_AA_S_CLASS "PROJECT"
 :_L1_AA_S_CLASS_FILTER "TRUE"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "(SAN_UA_RWE_SCP_UNIT_CODE IN (\"MED\",\"EA\") AND NOT SAN_UA_SC_B_OCCUPIED) OR ID=\"\""
)