
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 321217345341
 :NAME "SAN_RDPM_DMR_CRITICAL_PATH_SHORTNAME"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_RDPM_UA_CRITICAL_PATH_INDICATION_NAME"
 :_L1_AA_S_CLASS "__USER_TABLE_SAN_RDPM_UT_CRITICAL_PATH"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "LIST_FIND(value,currentrule.__USER_TABLE_SAN_RDPM_UT_CRITICAL_PATH.file.SAN_RDPM_UA_S_PRJ_ALL_INDIC_SHORTNAME)"
)