
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 338831522441
 :NAME "SAN_RDPM_DMR_OBS_ELEMENT_DEFAULT_VAL"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "1"
 :_L1_AA_B_NEVER_LOCK "1"
 :_L1_AA_S_ATTR "OBS"
 :_L1_AA_S_CLASS "RESOURCE"
 :_L1_AA_S_CLASS_FILTER "SAN_UA_S_RES_FORM_TYPE = \"R&D Pasteur\""
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_TAKE_VALUE "CHILD_OF.OBS_ELEMENT "
)