
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 310382236174
 :NAME "SAN_RDPM_DMR_RATE_CARD_CURRENCY"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_RDPM_UA_S_RATE_CARD_CURRENCY"
 :_L1_AA_S_CLASS "__USER_TABLE_SAN_RDPM_UT_SOURCING_RATE_CARD"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "?MONETARY_UNIT "
)