
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 143484622873
 :NAME "SAN_RDPM_DMR_ACT_BUDGET_OWNER"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_RDPM_UA_ACT_OBS_BUDGET_OWNER"
 :_L1_AA_S_CLASS "ACTIVITY"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "SAN_RDPM_UA_B_OBS_BUDGET_OWNER "
)