
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 143491497372
 :NAME "SAN_RDPM_DMR_COMP_COMPPHASE"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_RDPM_UA_COMP_PHASE"
 :_L1_AA_S_CLASS "__USER_TABLE_SAN_RDPM_UT_COMPETITOR"
 :_L1_AA_S_MSG_TYPE "WARNING"
 :_L1_AA_S_RULE "id=\"\" or SAN_RDPM_UA_AT_B_COMPETITOR_PHASE"
)