
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 310228874876
 :NAME "SAN_RDPM_DMR_EXP_TYPE_ACTUAL"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "TYPE"
 :_L1_AA_S_CLASS "WORK-PERFORMED"
 :_L1_AA_S_CLASS_FILTER "PROJECT.SAN_RDPM_UA_RD_PROJECT"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_TAKE_VALUE "\"Actual\""
)