
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 282705768041
 :NAME "SAN_RDPM_DMR_PH_PRIMARY_SKILL_MANDATORY"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "1"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "PRIMARY-SKILL"
 :_L1_AA_S_CLASS "TASK-ALLOC"
 :_L1_AA_S_MSG_TYPE "NOOP"
)