
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 321319222382
 :NAME "SAN_RDPM_DMR_LINK_GCI_ASSAY_RELEASE_DATE_LAG"
 :COMMENT "Alert to define the lag between GCI Assay task and Release date according to the reference table"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pasteur|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "DURATION"
 :_L1_AA_S_CLASS "CONSTRAINT"
 :_L1_AA_S_CLASS_FILTER "(SAN_RDPM_UA_LK_S_PRED_TYPE IN(\"V_ASSAY\",\"V_ASSAY_EXT\") AND SAN_RDPM_UA_LK_S_SUCC_TYPE IN(\"Release date\")) OR (SAN_RDPM_UA_LK_S_PRED_TYPE IN(\"V_S_SAMP-E\",\"V_S_SAMP-S\") AND SAN_RDPM_UA_LK_S_SUCC_TYPE IN(\"V_ASSAY\",\"V_ASSAY_EXT\")) "
 :_L1_AA_S_MSG_TYPE "WARNING"
 :_L1_AA_S_TAKE_VALUE "IF SAN_RDPM_UA_LK_S_PRED_TYPE IN(\"V_S_SAMP-E\",\"V_S_SAMP-S\") AND SAN_RDPM_UA_LK_S_SUCC_TYPE IN(\"V_ASSAY\",\"V_ASSAY_EXT\") AND SAN_RDPM_UA_LK_GCI_MANUAL_LAG=\"\" THEN SAN_RDPM_UA_LK_SAMPLE_GCI_LAG    ELSE IF SAN_RDPM_UA_LK_S_PRED_TYPE IN(\"V_ASSAY\",\"V_ASSAY_EXT\") AND SAN_RDPM_UA_LK_S_SUCC_TYPE IN(\"Release date\") AND SAN_RDPM_UA_LK_GCI_MANUAL_LAG=\"\" THEN SAN_RDPM_UA_LK_GCI_CLEANING_LAG   ELSE IF SAN_RDPM_UA_LK_GCI_MANUAL_LAG<>\"\" THEN SAN_RDPM_UA_LK_GCI_MANUAL_LAG  ELSE -1 FI FI  FI"
)