
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 283039693271
 :NAME "SAN_RDPM_DMR_PH_MAIN_SKILL"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pharma|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "PRIMARY-SKILL"
 :_L1_AA_S_CLASS "TASK-ALLOC"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "SAN_RDPM_UA_B_IS_MAIN_SKILL"
)