
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 142738986170
 :NAME "SAN_RDPM_DMR_BUSINESS_PROJ_STAT"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "_STA_RA_PRJ_STATUS"
 :_L1_AA_S_CLASS "PROJECT"
 :_L1_AA_S_CLASS_FILTER "SAN_RD_IS_RND_PROJECT "
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "_STA_RA_PRJ_TYPE = \"Continuum.RDPM\""
)