
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 321197062910
 :NAME "SAN_RDPM_DMR_RESOURCE_SITE"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pasteur|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "_RM_REVIEW_RA_LOCATION"
 :_L1_AA_S_CLASS "WORK-PERFORMED"
 :_L1_AA_S_MSG_TYPE "WARNING"
 :_L1_AA_S_TAKE_VALUE "RES._RM_REVIEW_RA_LOCATION "
)