
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 321178454641
 :NAME "SAN_RDPM_DMR_RES_OP_SERV"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_UA_RDPM_RES_OP_SERV"
 :_L1_AA_S_CLASS "RESOURCE"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "_INF_AA_B_GENERIC_RES AND SAN_RDPM_UA_RES_ENT_TYP =\"Service\""
)