
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 321319066482
 :NAME "SAN_RDPM_DMR_GCI_ASSAY_EXTERNAL"
 :COMMENT "DMR to identify assays always externalized based on the reference table"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pasteur|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_RDPM_UA_GCI_ASSAY_EXTERNAL"
 :_L1_AA_S_CLASS "__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY_ACTIVITY"
 :_L1_AA_S_CLASS_FILTER "BOOLEAN_VALUE(\"__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY\",SAN_RDPM_UA_GCI_ASSAY,\"SAN_RDPM_UA_GA_EXTERNAL\") AND NOT SAN_RDPM_UA_GCI_STUDY_STATUS IN(\"Completed\",\"Cancelled\")"
 :_L1_AA_S_MSG_TYPE "WARNING"
 :_L1_AA_S_TAKE_VALUE "YES"
)