
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 143485362641
 :NAME "SAN_RDPM_DMR_PH_SITE_PHARMA"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pharma|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATION_ONLY "1"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "_RM_REVIEW_RA_LOCATION"
 :_L1_AA_S_CLASS "TASK-ALLOC"
 :_L1_AA_S_CLASS_FILTER "FILE.SAN_RDPM_B_RND_PHARMA_PROJECT AND _RM_REVIEW_RA_LOCATION=\"\""
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_TAKE_VALUE "IF _RM_REVIEW_RA_ROLE.SAN_UA_RDPM_B_DISPLAYED_WBS_FORM_PHARMA THEN  þ þsan_pjs_get_wbs_form_string_value_on_object(ACTIVITY,_RM_REVIEW_RA_ROLE ,\"USER_ATTRIBUTE_SAN_UA_S_LEADER_SITE\")   ELSE þIF _RM_REVIEW_RA_ROLE._RM_REVIEW_RA_LOCATION<>\"\" THEN þþ_RM_REVIEW_RA_ROLE._RM_REVIEW_RA_LOCATION þELSE þþIF ACTIVITY._RM_REVIEW_RA_LOCATION<>\"\" THEN þþ þþþACTIVITY._RM_REVIEW_RA_LOCATION þ þþELSE þþ þþþ\"ND\"þ þ þþFI  þFI FI"
)