
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 258997107175
 :NAME "SAN_RDPM_DMR_SCOPE"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_ACTIVE "0"
 :_L1_AA_B_ATT_MANDATORY "1"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_RDPM_UA_SCOPE"
 :_L1_AA_S_CLASS "__USER_TABLE_SAN_RDPM_UT_PROJECT_TEAM_MEMBER"
 :_L1_AA_S_MSG_TYPE "WARNING"
 :_L1_AA_S_RULE "WBS_ELEMENT=\"\" OR SAN_RDPM_UA_B_IS_AN_INDICATION"
)