
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 310376741373
 :NAME "SAN_RDPM_DMR_TM_NAME"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "NAME"
 :_L1_AA_S_CLASS "__USER_TABLE_SAN_RDPM_UT_TRANSLATOR_METRICS"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_TAKE_VALUE "SAN_RDPM_UA_TM_WBS_TYPE+\"_\"+SAN_RDPM_UA_TM_COUNTRY+\"_\"+SAN_RDPM_UA_TM_LANGUAGE "
)