
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 143484756470
 :NAME "SAN_RDPM_DMR_PROJECT_MOLECULE_SUB_TYPE"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_RDPM_UA_MOLECULE_SUB_TYPE"
 :_L1_AA_S_CLASS "PROJECT"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "LEVEL=2 "
)