
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 260017743670
 :NAME "SAN_RDPM_DMR_PLAN_EXP_COST_ACC_MANDATORY"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "1"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "CBS"
 :_L1_AA_S_CLASS "EXPENDITURE"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "NOT (FROM(\"Internal Costs\"))"
)