
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 260017739070
 :NAME "SAN_RDPM_DMR_PLAN_EXP_UNIT_MANDATORY"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pharma|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "1"
 :_L1_AA_B_CREATION_ONLY "1"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "UNIT"
 :_L1_AA_S_CLASS "EXPENDITURE"
 :_L1_AA_S_CLASS_FILTER "TYPE=\"Standard\""
 :_L1_AA_S_MSG_TYPE "WARNING"
 :_L1_AA_S_TAKE_VALUE "\"k€\""
)