
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 260048952170
 :NAME "SAN_RDPM_DMR_PHARMA_PRIMARY_SKILLS"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "PRIMARY-SKILL"
 :_L1_AA_S_CLASS "RESOURCE"
 :_L1_AA_S_CLASS_FILTER "CHILD_OF.SAN_UA_RDPM_RES_TYP_PHAR AND NOT SAN_RDPM_UA_B_IS_A_TEAM AND NOT _INF_AA_B_GENERIC_RES"
 :_L1_AA_S_MSG_TYPE "WARNING"
 :_L1_AA_S_RULE "SAN_RDPM_UF_B_SELECTABLE_SKILL"
)