
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 317320310871
 :NAME "SAN_RDPM_DMR_GA_ROLE_GCI"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_RDPM_UA_GA_ROLE"
 :_L1_AA_S_CLASS "__USER_TABLE_SAN_RDPM_UT_CGI_ASSAY"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "BELONGS(\"_RM_REVIEW_PT_ROLE\",\"R&D - LSI\")"
)