
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 143484008771
 :NAME "SAN_RDPM_DMR_FUNCTION_VALUES"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pasteur|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_RDPM_UA_FUNCTION"
 :_L1_AA_S_CLASS "ACTIVITY"
 :_L1_AA_S_MSG_TYPE "CANCEL"
 :_L1_AA_S_RULE "SAN_RDPM_UA_RES_ENT_TYP = \"Department\" or id=\"\""
)