
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 310222570576
 :NAME "SAN_RDPM_DMR_ACT_STUDY_MANAGER"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pasteur|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "San_rdpm_ro_study_manager"
 :_L1_AA_S_CLASS "ACTIVITY"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "USER_IN_GROUP(ID,OC.SAN_RDPM_CS_AT_VACCINE_USER_GROUP)"
)