
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 262037003674
 :NAME "SAN_RDPM_DMR_TEAM_COST_UNIT"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "COST-UNIT"
 :_L1_AA_S_CLASS "RESOURCE"
 :_L1_AA_S_CLASS_FILTER "SAN_RDPM_UA_B_IS_A_TEAM"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_TAKE_VALUE "CHILD_OF.COST_UNIT"
)