
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 317314796876
 :NAME "SAN_RDPM_DMR_EXP_PLANNED_MONITARY_UNIT"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pasteur|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "UNIT"
 :_L1_AA_S_CLASS "EXPENDITURE"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "?MONETARY_UNIT"
)