
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 262070054474
 :NAME "SAN_RDPM_DMR_PH_ROLE_RES_FILTER_PHARMA"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pharma|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "RESOURCE"
 :_L1_AA_S_CLASS "TASK-ALLOC"
 :_L1_AA_S_CLASS_FILTER "FILE.SAN_RDPM_B_RND_PHARMA_PROJECT AND _RM_REVIEW_RA_ROLE<>\"\""
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "FROM(CURRENTRULE.PLANNED_HOURS._RM_REVIEW_RA_ROLE._RM_REVIEW_RA_RES) AND (ID=CURRENTRULE.PLANNED_HOURS._RM_REVIEW_RA_ROLE._RM_REVIEW_RA_RES OR SAN_RDPM_UA_B_IS_A_TEAM)"
)