
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 316665598974
 :NAME "SAN_RDPM_RULE_DATE_SLOT"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "1"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_RDPM_UA_S_DATE_SLOT"
 :_L1_AA_S_CLASS "__USER_TABLE_SAN_RDPM_UT_CLIN_MS_RULES"
 :_L1_AA_S_CLASS_FILTER "SAN_RDPM_UA_S_CLIN_MS_RULE_TYPE=\"Export/Field\""
 :_L1_AA_S_MSG_TYPE "NOOP"
)