
(TEMP-TABLE::_L1_PT_DCR
 :OBJECT-NUMBER 316638604576
 :NAME "SAN_RDPM_DMR_PRJ_PROJECT_CODE_PHARMA"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM.Pharma|)"
 :_L1_AA_B_ACTIVE "1"
 :_L1_AA_B_ATT_MANDATORY "0"
 :_L1_AA_B_CREATE_FILE "0"
 :_L1_AA_B_CREATION_ONLY "0"
 :_L1_AA_B_NEVER_LOCK "0"
 :_L1_AA_S_ATTR "USER_ATTRIBUTE_SAN_UA_RWE_PROJECT_CODE_PRIME"
 :_L1_AA_S_CLASS "PROJECT"
 :_L1_AA_S_CLASS_FILTER "PARENT =\"\" AND SAN_RDPM_B_RND_PHARMA_PROJECT"
 :_L1_AA_S_MSG_TYPE "NOOP"
 :_L1_AA_S_RULE "LIST_FIND(SAN_UA_PC_S_PROJECT_TYPE,\"Research,Dev,Other\")"
)