
(IMPEX::IMPEX-ATTRIBUTE
 :OBJECT-NUMBER 282808868570
 :COLUMN-NAME "SHINE_PROJECT_BIO_TYPE"
 :DATASET 118081000141
 :EXPORT-CONVERSION-FORMULA "STRING_VALUE(\"__USER_TABLE_SAN_RDPM_UT_MOLECULE_TYPE\",SAN_RDPM_DA_MOLECULE_SUB_TYPE,\"DESC\")"
 :EXTERNAL-TYPE STRING
 :IMPEX-FORMAT 282808793470
 :IMPORT-ATTRIBUTE :SAN_RDPM_DA_MOLECULE_SUB_TYPE
 :LENGTH 255
 :OFFSET 8
 :PLANISWARE-ATTRIBUTE :SAN_RDPM_DA_MOLECULE_SUB_TYPE
 :SOURCE-DCR-SYNC-OBJECTS 0
)