
(IMPEX::IMPEX-ATTRIBUTE
 :OBJECT-NUMBER 321321226082
 :CONTROL-FORMULA "IF TYPE=\"Actual\" THEN TRUE ELSE FALSE FI"
 :DATASET 118081000141
 :ERROR-FORMULA "\"The type must be \\\"Actual\\\". The current value is \"+TYPE+\".\""
 :EXTERNAL-TYPE STRING
 :IMPEX-FORMAT 321321222282
 :IMPORT-ATTRIBUTE :TYPE
 :IMPORT-CONVERSION-FORMULA "\"Actual\""
 :LENGTH 24
 :OFFSET 5
 :PLANISWARE-ATTRIBUTE :TYPE
 :SOURCE-DCR-SYNC-OBJECTS 0
)