
(IMPEX::IMPEX-ATTRIBUTE
 :OBJECT-NUMBER 321305198782
 :DATASET 118081000141
 :EXTERNAL-TYPE TIME-TYPES:DATE+
 :IMPEX-FORMAT 321305193682
 :IMPORT-ATTRIBUTE :|SAN_RDPM_UA_ACTUALS_WORKDAY_LAST_DAY_OF_WORK_FOR_LEAVE (LAST DAY OF WORK FOR LEAVE)|
 :LENGTH 25
 :OFFSET 15
 :PLANISWARE-ATTRIBUTE :USER_ATTRIBUTE_SAN_RDPM_UA_ACTUALS_WORKDAY_LAST_DAY_OF_WORK_FOR_LEAVE
 :PLIST (:FORMAT "DD/MM/YYYY")
 :SOURCE-DCR-SYNC-OBJECTS 0
)