
(TEMP-TABLE::_HOME_PT_AGGREG_CATEGORY
 :OBJECT-NUMBER 142734871970
 :NAME "SAN_WA_RDPM_EMAILING_TC_VALIDATION"
 :COMMENT "#@RDPM.SAN_RDPM_TK_EMAIL_TC_VAL_MAIL_SUBJECT"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_HOME_AA_B_CARD_MODE "1"
 :_HOME_AA_B_COMMON_DATA "0"
 :_HOME_AA_B_DEFAULT "1"
 :_HOME_AA_B_MAIL_MACRO "1"
 :_HOME_AA_B_NO_DONE "0"
 :_HOME_AA_B_NO_REMINDER "0"
 :_HOME_AA_B_PORT_MANDATORY "0"
 :_HOME_AA_B_SORT_INCREASE "1"
 :_HOME_AA_B_TOTAL_ONLY "1"
 :_HOME_AA_N_ADD_ELT_OPEN 10.0d0
 :_HOME_AA_N_ELT_CLOSED 10.0d0
 :_HOME_AA_N_OBJ_IN_MAIL 50.0d0
 :_HOME_AA_N_ORDER 0.0d0
 :_HOME_AA_S_CLASS "MANAGED-RESOURCES"
 :_HOME_AA_S_CURRENT_MODULE "HOME"
 :_HOME_AA_S_DATE_FIELD "oc.SAN_UA_RDPM_TC_DEADLINE"
 :_HOME_AA_S_FILTER "SAN_UA_RDPM_B_SEND_NOTIF_ALL_CONDITIONS  AND (SAN_UA_RDPM_RES_TYP_PHAR OR SAN_UA_RDPM_RES_TYP_PAST) AND USER_IN_GROUP($CURRENT_USER,MANAGER)"
 :_HOME_AA_S_FORMULA "SAN_RDPM_UA_TC_MAIL_CONTENT "
 :_HOME_AA_S_GROUP_READ "P_ADM,O_GBU_VACCINES,O_GSF_RND"
 :_HOME_AA_S_MAIL_URL "\"https://sanofi-continuum.planisware.live/\""
 :_HOME_AA_S_T_FORMULA "WRITE_TEXT_KEY(\"RDPM.SAN_RDPM_TK_EMAIL_TC_VAL_MAIL_SUBJECT\")"
 :_HOME_RA_LINK 4900601399
 :_HOME_RA_LINK2 0
)