
(TEMP-TABLE::_HOME_PT_AGGREG_CATEGORY
 :OBJECT-NUMBER 317268849241
 :NAME "SAN_RDPM_WA_PHARMA_PRJ_END_DATE"
 :COMMENT "R&D Pharma Project Quality control"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_HOME_AA_B_CARD_MODE "1"
 :_HOME_AA_B_COMMON_DATA "0"
 :_HOME_AA_B_DEFAULT "1"
 :_HOME_AA_B_MAIL_MACRO "0"
 :_HOME_AA_B_NO_DONE "0"
 :_HOME_AA_B_NO_HELP_BUBBLE "0"
 :_HOME_AA_B_NO_REMINDER "0"
 :_HOME_AA_B_PORT_MANDATORY "0"
 :_HOME_AA_B_SORT_INCREASE "0"
 :_HOME_AA_B_TOTAL_ONLY "1"
 :_HOME_AA_N_ADD_ELT_OPEN 1.0d0
 :_HOME_AA_N_ELT_CLOSED 0.0d0
 :_HOME_AA_N_OBJ_IN_MAIL 10.0d0
 :_HOME_AA_N_ORDER 0.0d0
 :_HOME_AA_S_AUTHOR_FORM "OWNER"
 :_HOME_AA_S_CLASS "ORDO-PROJECT"
 :_HOME_AA_S_CURRENT_MODULE "HOME"
 :_HOME_AA_S_DATE_FIELD "PF"
 :_HOME_AA_S_FILTER "SAN_RDPM_UA_PRJ_RND_PRJ AND PF>=DATE_ADDTIMEUNIT($DATE_OF_THE_DAY,20,\"Year\")"
 :_HOME_AA_S_FORMULA "ID+\" : Planned finish exceeds the limits for acceptable performance\""
 :_HOME_AA_S_GROUP_READ "R_ITS_ADMIN,OR_FUNCT_ADM_CONTINUUM,OR_FUNCT_ADM_PHARMA"
 :_HOME_AA_S_T_FORMULA "\"Planned finish exceeds the limits for acceptable performance\""
 :_HOME_RA_LINK 260004968570
 :_HOME_RA_LINK2 0
 :_INF_AA_S_USER_COLOR "OBJ31"
)