
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 260103759241
 :AFTER-V "Skill.SAN_RDPM_UA_B_IS_MAIN_SKILL"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Skill.SAN_RDPM_UA_B_IS_MAIN_SKILL}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Skill.SAN_RDPM_UA_B_IS_MAIN_SKILL"
 :ON-OBJECT-NUMBER 260103758941
 :USER "E0323871"
 :_CST_DA_TRANSMITTAL-ONB 0
)