
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 262038995241
 :AFTER-V "Project.SAN_RDPM_UA_PRJ_D_TERMINATION_DATE"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Project.SAN_RDPM_UA_PRJ_D_TERMINATION_DATE}
 :DATASET 118081000141
 :DATE 0
 :EVENT :M
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Project.SAN_RDPM_UA_PRJ_D_TERMINATION_DATE"
 :ON-OBJECT-NUMBER 260010138273
 :USER "E0431101"
 :_CST_DA_TRANSMITTAL-ONB 0
)