
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 282706448341
 :AFTER-V "Activity.SAN_RDPM_UA_B_SDP_LCI_LNK"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity.SAN_RDPM_UA_B_SDP_LCI_LNK}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity.SAN_RDPM_UA_B_SDP_LCI_LNK"
 :ON-OBJECT-NUMBER 260105943682
 :USER "E0323871"
 :_CST_DA_TRANSMITTAL-ONB 0
)