
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 282700754541
 :AFTER-V "Activity.SAN_RDPM_ACT_B_FILTER_OBS_WORKSPACE"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity.SAN_RDPM_ACT_B_FILTER_OBS_WORKSPACE}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity.SAN_RDPM_ACT_B_FILTER_OBS_WORKSPACE"
 :ON-OBJECT-NUMBER 282700754241
 :USER "E0046087"
 :_CST_DA_TRANSMITTAL-ONB 0
)