
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 282811884441
 :AFTER-V "Activity.SAN_UA_RDPM_ACT_S_STUDY_DESC"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity.SAN_UA_RDPM_ACT_S_STUDY_DESC}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity.SAN_UA_RDPM_ACT_S_STUDY_DESC"
 :ON-OBJECT-NUMBER 282811884141
 :USER "E0296878"
 :_CST_DA_TRANSMITTAL-ONB 0
)