
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 283130861241
 :AFTER-V "Planisware context.SAN_UA_B_CHC_PROD_DB"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_CONTINUUM_CONFIG_L1:Planisware context.SAN_UA_B_CHC_PROD_DB}
 :DATASET 118057330253
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Planisware context.SAN_UA_B_CHC_PROD_DB"
 :ON-OBJECT-NUMBER 283130860941
 :USER "E0296878"
 :_CST_DA_TRANSMITTAL-ONB 0
)