
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 296654330741
 :AFTER-V "Activity.SAN_RDPM_UA_B_TASK_EXPORT_FILTER"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity.SAN_RDPM_UA_B_TASK_EXPORT_FILTER}
 :DATASET 118081000141
 :DATE 0
 :EVENT :M
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity.SAN_RDPM_UA_B_TASK_EXPORT_FILTER"
 :ON-OBJECT-NUMBER 296637845771
 :USER "E0296878"
 :_CST_DA_TRANSMITTAL-ONB 0
)