
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 310195360141
 :AFTER-V "Activity.SAN_RDPM_UA_ACT_GNG_DATE_ACTUAL"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity.SAN_RDPM_UA_ACT_GNG_DATE_ACTUAL}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity.SAN_RDPM_UA_ACT_GNG_DATE_ACTUAL"
 :ON-OBJECT-NUMBER 310195345876
 :USER "E0455451"
 :_CST_DA_TRANSMITTAL-ONB 0
)