
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 310189064541
 :AFTER-V "Activity.SAN_UA_RDPM_LIB_ACT_CONNNECTOR"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity.SAN_UA_RDPM_LIB_ACT_CONNNECTOR}
 :DATASET 118081000141
 :DATE 0
 :EVENT :M
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity.SAN_UA_RDPM_LIB_ACT_CONNNECTOR"
 :ON-OBJECT-NUMBER 260069775674
 :USER "E0296878"
 :_CST_DA_TRANSMITTAL-ONB 0
)