
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 310222522341
 :AFTER-V "Resource role.SAN_UA_RDPM_APPLIC_WBS_TYPE"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Resource role.SAN_UA_RDPM_APPLIC_WBS_TYPE}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Resource role.SAN_UA_RDPM_APPLIC_WBS_TYPE"
 :ON-OBJECT-NUMBER 310223453676
 :USER "E0455451"
 :_CST_DA_TRANSMITTAL-ONB 0
)