
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 310200195641
 :AFTER-V "Activity.SAN_RDPM_UA_N_ACT_COST_TO_LAUNCH"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity.SAN_RDPM_UA_N_ACT_COST_TO_LAUNCH}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity.SAN_RDPM_UA_N_ACT_COST_TO_LAUNCH"
 :ON-OBJECT-NUMBER 310200074876
 :USER "E0455451"
 :_CST_DA_TRANSMITTAL-ONB 0
)