
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 310301801441
 :AFTER-V "Resource.SAN_RDPM_UA_B_UPDATE_TC_MANAGER"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Resource.SAN_RDPM_UA_B_UPDATE_TC_MANAGER}
 :DATASET 118081000141
 :DATE 0
 :EVENT :M
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Resource.SAN_RDPM_UA_B_UPDATE_TC_MANAGER"
 :ON-OBJECT-NUMBER 310222389272
 :USER "E0455451"
 :_CST_DA_TRANSMITTAL-ONB 0
)