
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 316662971141
 :AFTER-V "Project.SAN_RDPM_UA_S_FUNDING_ZONE"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Project.SAN_RDPM_UA_S_FUNDING_ZONE}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Project.SAN_RDPM_UA_S_FUNDING_ZONE"
 :ON-OBJECT-NUMBER 282705342072
 :USER "E0455451"
 :_CST_DA_TRANSMITTAL-ONB 0
)