
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 316662788041
 :AFTER-V "Activity.SAN_RDPM_UF_ACT_D_FPI_PF_F"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity.SAN_RDPM_UF_ACT_D_FPI_PF_F}
 :DATASET 118081000141
 :DATE 0
 :EVENT :M
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity.SAN_RDPM_UF_ACT_D_FPI_PF_F"
 :ON-OBJECT-NUMBER 296660611082
 :USER "E0296878"
 :_CST_DA_TRANSMITTAL-ONB 0
)