
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 317250191641
 :AFTER-V "Activity.SAN_RDPM_UA_B_IS_A_COUNTRY"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity.SAN_RDPM_UA_B_IS_A_COUNTRY}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity.SAN_RDPM_UA_B_IS_A_COUNTRY"
 :ON-OBJECT-NUMBER 317250191341
 :USER "E0296878"
 :_CST_DA_TRANSMITTAL-ONB 0
)