
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 317253241441
 :AFTER-V "Activity.SAN_RDPM_B_DISPLAYED_MR_TIMELINE"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity.SAN_RDPM_B_DISPLAYED_MR_TIMELINE}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity.SAN_RDPM_B_DISPLAYED_MR_TIMELINE"
 :ON-OBJECT-NUMBER 317253249876
 :USER "E0455451"
 :_CST_DA_TRANSMITTAL-ONB 0
)