
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 317295971541
 :AFTER-V "Sponsor.SAN_RDPM_UA_SPONSOR_CODE"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Sponsor.SAN_RDPM_UA_SPONSOR_CODE}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Sponsor.SAN_RDPM_UA_SPONSOR_CODE"
 :ON-OBJECT-NUMBER 317296823176
 :USER "E0455451"
 :_CST_DA_TRANSMITTAL-ONB 0
)