
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 317250394041
 :AFTER-V "Activity.SAN_RDPM_UA_S_STUDY_MANAGER_SITE"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity.SAN_RDPM_UA_S_STUDY_MANAGER_SITE}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity.SAN_RDPM_UA_S_STUDY_MANAGER_SITE"
 :ON-OBJECT-NUMBER 317250052210
 :USER "E0455451"
 :_CST_DA_TRANSMITTAL-ONB 0
)