
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 317291720541
 :AFTER-V "Activity type.SAN_RDPM_UA_B_RPP_ACT"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity type.SAN_RDPM_UA_B_RPP_ACT}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity type.SAN_RDPM_UA_B_RPP_ACT"
 :ON-OBJECT-NUMBER 317291961076
 :USER "E0455451"
 :_CST_DA_TRANSMITTAL-ONB 0
)