
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 317295965241
 :AFTER-V "Activity type.SAN_RDPM_UA_S_MEETING_WBS_TYPE"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity type.SAN_RDPM_UA_S_MEETING_WBS_TYPE}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity type.SAN_RDPM_UA_S_MEETING_WBS_TYPE"
 :ON-OBJECT-NUMBER 317296296176
 :USER "E0455451"
 :_CST_DA_TRANSMITTAL-ONB 0
)