
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 317300422441
 :AFTER-V "INTRANET.SAN_RDPM_REP_PRJ_MR_QUANTITATIVE_INFO"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{REPORT-OBJECTS::TAB-REPORT@SAN_CF_RDPM_CONFIG_L1_ABE:INTRANET.SAN_RDPM_REP_PRJ_MR_QUANTITATIVE_INFO}
 :DATASET 118081000141
 :DATE 0
 :EVENT :M
 :INFO-PAD "Json import"
 :ON-CLASS REPORT-OBJECTS::TAB-REPORT
 :ON-OBJECT-ID "INTRANET.SAN_RDPM_REP_PRJ_MR_QUANTITATIVE_INFO"
 :ON-OBJECT-NUMBER 316670052776
 :USER "E0455451"
 :_CST_DA_TRANSMITTAL-ONB 0
)