
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 321178471941
 :AFTER-V "INTRANET.SAN_RDPM_REP_TABLE_OF_BUD_FTE_ACT"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{REPORT-OBJECTS::TAB-REPORT@SAN_CF_RDPM_CONFIG_L1:INTRANET.SAN_RDPM_REP_TABLE_OF_BUD_FTE_ACT}
 :DATASET 118081000141
 :DATE 0
 :EVENT :M
 :INFO-PAD "Json import"
 :ON-CLASS REPORT-OBJECTS::TAB-REPORT
 :ON-OBJECT-ID "INTRANET.SAN_RDPM_REP_TABLE_OF_BUD_FTE_ACT"
 :ON-OBJECT-NUMBER 317316001676
 :USER "E0499298"
 :_CST_DA_TRANSMITTAL-ONB 0
)