
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 321191113941
 :AFTER-V "Resource.SAN_RDPM_UA_B_BPAC_RES_FILTER"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Resource.SAN_RDPM_UA_B_BPAC_RES_FILTER}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Resource.SAN_RDPM_UA_B_BPAC_RES_FILTER"
 :ON-OBJECT-NUMBER 321193803074
 :USER "E0477351"
 :_CST_DA_TRANSMITTAL-ONB 0
)