
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 321206782741
 :AFTER-V "RDPM.SAN_RDPM_TK_MR_KEY_ACHIEVEMENTS"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{#|Unknown Object|#TEMP-TABLE::_TK_PT_TK@SAN_CF_RDPM_CONFIG_L1:RDPM.SAN_RDPM_TK_MR_KEY_ACHIEVEMENTS}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS TEMP-TABLE::_TK_PT_TK
 :ON-OBJECT-ID "RDPM.SAN_RDPM_TK_MR_KEY_ACHIEVEMENTS"
 :ON-OBJECT-NUMBER 321207095076
 :USER "E0455451"
 :_CST_DA_TRANSMITTAL-ONB 0
)