
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 336984102041
 :AFTER-V "Activity.SAN_RDPM_UA_SHINE_ACT_PRJ_CODE"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Activity.SAN_RDPM_UA_SHINE_ACT_PRJ_CODE}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Activity.SAN_RDPM_UA_SHINE_ACT_PRJ_CODE"
 :ON-OBJECT-NUMBER 336984101741
 :USER "E0533655"
 :_CST_DA_TRANSMITTAL-ONB 0
)