
(USER-TRACE::TRACE-LOG
 :OBJECT-NUMBER 337654297641
 :AFTER-V "Planned hours.SAN_RDPM_UA_S_ROLE_CPLX_FACTOR"
 :ATTRIBUTE-ID :ID
 :BEFORE-V #{NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE@SAN_CF_RDPM_CONFIG_L1:Planned hours.SAN_RDPM_UA_S_ROLE_CPLX_FACTOR}
 :DATASET 118081000141
 :DATE 0
 :EVENT :C
 :INFO-PAD "Json import"
 :ON-CLASS NEW-ATTRIBUTE::USER-NEW-ATTRIBUTE
 :ON-OBJECT-ID "Planned hours.SAN_RDPM_UA_S_ROLE_CPLX_FACTOR"
 :ON-OBJECT-NUMBER 337654297341
 :USER "E0533655"
 :_CST_DA_TRANSMITTAL-ONB 0
)