
(ORDO-REQUEST::ENVIRONMENT-TOOL
 :OBJECT-NUMBER 1423371599
 :NAME :_GUI_TO_SHOW_SEARCH
 :COMMENT ""
 :CREATE-A-TOOL T
 :DATASET 1238591899
 :DISPLAY-CONDITION ""
 :DOCUMENTATION ""
 :FILTER ""
 :ICON NIL
 :LABEL ""
 :MODES-LIST NIL
 :MOUSE-LINE ""
 :OPX2-MACRO "_GUIINITIALIZESHORTCUTFORSEARCH"
 :SHELL-COMMAND ""
 :TOOL-BAR :DEFAULT
 :TOOL-CLASS OBJECT:EMPTY-CLASS
 :WAIT-FOR-SHELL-TO-COMPLETE NIL
)