
(ORDO-REQUEST::ENVIRONMENT-TOOL
 :OBJECT-NUMBER 1696693299
 :NAME :_GUI_TO_CLOSE_WINDOW
 :COMMENT ""
 :CREATE-A-TOOL T
 :DATASET 1238591899
 :DISPLAY-CONDITION ""
 :DOCUMENTATION ""
 :FILTER ""
 :ICON NIL
 :LABEL ""
 :MODES-LIST NIL
 :MOUSE-LINE "Close window"
 :OPX2-MACRO "_guiLogoutWithConfirmation"
 :SHELL-COMMAND ""
 :TOOL-BAR :DEFAULT
 :TOOL-CLASS OBJECT:EMPTY-CLASS
 :WAIT-FOR-SHELL-TO-COMPLETE T
)