
(ORDO-REQUEST::ENVIRONMENT-TOOL
 :OBJECT-NUMBER 46840699
 :NAME :_PM_TO_APPLY_EQUATION
 :COMMENT :|PE.apply_equation|
 :CREATE-A-TOOL T
 :DATASET 44047899
 :DISPLAY-CONDITION ""
 :DOCUMENTATION ""
 :FILTER ""
 :ICON :|gear|
 :LABEL :|PE.apply_equation|
 :MODES-LIST NIL
 :MOUSE-LINE :|PE.apply_equation|
 :OPX2-MACRO "APPLY_EQUATION"
 :SHELL-COMMAND ""
 :TOOL-BAR :DEFAULT
 :TOOL-CLASS ARCHIVE:ARCHIVABLE-OBJECT
 :WAIT-FOR-SHELL-TO-COMPLETE NIL
)