
(TEMP-TABLE::_LO_PT_LO
 :OBJECT-NUMBER 143484884872
 :NAME "SAN_RDPM_LK_ACT_B_WORKSPACE"
 :COMMENT "Hide Activities with obs different"
 :DATASET 118081000141
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :_LO_AA_B_BEFORE_APPLY "0"
 :_LO_AA_B_IS_ACTIVE "0"
 :_LO_AA_B_ON_ALL_MODIF "1"
 :_LO_AA_B_ON_CREATION "0"
 :_LO_AA_B_ON_DELETE "0"
 :_LO_AA_S_CLASS "ACTIVITY"
 :_LO_AA_S_FILTER "SAN_RDPM_ACT_B_FILTER_OBS_WORKSPACE"
 :_LO_AA_S_TYPE "NO_READ_PROPERTIES"
)