
(TEMP-TABLE::_LO_PT_LO
 :OBJECT-NUMBER 260079244373
 :NAME "SAN_RDPM_LO_PH_RO_ATTRIBUTES"
 :COMMENT "Lock on read only attributes"
 :DATASET 118081000141
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :PTYPES "(:|Continuum.RDPM|)"
 :_LO_AA_B_BEFORE_APPLY "0"
 :_LO_AA_B_IS_ACTIVE "1"
 :_LO_AA_B_ON_ALL_MODIF "0"
 :_LO_AA_B_ON_CREATION "0"
 :_LO_AA_B_ON_DELETE "0"
 :_LO_AA_S_CLASS "TASK-ALLOC"
 :_LO_AA_S_ON_ATT_MODIF "RSKILLS"
 :_LO_AA_S_TYPE "READ"
)