
(TEMP-TABLE::_LO_PT_LO
 :OBJECT-NUMBER 310263691476
 :NAME "SAN_RDPM_LO_PRJ_PPP_PROJECT_FIELDS"
 :COMMENT "Lock the PPP Project Fields for R_PM, R_STPM and OR_PLANNER_VACCINES"
 :DATASET 118081000141
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :PTYPES "(:|Continuum.RDPM.Pasteur|)"
 :_LO_AA_B_BEFORE_APPLY "0"
 :_LO_AA_B_IS_ACTIVE "1"
 :_LO_AA_B_ON_ALL_MODIF "0"
 :_LO_AA_B_ON_CREATION "0"
 :_LO_AA_B_ON_DELETE "0"
 :_LO_AA_S_CLASS "PROJECT"
 :_LO_AA_S_FILTER "USER_IN_GROUP($CURRENT_USER,\"R_PM,R_STPM,OR_PLANNER_VACCINES\")"
 :_LO_AA_S_ON_ATT_MODIF "USER_ATTRIBUTE_SAN_RDPM_UA_OBJECTIVE,_STA_RA_PRJ_STATUS,USER_ATTRIBUTE_SAN_RDPM_UA_PARTNER_NAME,USER_ATTRIBUTE_SAN_RDPM_UA_PM_PRJ_PORT,USER_ATTRIBUTE_SAN_RDPM_UA_S_PPP_PM,USER_ATTRIBUTE_SAN_RDPM_UA_S_PPP_PL,USER_ATTRIBUTE_SAN_RDPM_UA_S_PL_ENTITY,USER_ATTRIBUTE_SAN_RDPM_UA_PUBLIC_FUNDING_ORGANIZATION,USER_ATTRIBUTE_SAN_RDPM_UA_PROJECT_PHASE,USER_ATTRIBUTE_SAN_RDPM_UA_FRANCHISE,USER_ATTRIBUTE_SAN_RDPM_UA_D_ENTERING_DATE_DEV,USER_ATTRIBUTE_SAN_RDPM_UA_D_ENTERING_DATE_PREDEV,USER_ATTRIBUTE_SAN_RDPM_UA_D_EXITING_DATE_DEV,USER_ATTRIBUTE_SAN_RDPM_UA_D_EXITING_DATE_PREDEV,USER_ATTRIBUTE_SAN_RDPM_UA_S_COMMENT_RD_PIPELINE,USER_ATTRIBUTE_SAN_RDPM_UA_S_ADDITIONAL_COMMS_TERMINATION"
 :_LO_AA_S_TYPE "READ"
)