
(TEMP-TABLE::_LO_PT_LO
 :OBJECT-NUMBER 260141428476
 :NAME "SAN_RDPM_LK_ACT_CSC_ATTRIBUTES"
 :COMMENT "Pharma & Vaccine : CSC attributes only (exception for DMM DO-Storage conditions)"
 :DATASET 118081000141
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :PTYPES "(:|Continuum.RDPM.Pharma| :|Continuum.RDPM.Pasteur|)"
 :_LO_AA_B_BEFORE_APPLY "0"
 :_LO_AA_B_IS_ACTIVE "1"
 :_LO_AA_B_ON_ALL_MODIF "0"
 :_LO_AA_B_ON_CREATION "0"
 :_LO_AA_B_ON_DELETE "0"
 :_LO_AA_S_CLASS "ACTIVITY"
 :_LO_AA_S_FILTER "NOT WBS_TYPE.SAN_RDPM_UA_CSC_PACKAGING and NOT SAN_RDPM_UA_S_ACT_DMM"
 :_LO_AA_S_ON_ATT_MODIF "USER_ATTRIBUTE_SAN_RDPM_UA_ACT_PACK_ITEM_UT_COST,USER_ATTRIBUTE_SAN_RDPM_UA_ACT_ARMS_NUMBER,USER_ATTRIBUTE_SAN_RDPM_UA_ACT_IP_BATCH,USER_ATTRIBUTE_SAN_RDPM_UA_ACT_KITS_QUANTITY,USER_ATTRIBUTE_SAN_RDPM_UA_ACT_CAMPAIGN_NUMBER,USER_ATTRIBUTE_SAN_RDPM_UA_ACT_PACKAGING_TYPE,USER_ATTRIBUTE_SAN_RDPM_UA_ACT_STOCKAGE_CONDITIONS"
 :_LO_AA_S_TYPE "READ"
)