
(TEMP-TABLE::_LO_PT_LO
 :OBJECT-NUMBER 310222943976
 :NAME "SAN_RDPM_LK_PRJ_PRIO_INF"
 :COMMENT "Lock on fields Prio information tab"
 :DATASET 118081000141
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :PTYPES "(:|Continuum.RDPM.Pasteur|)"
 :_LO_AA_B_BEFORE_APPLY "0"
 :_LO_AA_B_IS_ACTIVE "1"
 :_LO_AA_B_ON_ALL_MODIF "0"
 :_LO_AA_B_ON_CREATION "0"
 :_LO_AA_B_ON_DELETE "0"
 :_LO_AA_S_CLASS "ACTIVITY"
 :_LO_AA_S_FILTER "NOT USER_IN_GROUP($CURRENT_USER,\"P_ADM,R_PORT_VACCINES\")"
 :_LO_AA_S_ON_ATT_MODIF "USER_ATTRIBUTE_SAN_RDPM_UA_ACT_COMMITMENT,USER_ATTRIBUTE_SAN_RDPM_UA_N_ACT_NPV,USER_ATTRIBUTE_SAN_RDPM_UA_N_ACT_COST_TO_LAUNCH,USER_ATTRIBUTE_SAN_RDPM_UA_N_ACT_INCR_PEAK_SALES,USER_ATTRIBUTE_SAN_RDPM_UA_N_ACT_INCR_YEAR_CUMUL_FORECAST,USER_ATTRIBUTE_SAN_RDPM_UA_ACT_INDICATION_DATE,USER_ATTRIBUTE_SAN_RDPM_UA_ACT_PRIO_COMMENT,USER_ATTRIBUTE_SAN_RDPM_UA_ACT_SEGMENT,USER_ATTRIBUTE_SAN_RDPM_UA_ACT_S_ECO_VALUE"
 :_LO_AA_S_TYPE "READ"
)