
(TEMP-TABLE::_LO_PT_LO
 :OBJECT-NUMBER 317250042410
 :NAME "SAN_RDPM_LO_FUNCTIONAL_ADM_ACCES_RIGHT"
 :COMMENT "Locking users functionalities for functional admin"
 :DATASET 118081000141
 :EXTERNAL-ID 0
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PARENT 0
 :_LO_AA_B_BEFORE_APPLY "0"
 :_LO_AA_B_IS_ACTIVE "1"
 :_LO_AA_B_ON_ALL_MODIF "0"
 :_LO_AA_B_ON_CREATION "0"
 :_LO_AA_B_ON_DELETE "0"
 :_LO_AA_S_CLASS "USER"
 :_LO_AA_S_FILTER "NOT BOOLEAN_VALUE(\"USER\",$CURRENT_USER,\"?ADMIN\") AND $CURRENT_USER<>\"\""
 :_LO_AA_S_ON_ATT_MODIF "_ADM_AA_S_NEW_PWD,_ADM_AA_S_CONFIRM_PWD,REPLAY-ALLOWED,OPX2-VOYAGER-ACCESS,OPX2-SERVER-ACCESS,EXPLORER-ACCESS,OPX2-PRO-ACCESS,ACTIVETAB-ACCESS,USER_ATTRIBUTE_SAN_UA_B_USER_TO_DELIVER,USER_ATTRIBUTE_SAN_UA_RWE_B_TECH_USER,TEAM-MEMBER,SHAREPOINT-ACCESS,ADMIN,USER_ATTRIBUTE_SAN_UA_S_AD_COUNTRY_CODE,USER_ATTRIBUTE_SAN_UA_S_AD_TITLE,USER_ATTRIBUTE_SAN_UA_S_AD_SITE,USER_ATTRIBUTE_SAN_UA_S_AD_LOCALITY,USER_ATTRIBUTE_SAN_UA_S_AD_FAMILY_NAME,USER_ATTRIBUTE_SAN_UA_S_AD_GIVEN_NAME,USER_ATTRIBUTE_SAN_UA_S_AD_DIVISION,USER_ATTRIBUTE_SAN_UA_S_AD_DEPARTMENT,USER_ATTRIBUTE_SAN_UA_S_AD_COUNTRY_NAME,USER_ATTRIBUTE_SAN_UA_D_USR_CRE_CON,USER_ATTRIBUTE_SAN_UA_D_USR_LAST_CON,USER_ATTRIBUTE_SAN_RDPM_UA_USER_B_NOTIF_SEND"
 :_LO_AA_S_TYPE "READ"
)