
(JAVASCRIPT::JAVASCRIPT
 :OBJECT-NUMBER 119922462599
 :NAME :_TC_JS2_TIMECARD_CONV
 :COMMENT ""
 :COMPILE-IF-POSSIBLE T
 :CONTROL-ARGUMENTS T
 :DATA-LENGTH 0
 :DATASET 96270999
 :DEFFERED-LOAD T
 :DOCUMENTATION ""
 :EVALUATE-ON-LOAD T
 :EVALUATE-ONE-TIME T
 :GENERATE-MACRO NIL
 :LAST-SYNCHRONIZATION-DATE NIL
 :LOCKING-PASSWORD NIL
 :ORIGIN :PROJECT
 :PROCESSES-API NIL
 :SCRIPT-LANGUAGE NIL
 :SYNCHRONIZE-WITH-FILE "processes/scripts/timecard/timecardconv.pjs"
 :VC-VERSION ""
 :VERSION 0
)