
(JAVASCRIPT::JAVASCRIPT
 :OBJECT-NUMBER 1248516599
 :NAME :_IHM_JS_LIBRARY
 :COMMENT "Ihm management"
 :COMPILE-IF-POSSIBLE T
 :CONTROL-ARGUMENTS T
 :DATA-LENGTH 0
 :DATASET 1238591899
 :DEFFERED-LOAD T
 :DOCUMENTATION ""
 :EVALUATE-ON-LOAD T
 :EVALUATE-ONE-TIME T
 :GENERATE-MACRO NIL
 :LAST-SYNCHRONIZATION-DATE NIL
 :LOCKING-PASSWORD NIL
 :ORIGIN :PROJECT
 :PROCESSES-API NIL
 :SCRIPT-LANGUAGE NIL
 :SYNCHRONIZE-WITH-FILE "processes/opx2it/_ihm_js_library.ojs"
 :VC-VERSION ""
 :VERSION 0
)