
(JAVASCRIPT::JAVASCRIPT
 :OBJECT-NUMBER 127164357299
 :NAME :_DQA_JS2_HMI
 :COMMENT "DQA HMI"
 :COMPILE-IF-POSSIBLE T
 :CONTROL-ARGUMENTS T
 :DATA-LENGTH 0
 :DATASET 127151640799
 :DEFFERED-LOAD T
 :DOCUMENTATION ""
 :EVALUATE-ON-LOAD T
 :EVALUATE-ONE-TIME T
 :GENERATE-MACRO NIL
 :LAST-SYNCHRONIZATION-DATE NIL
 :LOCKING-PASSWORD NIL
 :ORIGIN :PROJECT
 :PROCESSES-API NIL
 :SCRIPT-LANGUAGE NIL
 :SYNCHRONIZE-WITH-FILE "processes/scripts/dqa/hmi.pjs"
 :VC-VERSION ""
 :VERSION 0
)