
(JAVASCRIPT::JAVASCRIPT
 :OBJECT-NUMBER 260007785741
 :NAME :SAN_RDPM_JS_WBS_FORM
 :COMMENT "WBS Form bindings"
 :COMPILE-IF-POSSIBLE T
 :CONTROL-ARGUMENTS T
 :DATA-LENGTH 0
 :DATASET 118081000541
 :DEFFERED-LOAD T
 :DOCUMENTATION ""
 :EVALUATE-ON-LOAD T
 :EVALUATE-ONE-TIME T
 :GENERATE-MACRO NIL
 :LAST-SYNCHRONIZATION-DATE NIL
 :LOCKING-PASSWORD NIL
 :ORIGIN :PROJECT
 :PROCESSES-API NIL
 :SCRIPT-LANGUAGE NIL
 :SYNCHRONIZE-WITH-FILE NIL
 :VC-VERSION ""
 :VERSION 0
)