
(JAVASCRIPT::JAVASCRIPT
 :OBJECT-NUMBER 310233698441
 :NAME :PROV_03
 :COMMENT "Provisioned script"
 :COMPILE-IF-POSSIBLE T
 :CONTROL-ARGUMENTS T
 :DATA-LENGTH 0
 :DATASET 118081000541
 :DEFFERED-LOAD T
 :DOCUMENTATION ""
 :EVALUATE-ON-LOAD NIL
 :EVALUATE-ONE-TIME T
 :GENERATE-MACRO NIL
 :LAST-SYNCHRONIZATION-DATE NIL
 :LOCKING-PASSWORD NIL
 :ORIGIN :PROJECT
 :PROCESSES-API NIL
 :SCRIPT-LANGUAGE NIL
 :SYNCHRONIZE-WITH-FILE NIL
 :VC-VERSION ""
 :VERSION 0
)