
(TEMP-TABLE::_SLT_PT_SLOT_SETTING
 :OBJECT-NUMBER 310370703570
 :NAME "_INF_AA_S_TEMP_OPERATOR"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :_SLT_AA_B_ADMIN_ONLY "0"
 :_SLT_AA_B_HIDE "0"
 :_SLT_AA_N_USER_LENGTH 0.0d0
 :_SLT_AA_S_CLASS "_INF_TT_CURRENT_FILTER_PANEL"
 :_SLT_AA_S_DEFAULT_VALUE "="
)