
(TEMP-TABLE::_SLT_PT_SLOT_SETTING
 :OBJECT-NUMBER 143370479872
 :NAME "USER_ATTRIBUTE_SAN_RDPM_UA_CP_TC_PORT_CHOICE"
 :DATASET 118081000141
 :ORIGIN-NUMBER 0
 :ORIGIN-PROJECT 0
 :PTYPES "(:|Continuum.RDPM|)"
 :_SLT_AA_B_HIDE "0"
 :_SLT_AA_N_USER_LENGTH 0.0d0
 :_SLT_AA_S_CLASS "CONTEXT-OPX2"
 :_SLT_AA_S_DEFAULT_VALUE "My role"
 :_SLT_AA_S_MODULE "TM"
)